// Topic 8.10 — Startup, packaging and AOT. Source notes: Part-08-The-JVM/8.10-startup-packaging-aot.md
// Measurements: OpenJDK 17.0.17 (Homebrew), Apple M1, macOS. Running example: module `hello`
// (app.Main, app.Greeter, app.Polite, greeting.xml) packaged as hello.jar. Wall-clock times are medians
// of 50 interleaved runs (python perf_counter around the whole process); phase times come from
// -Xlog:startuptime,class+load with uptimenanos decorations (median of 15 runs). Leyden (JDK 24+) and
// GraalVM native image are not available on this machine: everything about them is labelled documented.
import { HELLO_MAIN, SIntro, STimeline, SClassFlood, SColdJit, SWhoCares } from './8.10/scenes1.jsx';
import { SCdsIdea, SAppCds, SCdsCheck, SLeydenShift, SLeydenWorkflow, SProfiles } from './8.10/scenes2.jsx';
import { SJdeps, SJlink, SJlinkTraps, SJpackage } from './8.10/scenes3.jsx';
import { SNativeIdea, SPointsTo, SWhatBreaks, SBuildInit, SNativeCosts, SAllTogether, SDecide, STraps, SRecap } from './8.10/scenes4.jsx';

const chapters = ['Intro', 'Why startup is slow', 'CDS and AppCDS', 'Project Leyden', 'jlink', 'jpackage', 'Native image', 'Choosing', 'Traps', 'Recap'];

const scenes = [
  { name: 'Intro', dur: 22, ch: 0, title: '', C: SIntro },
  { name: 'Timeline', dur: 50, ch: 1, title: 'Where 124 milliseconds go', C: STimeline },
  { name: 'ClassFlood', dur: 52, ch: 1, title: 'One class, then 1,287 of them', C: SClassFlood },
  { name: 'ColdJit', dur: 50, ch: 1, title: 'An interpreter that has learned nothing', C: SColdJit },
  { name: 'WhoCares', dur: 38, ch: 1, title: 'When startup is the workload', C: SWhoCares },
  { name: 'CdsIdea', dur: 56, ch: 2, title: 'Class Data Sharing: parse once, map every time', C: SCdsIdea },
  { name: 'AppCds', dur: 62, ch: 2, title: 'AppCDS: archive your own classes too', C: SAppCds },
  { name: 'CdsCheck', dur: 40, ch: 2, title: 'The archive is checked, then quietly skipped', C: SCdsCheck },
  { name: 'LeydenShift', dur: 58, ch: 3, title: 'Project Leyden: move work earlier, keep the JIT', C: SLeydenShift },
  { name: 'LeydenWorkflow', dur: 56, ch: 3, title: 'The AOT cache · JDK 24+', C: SLeydenWorkflow },
  { name: 'Profiles', dur: 42, ch: 3, title: 'AOT does not mean no JIT', C: SProfiles },
  { name: 'Jdeps', dur: 48, ch: 4, title: 'jdeps: which modules does it need?', C: SJdeps },
  { name: 'Jlink', dur: 60, ch: 4, title: 'jlink: a runtime with only those modules', C: SJlink },
  { name: 'JlinkTraps', dur: 44, ch: 4, title: 'Where jlink bites', C: SJlinkTraps },
  { name: 'Jpackage', dur: 48, ch: 5, title: 'jpackage: an installer with its own runtime', C: SJpackage },
  { name: 'NativeIdea', dur: 56, ch: 6, title: 'GraalVM native image: no JVM at run time', C: SNativeIdea },
  { name: 'PointsTo', dur: 60, ch: 6, title: 'The closed world: reachable from main, or gone', C: SPointsTo },
  { name: 'WhatBreaks', dur: 56, ch: 6, title: 'What breaks, and the fix', C: SWhatBreaks },
  { name: 'BuildInit', dur: 48, ch: 6, title: 'Build-time initialisation: a frozen heap', C: SBuildInit },
  { name: 'NativeCosts', dur: 52, ch: 6, title: 'The bill for native image', C: SNativeCosts },
  { name: 'AllTogether', dur: 44, ch: 7, title: 'The same app, every technique', C: SAllTogether },
  { name: 'Decide', dur: 54, ch: 7, title: 'Which one, when', C: SDecide },
  { name: 'Traps', dur: 36, ch: 8, title: 'Traps', C: STraps },
  { name: 'Recap', dur: 38, ch: 9, title: 'Recap', C: SRecap },
];

const captions = {
  Intro: [[0.8, 'Every Java program pays a bill before it does anything useful: startup.'], [5.5, 'Our running example, a tiny `hello.jar`, takes about 120 ms and loads almost 1,300 classes to print two lines.'], [12, 'This topic is about shrinking that bill, and the box you ship: CDS, Leyden, jlink, jpackage and native image.'], [17.5, 'Every JDK 17 number you see was measured on this machine.']],
  Timeline: [[0.5, 'Run `hello.jar` with class-data sharing switched off, and log where the time goes.'], [6, 'Before `main` even starts: 35 ms. The JVM sets up its heap, generates the interpreter and boots the module system.'], [13, 'Then the launcher opens the jar, reads the manifest and loads `app.Main`. 531 classes are loaded by now.'], [20, 'The first log line costs 57 ms: `Logger`, handlers, time-zone rules, locale data. 538 more classes.'], [28, 'Parsing a one-line XML file: 17 ms and 190 classes, mostly from `java.xml`.'], [35, 'The stream, the lambda and the reflective lookup: 4 ms and 28 classes, many generated on the fly.'], [42.3, 'Total: 1,287 classes to print two lines. Three of them are ours.']],
  ClassFlood: [[0.5, 'Each of those classes goes through the same pipeline. Follow one: `DocumentBuilderFactory`.'], [6, 'Find its bytes, here inside the JDK\'s `lib/modules` file, and parse the class file into a structure in metaspace.'], [13, 'Verify it, link it, then run its static initialiser. Per class, per process, on every start.'], [20, 'Now multiply. `java.base` alone: 1,011 classes. Then `java.xml`, `java.logging`, and 69 generated at runtime.'], [28, 'How many were verified? Only 8: our three classes, a lambda, and four locale classes.'], [35, 'HotSpot trusts the JDK\'s own boot classes and skips verifying them. Application and library classes are always verified.'], [43, 'A Spring Boot app loads thousands of library classes, all verified. JEP 483 counts about 21,000 for Spring PetClinic.']],
  ColdJit: [[0.5, 'The third cost: every method starts in the interpreter, with an empty profile.'], [5.5, '`-XX:+PrintCompilation` shows what the JIT managed during one short run.'], [11.5, '223 methods got a quick C1 compile with profiling. Only 21 reached C2.'], [18, 'And those C2 methods are tiny JDK helpers, like `String.charAt` and `String.hashCode`. None of our code.'], [25, 'So our program runs mostly interpreted, and exits long before the JIT pays off.'], [31.5, 'A long-running service gets there eventually: thousands of requests later, several times faster.'], [38.5, 'So startup is three costs: loading classes, verifying them, and an interpreter that knows nothing yet.'], [44.5, 'Every technique in this topic attacks one or more of those three.']],
  WhoCares: [[0.5, 'Does any of this matter? It depends on how long the process lives.'], [5, 'A server that runs for three weeks pays startup once. It\'s a rounding error.'], [11, 'A container that autoscales pays it on every scale-out, while traffic waits.'], [18, 'A serverless function with 200 ms of real work can spend most of its billed time starting up.'], [25, 'A command-line tool runs for a moment. Startup is the whole experience.'], [31, 'That\'s where Java loses to Go and Node, and why this corner of the JVM is changing fastest.']],
  CdsIdea: [[0.5, 'Without help, every JVM parses the same JDK classes into the same structures, on every start.'], [6, 'Class Data Sharing does that work once and writes the result to an archive file.'], [12.5, 'On the next start the JVM parses nothing. It memory-maps the archive straight into metaspace.'], [19.5, '`-Xlog:cds` shows it: regions of the archive mapped at startup, one read-write and one read-only.'], [26.5, 'Mapped pages live in the OS page cache, so a second JVM using the same archive maps the same pages.'], [33, 'The read-only part is shared by every JVM using it: less memory per process on a busy host.'], [40.3, 'Archived classes were verified when the archive was made, so that cost disappears too.'], [47.3, 'Since JDK 12 the JDK ships a default archive of its core classes. It\'s on unless you turn it off.']],
  AppCds: [[0.5, 'The default archive only holds classes the JDK picked. AppCDS archives the ones your app uses.'], [5, 'Step one, a training run: `-XX:ArchiveClassesAtExit` writes every class this run loaded into `app.jsa`.'], [12, 'For us that\'s 2.2 MB, a layer on top of the JDK\'s 13.5 MB base archive.'], [18, 'Step two: start with `-XX:SharedArchiveFile=app.jsa`.'], [23, 'Now count where classes come from. With sharing off: 1,215 parsed from the JDK image.'], [29, 'Default archive: 987 mapped, but 245 still parsed. Logging, XML and locale classes weren\'t in it.'], [35, 'With AppCDS: 1,246 mapped, none parsed. Only classes generated at runtime are left.'], [42.5, 'Wall clock, median of 50 runs: 122 ms, then 81, then 75.'], [49, 'Most of our win came free from the default archive. The bigger your app, the more AppCDS adds.'], [54.6, 'Since JDK 19, `-XX:+AutoCreateSharedArchive` does both steps. On 17 it\'s an unrecognised option.']],
  CdsCheck: [[0.5, 'An archive is only valid for the exact setup that created it.'], [5, 'It records the JDK build and the class path, including each jar\'s size and modification time.'], [11.5, 'Rebuild the jar, even with identical content, and the next start can\'t use the archive.'], [17.5, 'The JVM prints one warning and carries on without it, slower. Easy to miss in a log.'], [25, 'Add `-Xshare:on` and a mismatch becomes a hard failure. Useful in CI, to catch a stale archive.'], [32.5, 'The rule: regenerate the archive in the same build step that produces the jar.']],
  LeydenShift: [[0.5, 'Project Leyden asks: what else could move from every start into one earlier training run?'], [6, 'At startup the JVM parses, verifies, loads and links classes, profiles methods, then compiles the hot ones.'], [13, 'CDS already moved parsing and verification out. That\'s where JDK 17 stops.'], [19.5, 'JDK 24, JEP 483: the AOT cache stores classes already loaded. They appear in their class loaders instantly.'], [27.5, 'And already linked, so the JVM skips wiring them together again.'], [34, 'JDK 25, JEP 515: it also stores method profiles, so the JIT can compile hot code right away.'], [41, 'JDK 26, JEP 516: cached objects now work with any collector, including ZGC.'], [48, 'What stays: the interpreter, the JIT and deoptimisation. Still a full JVM, just a well-prepared one.']],
  LeydenWorkflow: [[0.5, 'The AOT cache takes three steps. JDK 17 has none of this, so the numbers here come from the JEPs.'], [5.5, 'Record: run the app with `-XX:AOTMode=record`. The JVM notes what it loads and links.'], [12, 'Create: `-XX:AOTMode=create` turns that configuration into the cache file. No application code runs.'], [18, 'Run: every production start passes `-XX:AOTCache=app.aot`.'], [24, 'JDK 25\'s JEP 514 folds the first two into one flag: `-XX:AOTCacheOutput`.'], [30.5, 'JEP 483 reports Spring PetClinic, about 21,000 classes, starting in 2.6 s instead of 4.5 s: 42% faster.'], [38, 'The price: a 130 MB cache, and the same JDK, OS and CPU architecture for every run.'], [45, 'JEP 515\'s profiles cut a warm-up benchmark from 90 ms to 73 ms, for 250 KB more cache.'], [51, 'No code changes. Your app stays a normal JVM app.']],
  Profiles: [[0.5, 'Why keep the JIT at all? Because the best code depends on what the program does in production.'], [6, 'A cold JVM climbs: interpreter, then C1 with profiling, then C2. That climb is warm-up.'], [13, 'With cached profiles, C2 has data from the start, so the climb is shorter.'], [20, 'The peak is the same. It\'s the same C2, still free to re-profile and recompile.'], [27, 'If production behaves differently from training, it deoptimises and learns. Nothing breaks.'], [34, 'That\'s the big contrast with native image, coming up: no JIT at all.']],
  Jdeps: [[0.5, 'A full JDK 17 has 70 modules: the compiler, the debugger, Swing, JShell and much more.'], [6.5, '`jdeps` reads our bytecode and lists the modules it actually references.'], [12.5, '`--print-module-deps` prints one line: `java.base,java.logging,java.xml`.'], [19, 'Three modules out of seventy. And `java.logging` and `java.xml` each need only `java.base`.'], [26, 'Our `module-info.java` already says this, so jlink can follow the `requires` lines by itself.'], [33, 'For a plain jar without a module descriptor, `jdeps` is how you get the list.'], [40, 'But it only sees static references. Anything found by reflection or a service lookup, it can miss.']],
  Jlink: [[0.5, '`jlink` assembles a custom runtime: the modules you name, plus everything they require.'], [6, 'Point it at our module, and it follows `requires` to pull in exactly three JDK modules.'], [12.5, 'On JDK 17, compression is `--compress=2`. The `zip-6` form in many guides needs JDK 21 or later.'], [19, 'The full JDK on this machine: 305 MB. A runtime with every module: 154 MB.'], [25.5, 'Our three modules: 52 MB. Strip debug info, headers and man pages, compress: 28 MB.'], [32, 'Half of what\'s left is the JVM itself: `libjvm` is 14 MB. The class library is 12.'], [38.5, 'A surprise: the trimmed runtime starts slower, 110 ms instead of 81. It has no CDS archive.'], [46, 'Add `--generate-cds-archive`: 50 MB, and back to 75 ms. Size against startup, your choice.'], [53, 'For containers, that\'s the win: a 28 to 50 MB runtime layer instead of a 300 MB JDK.']],
  JlinkTraps: [[0.5, 'Two places where jlink bites.'], [4, 'One: every module it links must be a real, explicit module. Automatic modules are refused.'], [10.5, 'A plain jar on the module path, like this old `util-1.0.jar`, gets exactly this error.'], [17, 'So most teams jlink only the JDK modules from `jdeps`, and keep their jars on the class path.'], [24, 'Two: `jdeps` sees only static references. Services and reflection are invisible to it.'], [30.5, 'Our run quietly loaded classes from `jdk.localedata`. Leave it out and you get English-only locale data.'], [37, 'Test the trimmed runtime itself, and add modules like `jdk.localedata` by hand.']],
  Jpackage: [[0.5, '`jpackage` goes one step further: a native app the user installs, with no Java required.'], [5.5, 'It runs jlink for you, adds a native launcher, and wraps it all in the platform\'s format.'], [12, 'On macOS, `--type app-image` builds `Hello.app`: a launcher, our jar with a config file, and a private runtime.'], [19.5, 'Left to its defaults, jpackage bundled a 125 MB runtime. Naming our three modules: 29 MB.'], [27, '`--type dmg` wraps it into an 18.8 MB disk image. Windows gets `msi` or `exe`, Linux `deb` or `rpm`.'], [34.5, 'There\'s no cross-building: you make each installer on its own OS, usually in CI.'], [41, 'It\'s packaging, not speed. It starts exactly as fast as the JVM inside it.']],
  NativeIdea: [[0.5, 'GraalVM native image goes the other way: do everything at build time, then leave the JVM behind.'], [6, '`native-image` starts from `main` and works out every method the program could ever reach.'], [12.5, 'It can run static initialisers during the build and keep the objects they create: the image heap.'], [19.5, 'It compiles every reachable method to machine code, ahead of time. No bytecode survives.'], [26, 'Then it links in Substrate VM, a small runtime with a garbage collector and thread support.'], [33, 'Out comes one executable. At run time: no class loading, no verification, no interpreter, no JIT.'], [41, 'Starting it means: map the binary, map the image heap, call `main`.'], [49, 'All three startup costs, gone. The price is paid in a different currency.']],
  PointsTo: [[0.5, 'Native image assumes a closed world: everything that can run must be visible at build time.'], [6, 'The points-to analysis starts at `main` and follows every call, field and type it can prove.'], [12.5, '`Logger`, the XML parser, `List.of`, the stream: all reachable, so all compiled in.'], [19.5, 'Lambdas are fine: their `invokedynamic` call sites are linked during the build.'], [25.5, 'Then this line. The class name comes from a system property, known only at run time.'], [32, 'The analysis can\'t follow a string it can\'t see, and nothing else mentions `app.Polite`.'], [38.5, 'So `app.Polite` is not in the binary. And nothing fails at build time.'], [45, 'With a constant, `Class.forName("app.Polite")`, the analysis would fold the call and keep the class.'], [52.5, 'Everything main can\'t reach is left out too. That\'s why the binaries are small.']],
  WhatBreaks: [[0.5, 'On the JVM our app works. As a native binary it builds cleanly, then fails when it runs.'], [5.5, '`Class.forName` can\'t produce `app.Polite`: the class was never registered, so the image doesn\'t have it.'], [12.5, 'Reflection, proxies, JNI, serialization, resources with computed names: invisible unless declared.'], [19.5, 'The fix is metadata: a JSON file telling the build what will be used reflectively.'], [26.5, 'Recent GraalVM reads one `reachability-metadata.json`. Older releases used `reflect-config.json` and friends.'], [33.5, 'You rarely write it by hand. Run on the JVM with the tracing agent, and it records what was used.'], [41, 'Frameworks do it for you: Spring Boot 3, Quarkus and Micronaut generate metadata during the build.'], [48, 'The real pain: old libraries doing reflection nobody declared. They fail in production, not in the build.']],
  BuildInit: [[0.5, 'Native image can run static initialisers at build time and keep the objects they create.'], [6, 'Here `<clinit>` builds a lookup map during the build. The map is written into the binary\'s image heap.'], [13, 'At run time it\'s simply there: no initialiser, no parsing, no allocation.'], [19.5, 'But whatever a build-time initialiser captures is frozen: a timestamp, a random seed, an environment variable.'], [26, 'This field would hold the build machine\'s clock, forever, in every copy of the binary.'], [33.5, 'So application classes initialise at run time by default. You opt in with `--initialize-at-build-time`.'], [41, 'Frameworks lean on this hard: Quarkus and Spring\'s AOT mode do much of their wiring during the build.']],
  NativeCosts: [[0.5, 'Here\'s the trade, in ranges commonly reported. Not measured here: GraalVM isn\'t on this machine.'], [6, 'Startup and memory: native wins, often by a wide margin.'], [13, 'Peak throughput: native is usually lower. Without a runtime profile, C2\'s speculative tricks aren\'t available.'], [20, 'Over time, the warmed-up JVM climbs past native and stays there.'], [26.5, 'Profile-guided optimisation, a training run in Oracle GraalVM, recovers much of that gap.'], [33, 'Builds take minutes and gigabytes of memory, instead of seconds.'], [39, 'Collectors: Serial in Community Edition. G1 only in Oracle GraalVM, on Linux.'], [45.5, 'And the tools differ: many JVM agents and diagnostics don\'t apply, or work differently.']],
  AllTogether: [[0.5, 'Put the measured numbers side by side: `hello.jar` on JDK 17, median of 50 runs.'], [6, 'Sharing off: 122 ms. The default CDS archive: 81. Our own AppCDS archive: 75.'], [13, 'jlink alone: 110, slower than the full JDK. jlink with a CDS archive: 75, in a runtime a sixth the size.'], [21, 'The AOT cache isn\'t in JDK 17. JEP 483 reports 42% off Spring PetClinic\'s start.'], [28, 'Native image would start fastest of all, but it\'s no longer a JVM, and the bill is different.'], [35, 'Each bar is one idea: skip parsing, skip linking, or stop being a JVM.']],
  Decide: [[0.5, 'So which one? Start from how long the process lives.'], [5, 'A long-running server: plain JVM. Startup is amortised, and you want the JIT\'s peak.'], [11, 'Deploying often? Add AppCDS today, or the AOT cache from JDK 24. It\'s a flag, not a rewrite.'], [18, 'Image size matters? Add jlink, and give the runtime a CDS archive.'], [24.5, 'Scaling out constantly? Try both native image and the AOT cache, and measure under real load.'], [31.5, 'Serverless functions and CLI tools: native image, where cold start is the product.'], [38, 'Desktop apps: jpackage, so users never install Java.'], [44, 'The honest default: plain JVM plus the AOT cache. Take native image when cold start truly matters.']],
  Traps: [[0.5, 'Five traps worth avoiding.'], [3.5, 'AOT doesn\'t mean no JIT. Leyden keeps it. Only native image removes it.'], [9.5, 'Native image is not strictly better: lower peak, slow builds, reflection metadata.'], [15.5, 'jlink refuses automatic modules. jlink the JDK, keep your jars on the class path.'], [21.5, 'A rebuilt jar silently invalidates your CDS archive. `-Xshare:on` makes that loud.'], [27.5, 'And a trimmed runtime without a CDS archive starts slower than the full JDK.']],
  Recap: [[0.5, 'Recap.'], [3, 'Startup costs: loading classes, verifying them, and an interpreter with no profile.'], [8.5, 'CDS and AppCDS parse once and map every time. 122 down to 75 ms here.'], [14, 'Leyden\'s AOT cache adds loaded and linked classes, then profiles, and keeps the JIT.'], [19.5, 'jlink trims the runtime; jpackage ships it as an installer.'], [25, 'Native image removes the JVM: millisecond starts, a closed world, and real costs.'], [30, 'The default: plain JVM plus the AOT cache. Native image only when cold start is the requirement.']],
};

const MAIN_FULL = ['package app;', '', 'import java.util.List;', 'import java.util.logging.Logger;', 'import java.util.stream.Collectors;', 'import javax.xml.parsers.DocumentBuilderFactory;', '', 'public class Main {', ...HELLO_MAIN.map((l) => '    ' + l), '}'].join('\n');

const notes = [
  { ch: 1, blocks: [
    { p: 'The running example for the whole topic is a three-class module. It logs a line, reads a word from an XML resource, uppercases a list with a stream, and loads a greeter **by name** (that last line matters in the native-image chapter).' },
    { code: MAIN_FULL, title: 'src/hello/app/Main.java' },
    { code: 'module hello {\n    requires java.logging;\n    requires java.xml;\n}\n\n// app/Greeter.java:  public interface Greeter { String greet(String name); }\n// app/Polite.java:   public class Polite implements Greeter { … "Good day, " + name + "." }\n// greeting.xml:      <greeting>Hello</greeting>', title: 'module-info.java and friends' },
    { tryit: { note: 'Build it as a modular jar (JDK 17):', cmd: '$ javac -d out --module-source-path src -m hello\n$ cp src/hello/greeting.xml out/hello/\n$ jar --create --file hello.jar --main-class app.Main -C out/hello .\n$ java -jar hello.jar', out: 'Oct 05, 2026 12:14:39 PM app.Main main\nINFO: starting\nHello, ADA, LINUS, GRACE\nGood day, world.' } },
    { h: 'Where the time goes' },
    { mini: { scene: 'Timeline' } },
    { tryit: { note: 'HotSpot can time its own boot. JDK 17 output, sharing off (abridged):', cmd: '$ java -Xshare:off -Xlog:startuptime -jar hello.jar', out: '[0.013s][info][startuptime] Interpreter generation, 0.0006410 secs\n[0.026s][info][startuptime] Initialize java.lang classes, 0.0124152 secs\n[0.039s][info][startuptime] Initialize module system, 0.0117862 secs\n[0.039s][info][startuptime] Create VM, 0.0372228 secs' } },
    { table: { head: ['phase (ms since launch)', '-Xshare:off', 'default CDS', 'AppCDS'], rows: [['JVM created (`Create VM`)', '35', '19', '18.5'], ['`app.Main` loaded', '45.5', '25', '24'], ['first log line done, XML parsing starts', '103', '68', '64'], ['XML done, lambda created', '120', '85', '73'], ['last class loaded', '124', '87', '76']] } },
    { p: 'Medians of 15 runs with `-Xlog:startuptime,class+load` and nanosecond timestamps. Logging adds a little overhead; plain wall-clock medians over 50 runs were **122 / 81 / 75 ms**. The surprise is the **first log line**: `java.util.logging` pulls in handlers, a formatter, the time-zone database and locale data, roughly 540 classes, all executed by a cold interpreter.' },
    { h: 'One class, then 1,287' },
    { mini: { scene: 'ClassFlood' } },
    { steps: ['**Find** the bytes: a jar entry, or a resource inside the JDK\'s `lib/modules` jimage file.', '**Parse** the class file and build an `InstanceKlass` (plus its methods and constant pool) in metaspace (8.2, 8.5).', '**Verify** each method\'s bytecode with the type-checking verifier, using the `StackMapTable`.', '**Link**: prepare static fields, rewrite some bytecodes into faster internal forms, lay out the vtable and itable.', '**Initialise**: run `<clinit>` the first time the class is actively used.'] },
    { tryit: { note: 'Count them yourself. Real JDK 17 numbers:', cmd: "$ java -Xshare:off -Xlog:class+load:file=cl.txt -jar hello.jar\n$ wc -l < cl.txt\n$ grep -c 'source: jrt:/java.base' cl.txt\n$ grep -c 'source: jrt:/java.xml' cl.txt", out: '1287\n1011\n164' } },
    { callout: { tone: 'violet', title: 'deeper: who gets verified', text: 'The source note says every method is verified on every start. Not quite. HotSpot runs with `-XX:-BytecodeVerificationLocal` (classes from the **boot** loader, i.e. most of the JDK, are trusted) and `-XX:+BytecodeVerificationRemote` (everything else is verified). In our run, `-Xlog:class+init` shows only **8** verifications: our three classes, one lambda class, and four `jdk.localedata` classes (platform loader). In a framework app the cost is real, because almost all of its tens of thousands of classes are library classes. Classes taken from a CDS archive were verified when the archive was dumped.' } },
    { h: 'The cold JIT' },
    { mini: { scene: 'ColdJit' } },
    { tryit: { note: 'One run, counted by tier (the counts vary slightly run to run):', cmd: "$ java -XX:+PrintCompilation -jar hello.jar > pc.txt\n$ awk '$3==\"3\"||$4==\"3\"' pc.txt | wc -l     # C1 with full profiling\n$ awk '$3==\"4\"||$4==\"4\"' pc.txt | wc -l     # C2\n$ grep -c 'app\\.' pc.txt", out: '223\n21\n0' } },
    { p: 'In 80 ms the JIT compiled a couple of hundred JDK methods with C1 and a handful of tiny ones (`String.charAt`, `String.hashCode`, `Object.<init>`) with C2. None of our code got compiled at all. A short-lived process runs almost entirely in the interpreter and C1. That is the third cost, and the one only a cached **profile** (Leyden) or **no JIT at all** (native image) addresses.' },
    { h: 'When it matters' },
    { mini: { scene: 'WhoCares' } },
    { list: ['**Long-running server**: startup is paid once per deploy. Irrelevant next to weeks of uptime.', '**Autoscaling containers**: paid on every scale-out, exactly when traffic is spiking.', '**Serverless functions**: a cold start is billed and felt by the caller.', '**CLI tools**: the user waits for the whole thing, every time.'] },
  ] },
  { ch: 2, blocks: [
    { p: '**Class Data Sharing** takes the result of loading, parsing and verifying classes, writes it to an archive, and on later starts **memory-maps** that archive into metaspace instead of redoing the work.' },
    { mini: { scene: 'CdsIdea' } },
    { tryit: { note: 'Watch the mapping happen (JDK 17, abridged):', cmd: '$ java -XX:SharedArchiveFile=app.jsa -Xlog:cds -jar hello.jar', out: '[0.004s][info][cds] Mapped static  region #0 at base 0x000000d800000000 top 0x000000d800454000 (ReadWrite)\n[0.004s][info][cds] Mapped static  region #1 at base 0x000000d800454000 top 0x000000d800bc0000 (ReadOnly)\n[0.007s][info][cds] Mapped dynamic region #0 at base 0x000000d800bc0000 top 0x000000d800ca0000 (ReadWrite)\n[0.007s][info][cds] Mapped dynamic region #1 at base 0x000000d800ca0000 top 0x000000d800dd4000 (ReadOnly)\n[0.008s][info][cds] Trying to map heap data: region[3] at 0x0000000380700000, size =   475136 bytes' } },
    { callout: { tone: 'violet', title: 'deeper: what is in the archive', text: 'A **static** archive (the JDK\'s `lib/server/classes.jsa`, 13.5 MB here) holds metadata for about 1,200 core classes, split into a **read-write** region (things the JVM updates, like some class state) and a **read-only** region (method bytecodes, constant pools, symbols) that every process maps from the same page-cache pages. A **dynamic** archive (`app.jsa`) is a second layer on top. With G1, the archive also carries **heap objects**: interned strings, the boot module graph and some `Class` mirrors, mapped straight into the Java heap ("Trying to map heap data").' } },
    { h: 'AppCDS: your classes too' },
    { mini: { scene: 'AppCds' } },
    { code: '# 1. training run: archive every class this run loaded\njava -XX:ArchiveClassesAtExit=app.jsa -jar hello.jar\n\n# 2. every later start\njava -XX:SharedArchiveFile=app.jsa -jar hello.jar\n\n# JDK 19+: one step (creates the archive if missing or stale)\njava -XX:+AutoCreateSharedArchive -XX:SharedArchiveFile=app.jsa -jar hello.jar', lang: 'shell', title: 'AppCDS' },
    { table: { head: ['JDK 17 · hello.jar', 'mapped from archive', 'parsed from lib/modules', 'wall clock (median of 50)'], rows: [['`-Xshare:off`', '0', '1,215', '**122 ms**'], ['default CDS archive', '987', '245', '**81 ms**'], ['+ `app.jsa` (2.2 MB)', '1,246', '0', '**75 ms**']] } },
    { p: 'For a tiny app, the JDK\'s default archive delivers most of the gain for free. AppCDS matters in proportion to how many classes **your** app loads beyond that default set: libraries, frameworks, XML, logging. The leftovers in the AppCDS run are `LambdaForm` classes spun up at runtime by `java.lang.invoke`, which the JDK 17 dynamic archive does not store. On 17, `-XX:+AutoCreateSharedArchive` fails with **Unrecognized VM option**: it arrived in JDK 19.' },
    { table: { head: ['JDK', 'CDS milestone'], rows: [['5', 'CDS for JDK classes (client VM)'], ['10', 'AppCDS: application classes (JEP 310)'], ['12', 'default archive shipped and on by default (JEP 341)'], ['13', 'dynamic archiving at exit, `-XX:ArchiveClassesAtExit` (JEP 350)'], ['19', '`-XX:+AutoCreateSharedArchive`'], ['24+', 'Leyden\'s AOT cache builds on the same machinery']] } },
    { h: 'Validation' },
    { mini: { scene: 'CdsCheck' } },
    { tryit: { note: 'Make the archive stale and see what you get (real JDK 17 output):', cmd: '$ touch hello.jar\n$ java -XX:SharedArchiveFile=app.jsa -jar hello.jar\n$ java -XX:SharedArchiveFile=app.jsa -Xshare:on -version', out: '[0.008s][warning][cds,dynamic] Unable to use shared archive. The top archive failed to load: app.jsa\n…the program runs normally, without the archive…\nAn error has occurred while processing the shared archive file.\nshared class paths mismatch (hint: enable -Xlog:class+path=info to diagnose the failure)\nError occurred during initialization of VM' } },
    { callout: { tone: 'pull', title: 'rule', text: 'Generate the archive in the same build step that produces the jar, with the same JDK, and ship them together. In CI, a run with `-Xshare:on` proves the archive is actually usable.' } },
  ] },
  { ch: 3, blocks: [
    { p: '**Project Leyden** shifts work from every start into an earlier **training run**, step by step, while keeping the JVM a JVM: interpreter, JIT and deoptimisation all stay.' },
    { mini: { scene: 'LeydenShift' } },
    { table: { head: ['JEP', 'JDK', 'what it adds'], rows: [['483 · Ahead-of-Time Class Loading & Linking', '24', 'the AOT cache: classes stored already **loaded and linked**, from class path, module path and the JDK'], ['514 · Ahead-of-Time Command-Line Ergonomics', '25', 'one-step `-XX:AOTCacheOutput`, plus `JDK_AOT_VM_OPTIONS` for the creation step'], ['515 · Ahead-of-Time Method Profiling', '25', 'method **profiles** from training, so the JIT starts compiling hot code at once'], ['516 · Ahead-of-Time Object Caching with Any GC', '26', 'cached heap objects can be **streamed**, so the cache works with ZGC too']] } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note says JDK 26 makes AOT caching work "with any collector (previously G1-only)". JEP 483 itself lists only **ZGC** as unsupported, and allows training and production runs to use different collectors. JEP 516 removes the ZGC limitation by adding a GC-agnostic, streamed object format alongside the mapped one.' } },
    { h: 'The workflow' },
    { mini: { scene: 'LeydenWorkflow' } },
    { code: '# JDK 24+ (JEP 483): record, create, run\njava -XX:AOTMode=record -XX:AOTConfiguration=app.aotconf -cp app.jar com.example.App\njava -XX:AOTMode=create -XX:AOTConfiguration=app.aotconf -XX:AOTCache=app.aot -cp app.jar\njava -XX:AOTCache=app.aot -cp app.jar com.example.App\n\n# JDK 25+ (JEP 514): training run and creation in one command\njava -XX:AOTCacheOutput=app.aot -cp app.jar com.example.App', lang: 'shell', title: 'documented commands (not runnable on JDK 17)' },
    { table: { head: ['documented result', 'before', 'with cache', 'cache'], rows: [['HelloStream (JEP 483)', '0.031 s', '0.018 s (−42%)', '11.4 MB'], ['Spring PetClinic 3.2.0, ~21,000 classes (JEP 483)', '4.486 s', '2.604 s (−42%)', '130 MB'], ['HelloStreamWarmup with profiles (JEP 515)', '90 ms', '73 ms (−19%)', '+250 KB']] } },
    { list: ['All runs: the **same JDK release, OS and CPU architecture**.', 'The class path must contain **only JAR files** (no directories), and module options must match.', 'The training run must resemble production: the cache only helps with what training actually did.', 'Under the hood the AOT options are macros over the existing CDS machinery (`-XX:SharedArchiveFile` and friends).'] },
    { callout: { tone: 'violet', title: 'deeper: what "linked" buys you', text: 'With plain CDS, an archived class still has to be **loaded** into its class loader (made visible, registered, given a mirror) and **linked** at runtime. The AOT cache records that state, so in production the classes simply appear already loaded and linked when the JVM starts. The HotSpot implementation also pre-resolves some constant-pool entries and pre-generates `invokedynamic` linkage for lambdas; treat those as implementation details that grow from release to release.' } },
    { h: 'Profiles, and why the JIT stays' },
    { mini: { scene: 'Profiles' } },
    { p: 'A cached profile is a **head start**, not a contract. The production run keeps profiling; if it behaves differently from training, C2\'s speculation fails, the code is deoptimised, and the JVM learns from the real workload (8.8). Peak performance is unchanged because it is the same C2.' },
  ] },
  { ch: 4, blocks: [
    { p: '`jlink` builds a custom runtime image containing only the modules you name plus their transitive `requires`. `jdeps` tells you which modules a jar needs.' },
    { mini: { scene: 'Jdeps' } },
    { tryit: { note: 'Real JDK 17 output:', cmd: '$ java --list-modules | wc -l\n$ jdeps --print-module-deps hello.jar\n$ jdeps hello.jar | head -4', out: '      70\njava.base,java.logging,java.xml\nhello\n [file:///…/hello.jar]\n   requires mandated java.base (@17.0.17)\n   requires java.logging (@17.0.17)' } },
    { h: 'Building the runtime' },
    { mini: { scene: 'Jlink' } },
    { code: '# JDK 17 syntax\njlink --module-path hello.jar --add-modules hello \\\n      --strip-debug --no-header-files --no-man-pages \\\n      --compress=2 --output rt\n\nrt/bin/java -m hello/app.Main\n\n# JDK 21+ spells compression --compress=zip-6 (JDK 17: "Invalid compression level zip-6")', lang: 'shell', title: 'jlink' },
    { table: { head: ['image (macOS arm64, JDK 17)', 'size'], rows: [['full JDK (includes 70 MB of `jmods`)', '**305 MB**'], ['runtime with all 70 modules', '154 MB'], ['3 modules, plain jlink', '52 MB'], ['3 modules, stripped + `--compress=2`', '**28 MB** (libjvm 14, `lib/modules` 12)'], ['same + `--generate-cds-archive`', '50 MB']] } },
    { callout: { tone: 'pull', title: 'measured surprise', text: 'A trimmed runtime has **no CDS archive** unless you ask for one, so it starts slower than the full JDK: **110 ms** vs **81 ms** for `hello.jar`. `--generate-cds-archive` (a jlink plugin since JDK 17) adds 22 MB and brings it back to **75 ms**.' } },
    { h: 'Where jlink bites' },
    { mini: { scene: 'JlinkTraps' } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note says jlink needs dependencies to be "modular or at least automatic modules". Automatic modules are **not** accepted: `Error: automatic module cannot be used with jlink: util from file:///…/util-1.0.jar` (real JDK 17 output). The common pattern is to jlink only the JDK modules your jars need and keep the jars on the class path.' } },
    { code: 'jdeps --print-module-deps --ignore-missing-deps -cp "lib/*" app.jar   # → e.g. java.base,java.sql\njlink --add-modules java.base,java.sql --output rt\nrt/bin/java -cp "app.jar:lib/*" com.example.Main', lang: 'shell', title: 'the usual pattern' },
    { p: '`jdeps` only sees static references. Modules reached through **services** (`ServiceLoader`) or reflection are invisible to it. Our run loaded classes from `jdk.localedata` (non-English locale data) without any reference in our code; `jdk.crypto.ec`, `jdk.charsets` and `jdk.zipfs` are other usual suspects. Test the trimmed runtime itself and add such modules explicitly.' },
  ] },
  { ch: 5, blocks: [
    { mini: { scene: 'Jpackage' } },
    { tryit: { note: 'Real run on macOS, JDK 17:', cmd: '$ jpackage --name Hello --input input --main-jar hello.jar --main-class app.Main \\\n           --type app-image --dest out\n$ du -sh out/Hello.app\n$ jpackage --name Hello --input input --main-jar hello.jar --main-class app.Main \\\n           --type dmg --add-modules java.base,java.logging,java.xml \\\n           --jlink-options "--strip-debug --no-header-files --no-man-pages --compress=2" --dest dmg\n$ ls -l dmg', out: '125M\tout/Hello.app\n-rw-r--r--  1 basha  wheel  18829607  5 Oct 12:19 Hello-1.0.dmg' } },
    { list: ['Output types: `app-image` everywhere; `dmg`/`pkg` on macOS, `msi`/`exe` on Windows, `deb`/`rpm` on Linux.', 'It builds only for the OS it runs on: one CI job per platform.', 'Left to defaults it links a large runtime (125 MB here). Name your modules (`--add-modules`) or pass a jlink image (`--runtime-image`): 29 MB here.', 'Signing and notarisation options exist for macOS; Windows installers need the WiX toolset.', 'It changes how you ship, not how fast the JVM starts.'] },
  ] },
  { ch: 6, blocks: [
    { p: '**GraalVM native image** compiles the application, the parts of the JDK it uses, and a small runtime (**Substrate VM**) into one executable, ahead of time. Nothing on this page about native image was measured: `native-image` is not installed on the machine used for this topic.' },
    { mini: { scene: 'NativeIdea' } },
    { h: 'The closed world' },
    { mini: { scene: 'PointsTo' } },
    { p: 'The **points-to analysis** starts from `main` and iterates to a fixed point: which methods can be called, which types can flow into each variable and field, which fields are read. Only what it proves reachable is compiled. Calls it can see through, like `Class.forName("app.Polite")` with a **constant** argument, or `Main.class.getResourceAsStream("/greeting.xml")` with a literal name, are folded and registered automatically. A name computed at run time (our system property) cannot be.' },
    { h: 'What breaks, and the fix' },
    { mini: { scene: 'WhatBreaks' } },
    { code: '{\n  "reflection": [\n    { "type": "app.Polite",\n      "methods": [ { "name": "<init>", "parameterTypes": [] } ] }\n  ],\n  "resources": [ { "glob": "templates/**" } ]\n}', lang: 'plain', title: 'META-INF/native-image/<groupId>/<artifactId>/reachability-metadata.json' },
    { code: '# run on the JVM; the agent writes what reflection, resources, proxies… were used\njava -agentlib:native-image-agent=config-output-dir=cfg -jar hello.jar', lang: 'shell', title: 'the tracing agent' },
    { callout: { tone: 'violet', title: 'deeper: which exception?', text: 'The source note says the binary fails with `ClassNotFoundException`. That was the classic behaviour. Current GraalVM documentation says a reflective lookup without metadata throws `MissingReflectionRegistrationError` (an `Error`), which names the missing registration; `--exact-reachability-metadata` makes such problems surface early. Either way it fails **at run time**, not at build time.' } },
    { list: ['Spring Boot 3 (AOT processing), Quarkus and Micronaut generate metadata during the build.', 'The **GraalVM Reachability Metadata Repository** supplies metadata for many popular libraries.', 'Old libraries doing undeclared reflection, proxies or serialization are where native builds hurt.'] },
    { h: 'Build-time initialisation' },
    { mini: { scene: 'BuildInit' } },
    { p: 'Static initialisers that run during the build leave their objects in the **image heap**, which is mapped at startup: zero initialisation work at run time. The danger is capturing build-machine state (time, random seeds, environment, host names, open files). Since GraalVM 19, application classes are initialised at **run time** by default; `--initialize-at-build-time=<class or package>` opts in.' },
    { h: 'The bill' },
    { mini: { scene: 'NativeCosts' } },
    { table: { head: ['', 'JVM', 'native image (typical reports)'], rows: [['startup', 'hundreds of ms to seconds', 'a few to tens of ms'], ['memory', 'larger (JIT, metadata, profiles)', 'often several times smaller'], ['peak throughput', 'higher: C2 with live profiles', 'usually lower; PGO (Oracle GraalVM) recovers much'], ['build', 'seconds', 'minutes and several GB of RAM'], ['GC', 'all HotSpot collectors', 'Serial (Community); G1 in Oracle GraalVM on Linux'], ['tooling', 'JFR, jcmd, agents, JMX', 'a different, smaller set']] } },
    { callout: { tone: 'pull', title: 'status in 2025–26', text: 'The source note calls G1 and PGO features of "paid" Oracle GraalVM. Since 2023 Oracle GraalVM has been free to use under the GraalVM Free Terms and Conditions; G1 and PGO are still Oracle GraalVM, not Community Edition. In September 2025 Oracle said GraalVM for JDK 24 was the last release included in its Java SE products and that JVM startup/AOT work continues in OpenJDK\'s Project Leyden. Native image itself continues in GraalVM 25.' } },
  ] },
  { ch: 7, blocks: [
    { mini: { scene: 'AllTogether' } },
    { table: { head: ['technique', 'what it skips', 'hello.jar, JDK 17'], rows: [['default CDS', 'parsing + verifying JDK classes', '122 → 81 ms'], ['AppCDS', 'parsing + verifying your classes too', '→ 75 ms'], ['jlink', 'nothing (it saves disk, not time)', '110 ms without an archive'], ['jlink + CDS', 'as CDS, in a 50 MB runtime', '75 ms'], ['AOT cache (JDK 24+)', '+ loading, linking, (25) profiling', 'documented: −42% on PetClinic'], ['native image', 'the whole JVM', 'documented: milliseconds']] } },
    { mini: { scene: 'Decide' } },
    { table: { head: ['workload', 'use'], rows: [['long-running server', '**plain JVM**: startup is amortised; you want peak JIT throughput'], ['frequent deploys or restarts', 'JVM + **AppCDS**, or the **AOT cache** on JDK 24+'], ['container image size matters', '+ **jlink** (with `--generate-cds-archive`)'], ['scales out constantly', 'native image **or** JVM + AOT cache: measure both'], ['serverless function, CLI tool', '**native image**'], ['desktop application', '**jpackage**']] } },
    { callout: { tone: 'pull', title: 'the honest default', text: 'For a normal server: plain JVM, plus the AOT cache once you are on JDK 24+. It is a flag, not an architecture change. Native image is a commitment (a different build, minutes-long builds, metadata, different tooling): take it when cold start is the actual product requirement.' } },
  ] },
];

const traps = [
  '**AOT is not "no JIT".** Leyden\'s AOT cache keeps the interpreter, C1, C2 and deoptimisation. Only native image removes the JIT.',
  '**Native image is not strictly better.** Lower peak throughput (without PGO), minutes-long builds, reflection metadata, a different toolset. Wrong for most long-running servers.',
  '**jlink does not accept automatic modules.** jlink the JDK modules from `jdeps`, keep your jars on the class path.',
  '**A stale CDS archive is silently ignored.** Rebuilding the jar invalidates it; the JVM prints one warning and runs slower. `-Xshare:on` makes it fatal.',
  '**A trimmed runtime can start slower.** A jlink image has no CDS archive unless you add `--generate-cds-archive` (110 vs 75 ms here).',
  '**A benchmark on a fresh JVM measures startup and the interpreter**, not your steady-state code (8.8).',
  '**Optimising startup for a service that runs for weeks** buys nothing. Optimise throughput instead.',
];

const recap = [
  '**Why startup is slow**: class loading (1,287 classes for a 3-class app), verification of non-JDK classes, and an interpreter with no profile.',
  '**CDS**: dump parsed, verified classes once and `mmap` them; read-only pages are shared between JVMs. On by default for JDK classes since JDK 12.',
  '**AppCDS**: `-XX:ArchiveClassesAtExit` then `-XX:SharedArchiveFile` (JDK 19+: `-XX:+AutoCreateSharedArchive`). 122 → 81 → 75 ms here.',
  '**Leyden AOT cache**: JDK 24 (JEP 483) loaded + linked classes; JDK 25 (JEP 514, 515) one-step creation and profiles; JDK 26 (JEP 516) any GC. Keeps the JIT.',
  '**jlink**: only the modules you need, 305 MB → 28 MB; explicit modules only; add a CDS archive back. **jpackage**: native installers, per OS.',
  '**Native image**: closed-world points-to analysis, build-time init into an image heap, AOT machine code, no JIT. Milliseconds to start; metadata, build time and peak throughput are the bill.',
  '**Default**: plain JVM + AOT cache. Native image when cold start is the requirement.',
];

const quiz = [
  { q: 'Running `hello.jar` with `-Xlog:class+init`, only 8 of about 1,280 loaded classes are verified. Why?', options: ['Verification is lazy and most classes never run', 'Classes from the boot loader (most of the JDK) are trusted and skip verification; app and library classes are verified', 'The default CDS archive disables verification for everything', 'Verification only happens for classes with a static initialiser'], answer: 1, why: 'HotSpot defaults to `-XX:-BytecodeVerificationLocal` (boot classes trusted) and `-XX:+BytecodeVerificationRemote` (everything else verified). The 8 were our 3 classes, a lambda class and 4 `jdk.localedata` classes loaded by the platform loader.' },
  { q: 'What does CDS actually save at startup?', options: ['JIT compilation of hot methods', 'Reading, parsing and verifying classes: the archive is memory-mapped straight into metaspace', 'Garbage collection during startup', 'Running static initialisers'], answer: 1, why: 'The archive holds already-parsed, already-verified class metadata. Mapping it replaces per-class parsing; the read-only pages can even be shared by several JVMs. It does not compile code or run `<clinit>`.' },
  { q: 'You rebuild `hello.jar` but keep the old `app.jsa`. What happens on the next start with `-XX:SharedArchiveFile=app.jsa`?', options: ['The JVM refuses to start', 'It maps the stale archive and may run old code', 'It prints a warning, ignores the archive and runs without it, slower', 'It regenerates the archive automatically'], answer: 2, why: 'The archive records each jar\'s size and modification time. On a mismatch the JVM warns ("Unable to use shared archive") and carries on. Only with `-Xshare:on` does it become a fatal error; only `-XX:+AutoCreateSharedArchive` (JDK 19+) regenerates.' },
  { q: 'Which startup cost does JEP 515 (AOT method profiling, JDK 25) address that CDS and JEP 483 do not?', options: ['Parsing class files', 'Verifying bytecode', 'The JIT starting with an empty profile', 'The size of the runtime image'], answer: 2, why: 'CDS removes parsing/verification, JEP 483 removes loading/linking. JEP 515 stores profiles from the training run so the JIT can compile hot methods immediately instead of profiling from zero.' },
  { q: 'A team says "we use Leyden\'s AOT cache, so we lost C2\'s peak performance". Is that right?', options: ['Yes, AOT code replaces the JIT', 'Yes, but only with ZGC', 'No: the JVM still interprets, profiles, JIT-compiles and deoptimises; the cache is a head start', 'No, because the AOT cache disables C1 instead'], answer: 2, why: 'Leyden keeps the whole JIT pipeline. Only GraalVM native image gives up the JIT and its profile-driven speculation.' },
  { q: 'A jlink image with just `java.base,java.logging,java.xml` starts in 110 ms while the full JDK takes 81 ms. Why is the smaller runtime slower?', options: ['Compression makes class loading slower', 'It lacks a CDS archive, so every class is parsed again', 'It runs without the C2 compiler', 'Fewer modules means a longer module-resolution step'], answer: 1, why: 'The full JDK ships `lib/server/classes.jsa`; a fresh jlink image has none. `--generate-cds-archive` puts one back (75 ms here, at +22 MB).' },
  { q: 'Why does `jlink` reject your build when one dependency is a plain jar on the module path?', options: ['jlink only accepts signed jars', 'The jar becomes an automatic module, and jlink only links explicit modules', 'Plain jars must be compressed first', 'jlink requires every jar to contain native code'], answer: 1, why: 'Automatic modules have no declared dependencies, so jlink cannot compute a closed module graph and refuses them. The usual fix is to jlink only the JDK modules and put your jars on the class path.' },
  { q: 'In the native image of our app, `Class.forName(System.getProperty("greeter", "app.Polite"))` fails at run time. What is the root cause?', options: ['Native image does not support reflection at all', 'The closed-world analysis cannot see a name computed at run time, so `app.Polite` was never registered or compiled in', 'System properties are unavailable in native executables', 'The class was initialised at build time and then discarded'], answer: 1, why: 'Reflection works when declared. A constant `Class.forName("app.Polite")` would be folded automatically; a computed name needs reachability metadata (or the tracing agent to generate it).' },
  { q: 'A class has `static final long BUILT_AT = System.currentTimeMillis();` and is initialised at build time in a native image. What value does production see?', options: ['The current time at each start', 'The time the binary was built, in every copy', 'Zero, because build-time fields are reset', 'A compile error from native-image'], answer: 1, why: 'Build-time initialisation snapshots the objects and values into the image heap. That is why application classes initialise at run time by default.' },
  { q: 'Your service runs for three weeks between deploys and needs maximum throughput. Best choice?', options: ['GraalVM native image', 'Plain JVM (optionally with the AOT cache for faster deploys)', 'jpackage', 'A jlink image without CDS'], answer: 1, why: 'Startup is amortised over weeks; what matters is peak throughput, where C2 with live profiles usually beats native image.' },
];

window.AN.registerTopic({
  id: '8.10', part: '08', title: 'Startup, packaging and AOT', kicker: 'Part 08 · The JVM',
  lede: 'Why a three-class program loads 1,287 classes before it prints a line, and what CDS, Leyden\'s AOT cache, jlink, jpackage and GraalVM native image each do about it, measured where possible.',
  chapters, scenes, captions, notes, traps, recap, quiz,
});
