// Topic 8.7 — References and reachability. Source notes: Part-08-The-JVM/8.7-references-and-reachability.md
// Every console line, GC log line and javap listing is real JDK 17 output (OpenJDK 17.0.17, G1, macOS),
// from small programs compiled and run for this topic. -Xlog:gc decorations ([0.039s][info][gc]) are trimmed.
import { SIntro, SReachability, SFourStrengths, SStrengthTable, SStrongestPath, SSoftPolicy, SWeakOldGen } from './8.7/scenes1.jsx';
import { SRefQueue, SWeakMapVanish, SWeakMapTraps, SFinalize, SFinalizeProblems, SCleanerVsTwr, SCleanerTrap } from './8.7/scenes2.jsx';
import { SLeakStatic, SLeakListeners, SLeakThreadLocal, SLeakInner, SLeakResources, SLeakMutatedKey, SLeakCache } from './8.7/scenes3.jsx';
import { SSystemGc, STraps, SRecap } from './8.7/scenes4.jsx';

const chapters = ['Intro', 'Reachability', 'Four strengths', 'Soft vs weak', 'ReferenceQueue', 'WeakHashMap', 'finalize()', 'Cleaner', 'Leak shapes', 'System.gc()', 'Traps', 'Recap'];

const scenes = [
  { name: 'Intro', dur: 24, ch: 0, title: '', C: SIntro },
  { name: 'Reachability', dur: 60, ch: 1, title: 'Alive means reachable', C: SReachability },
  { name: 'FourStrengths', dur: 72, ch: 2, title: 'Four strengths, one GC cycle', C: SFourStrengths },
  { name: 'StrengthTable', dur: 34, ch: 2, title: 'The four strengths side by side', C: SStrengthTable },
  { name: 'StrongestPath', dur: 46, ch: 3, title: 'The strongest path decides', C: SStrongestPath },
  { name: 'SoftPolicy', dur: 54, ch: 3, title: 'When is memory “short”?', C: SSoftPolicy },
  { name: 'WeakOldGen', dur: 40, ch: 3, title: '“The next GC” is not always next', C: SWeakOldGen },
  { name: 'RefQueue', dur: 64, ch: 4, title: 'How a Reference reaches your queue', C: SRefQueue },
  { name: 'WeakMapVanish', dur: 58, ch: 5, title: 'WeakHashMap: how an entry disappears', C: SWeakMapVanish },
  { name: 'WeakMapTraps', dur: 48, ch: 5, title: 'Three WeakHashMap surprises', C: SWeakMapTraps },
  { name: 'Finalize', dur: 60, ch: 6, title: 'finalize() brings an object back', C: SFinalize },
  { name: 'FinalizeProblems', dur: 40, ch: 6, title: 'Why finalize() was a mistake', C: SFinalizeProblems },
  { name: 'CleanerVsTwr', dur: 60, ch: 7, title: 'Cleaner vs try-with-resources', C: SCleanerVsTwr },
  { name: 'CleanerTrap', dur: 46, ch: 7, title: 'The one Cleaner rule', C: SCleanerTrap },
  { name: 'LeakStatic', dur: 50, ch: 8, title: 'Static collections', C: SLeakStatic },
  { name: 'LeakListeners', dur: 40, ch: 8, title: 'Listeners never removed', C: SLeakListeners },
  { name: 'LeakThreadLocal', dur: 62, ch: 8, title: 'ThreadLocal in a thread pool', C: SLeakThreadLocal },
  { name: 'LeakInner', dur: 40, ch: 8, title: 'Inner classes hold their outer object', C: SLeakInner },
  { name: 'LeakResources', dur: 38, ch: 8, title: 'Resources never closed', C: SLeakResources },
  { name: 'LeakMutatedKey', dur: 42, ch: 8, title: 'Keys mutated inside a map', C: SLeakMutatedKey },
  { name: 'LeakCache', dur: 46, ch: 8, title: 'Caches with no eviction', C: SLeakCache },
  { name: 'SystemGc', dur: 54, ch: 9, title: 'Why you never call System.gc()', C: SSystemGc },
  { name: 'Traps', dur: 37, ch: 10, title: 'Traps', C: STraps },
  { name: 'Recap', dur: 36, ch: 11, title: 'Recap', C: SRecap },
];

const captions = {
  Intro: [[0.8, 'An object lives as long as something can reach it. Nothing else matters to the collector.'], [6, 'Java lets you hold an object **loosely**: soft, weak and phantom references, each weaker than the last.'], [12.5, 'And when something holds an object too tightly by accident, that is a memory leak.'], [18, 'One running example all the way: an image viewer and its cache of pictures.']],
  Reachability: [[0.5, 'First, a reminder from 8.5: the collector starts from **GC roots**: thread stacks, static fields, JNI handles.'], [7, 'It follows every reference it finds, marking each object it reaches.'], [13, "Whatever it never reaches is garbage, cycles included. Two objects pointing at each other don't save each other."], [20, 'So a Java object dies when nothing reachable points at it. There is no "delete", and no reference count.'], [27, 'A `WeakReference` is itself an ordinary object. Here a local variable holds it strongly.'], [33, 'Inside it, `javap` shows four fields. One of them, `referent`, is special.'], [39, 'When marking reaches a Reference object, it does **not** follow `referent`. It notes the Reference, and decides later.'], [47, 'That gives five levels of reachability, from strongly reachable down to unreachable.'], [53, "The strongest path to an object decides its level. Now let's meet the four strengths."]],
  FourStrengths: [[0.5, 'Four images, each held a different way. `a` is an ordinary local variable: a strong reference.'], [7, '`b` is held through a `SoftReference`, `c` through a `WeakReference`, `d` through a `PhantomReference`.'], [13.5, 'All three register a `ReferenceQueue`. And `d.get()` already returns null: a phantom never gives the object back.'], [19, 'Now `System.gc()`. The weak referent `c` is cleared at once: nothing strong or soft holds it.'], [25.5, 'The phantom referent `d` is collected too, and both Reference objects land on the queue.'], [32, '`b` survives: a soft referent is kept while there is room. And `a` is untouchable.'], [38, 'Now apply memory pressure: allocate 1 MB blocks until the heap is nearly full.'], [45, 'G1 tries young GCs, then full GCs that still keep soft referents. 61M stays 61M.'], [51.5, 'Only a last-ditch full GC clears soft references: 61M down to 59M. `b` is gone, and its reference is queued.'], [59, 'Real JDK 17 output. `a`, the strong one, was never at risk.'], [65, 'And the queue told us exactly **which** references were cleared, without checking each one.']],
  StrengthTable: [[0.5, 'The four strengths side by side.'], [4, 'Strong references keep an object alive. Period.'], [9, 'Soft: kept until memory runs short. The JVM promises to clear all of them before throwing `OutOfMemoryError`.'], [16, 'Weak: cleared at the next GC that notices, whether memory is short or not.'], [22, 'Phantom: `get()` is always null. It only tells you, through the queue, that the object is gone.'], [28, 'Memory pressure matters only to soft references. Weak ones never wait for it.']],
  StrongestPath: [[0.5, 'One image, held all four ways at once. Which references get cleared?'], [6, 'Drop the strong one: `img = null`. The image is now reachable only through Reference objects.'], [12.5, 'Run `System.gc()`. Nothing is cleared, not even the weak reference. Real output.'], [19, 'Why? Reachability is decided by the **strongest** path. A soft path exists, so the image is softly reachable.'], [26, 'Now memory pressure. The soft reference gives way, and in that same GC so does the weak one.'], [32, 'The image is collected, and all three references arrive on the queue together.'], [38, 'The rule: soft and weak references to one object are cleared atomically. Then the phantom is enqueued.']],
  SoftPolicy: [[0.5, 'When is memory "short"? HotSpot uses a clock, not a fill level.'], [5, 'Every `SoftReference` has a `timestamp`, refreshed by each `get()`. A static `clock` advances at every GC.'], [12, 'A soft referent survives if it was used recently: within free heap in MB, times 1000 ms.'], [19.5, 'With 63 MB free, an untouched entry gets about a minute. Shrink the factor, and the same idle entry is cleared.'], [27, 'Real output: idle for 1.5 s. At 1000 ms per MB it survives; at 10 or 0 it is cleared.'], [33, 'Now a cache of 200 soft thumbnails, while the app slowly needs more memory.'], [39, 'All 200 survive, then one full GC clears every entry at once. 200 to zero.'], [46, 'A cache that is full or empty, never in between. Use a bounded cache like Caffeine instead.']],
  WeakOldGen: [[0.5, '"Weak references are cleared at the next GC." Mostly true. Here is the catch.'], [6, 'One object is promoted to the old generation by a full GC. Another is young. Each has a `WeakReference`.'], [13, 'Drop both strong references, then make garbage. G1 runs young GCs: thirteen of them.'], [20, 'Each young GC scans only young regions. The young referent is cleared; the old one is still alive.'], [26.5, 'Only a GC that covers the old region, here a full GC, clears it.'], [33, 'So weak means "at the next GC that examines it". For old objects, that can be minutes away.']],
  RefQueue: [[0.5, 'How does a cleared reference reach your queue? Follow one `WeakReference` through its life.'], [5.5, 'It starts **active**: the referent is set, and the GC examines it at every cycle.'], [11, 'When the GC finds the referent only weakly reachable, it clears it and links the Reference onto a **pending list**.'], [18, 'A high-priority JVM thread, the **Reference Handler**, drains that list and enqueues each Reference on its queue.'], [24.5, 'Your code then sees it with `poll()` or a blocking `remove()`. After that it is inactive: done.'], [31, 'Now use it. Each `Texture` owns a GPU handle. A `PhantomReference` subclass carries a copy of that handle.'], [38, 'A cleanup thread blocks in `remove()`. The GC runs: `sea.png` and `sun.png` are unreachable.'], [44, "`sea.png`'s `TextureRef` is enqueued and the thread frees the handle. `get()` is null: it can't touch the texture."], [51, 'But `sun.png` was never reported. Its `TextureRef` was garbage too: nothing held the Reference object.'], [57, 'Rule: keep your Reference objects strongly reachable, in a set, until they are processed.']],
  WeakMapVanish: [[0.5, 'A `WeakHashMap` keyed by `Page`: each open page gets a thumbnail that should vanish when the page closes.'], [7, 'Inside, every entry **is** a `WeakReference` to its key. The value is an ordinary strong field.'], [13.5, 'The map also owns a private `ReferenceQueue`, and every entry is registered with it.'], [19, "Page 1 closes: `p1 = null`. Now only the entry's weak `referent` points at it."], [24.6, "GC: the key is cleared and collected, and the entry is enqueued on the map's queue."], [31, 'But the entry is still in the table, still holding the thumbnail. Real output: 2 slots in use.'], [38.5, 'The next time you touch the map, `size()`, `get()` or `put()`, it runs `expungeStaleEntries()`.'], [45, 'It drains the queue and unlinks each stale entry. Now the thumbnail is garbage too.'], [51, 'Entries vanish in two steps: the GC clears the key, and the map cleans up later.']],
  WeakMapTraps: [[0.5, 'Three ways a `WeakHashMap` surprises people.'], [4, 'One: the value points back at its key. The map holds values strongly, so the key stays strongly reachable.'], [11.5, 'The entry never clears. Keep values free of their keys, or hold the key weakly inside the value.'], [19, 'Two: string literals as keys. Literals are interned and held by the JVM, so they never go away.'], [26, 'Three: a weak listener registry. A listener registered as an inline lambda has nothing else holding it.'], [33, 'The next GC removes it, though the viewer is alive and open. The listener silently stops firing.'], [40, 'So the owner must hold its listener in a field. And never count on an entry still being there.']],
  Finalize: [[0.5, 'Before references, Java had `finalize()`: a method the GC calls before reclaiming an object.'], [6, 'Because `Zombie` overrides it, the JVM registers each new instance with a hidden `Finalizer` reference, at allocation.'], [13, 'Drop the last strong reference and call `System.gc()`. Reference processing runs in four phases.'], [19, 'Phase 2 clears the `WeakReference`. As far as weak references know, the object is dead.'], [25, 'Phase 3 marks it alive again, with everything it references, and queues it for the **Finalizer** thread.'], [32, 'The Finalizer thread runs `finalize()`, which stores `this` in a static field. The object is back from the dead.'], [39.5, 'Real output: the weak reference was cleared, yet `saved` holds that very same object.'], [46, 'Drop it again and GC: this time it is simply collected. `finalize()` never runs twice.'], [53, "The cost: every finalizable object needs at least two GCs to die, and a thread you don't control."]],
  FinalizeProblems: [[0.5, 'Six problems, all fundamental.'], [3.5, "It may never run, not even at exit. And when it does, you don't know when, or in what order."], [10.5, 'It slows collection. It can resurrect objects. And exceptions thrown inside it are silently ignored.'], [18, "And the finalizer attack: a subclass's `finalize()` can grab a half-built object whose constructor threw."], [25, 'Deprecated in Java 9, deprecated **for removal** in 18. Java 18 also added `--finalization=disabled`.'], [33, "It's still present in Java 25, but treat it as gone. Its replacement, `Cleaner`, is built on phantom references."]],
  CleanerVsTwr: [[0.5, '`Cleaner` is the supported replacement: phantom references plus a thread, packaged up.'], [6, '`register(this, action)` returns a `Cleanable`. The Cleaner holds the action and a phantom reference to the texture.'], [13, 'The action, a static nested record, holds only the handle. It never points back at the texture.'], [19.5, 'Path one: try-with-resources. `close()` calls `clean()` at the end of the block, on your own thread.'], [27, 'Deterministic: the GPU memory comes back exactly when the block ends.'], [32.5, 'Path two: someone forgets `close()`. The texture becomes unreachable, and nothing happens yet.'], [39.5, "Only when a GC notices does the Cleaner's own thread, `Cleaner-0`, run the action. Maybe soon, maybe never."], [47, 'Either way, the action runs at most once. A second `clean()` does nothing.'], [53, 'So try-with-resources is the answer. `Cleaner` is only a safety net, for native memory.']],
  CleanerTrap: [[0.5, 'The one rule of `Cleaner`: the action must not reference the object it cleans.'], [5.5, 'This lambda reads `this.name`, so it captures `this`.'], [11, 'The Cleaner is reachable from its thread, the action from the Cleaner, and the texture from the action.'], [18, 'A strong path exists, so the texture never becomes phantom reachable. Two GCs later: nothing.'], [26, "A leak and a missed cleanup at once. It's the same hidden `this` that inner classes carry."], [32, 'The fix: a static nested class or record that copies just what cleanup needs: the handle.'], [38.5, 'The opposite trap: an object can become unreachable while its own method still runs. `reachabilityFence` prevents that.']],
  LeakStatic: [[0.5, 'A Java leak is unintentional reachability. Leak one, the most common: a static collection that only grows.'], [5, 'A static field is a GC root. Everything the map reaches lives as long as the class: usually forever.'], [12, 'Each request adds a 100 KB session, and nothing ever removes it.'], [18, "Watch the heap: 14M, 17M, 19M after successive GCs. The GC is working; it just can't free anything."], [26, 'Full GCs at 30M free almost nothing. `OutOfMemoryError` at request 292. Real run, 32 MB heap.'], [34, "The fix: remove the entry when the request ends. Or bound the map, or don't make it static."], [41, 'Now each GC drops the heap back to 1M. A sawtooth, not a climb: that is a healthy heap.']],
  LeakListeners: [[0.5, 'Leak two: listeners that are added and never removed.'], [5, 'Each viewer registers a theme listener. The lambda calls `repaint()`, so it captures the viewer.'], [11.5, 'The viewer closes, but the app-wide theme manager still holds the listener, which holds the viewer and its image.'], [19, 'Open and close enough viewers and the heap fills: `OutOfMemoryError` after 296, with 295 still registered.'], [27, 'Fix: unregister in `close()`. A thousand viewers later, zero listeners remain.'], [33.5, 'A weak registry works too, but only if the viewer holds its listener in a field. Remember the vanishing lambda.']],
  LeakThreadLocal: [[0.5, 'Leak three, the nasty one: a `ThreadLocal` in a thread pool.'], [5, "Each `Thread` object owns a map. `CONTEXT.set()` puts an entry into the current thread's map."], [11.5, 'The entry is a weak reference to the `ThreadLocal` key, but its value is held strongly.'], [18, 'Request one, alice, sets her context. The request ends. The context stays, attached to the thread.'], [25, "In a pool the thread is reused, never destroyed. Bob's request overwrites the value, and it stays too."], [31, "Then an anonymous request on the same thread reads bob's context. Real output. That's a data leak."], [38.5, 'And memory: eight idle pool threads keep 4 MB each. After a full GC, 33M is still live.'], [46.5, "The fix is mandatory in pools: `remove()` in a `finally`. Nobody's context leaks, and the full GC frees it all."], [54.5, "On an app server, a value from your webapp's classes pins the whole class loader after a redeploy."]],
  LeakInner: [[0.5, 'Leak four: an inner class instance that outlives its outer object.'], [5, 'A non-static inner class gets a hidden field, `this$0`, pointing at its enclosing instance. `javap -p` shows it.'], [12.5, 'Queue a tiny `Refresh` task in a long-lived scheduler, and it drags the whole closed viewer along.'], [19, 'Real output: `OutOfMemoryError` after 292 viewers, with just 291 tiny tasks queued.'], [26.5, 'Fix: a `static` nested class that copies only what it needs. No `this$0`.'], [32.5, 'A thousand tasks, no problem. Capturing lambdas and anonymous classes hold `this` the same way.']],
  LeakResources: [[0.5, 'Leak five: resources that are opened and never closed.'], [5, 'Every `FileInputStream` holds an OS file descriptor, plus buffers and native memory that a heap gauge never shows.'], [12, 'Here the heap stays nearly empty, so no GC runs, and nothing ever releases the descriptors.'], [18.5, 'Real output, with the limit set to 256: after 253 reads, `Too many open files`.'], [25, 'The fix is try-with-resources: closed at the end of the block, every time. 5,000 reads, no problem.'], [31.5, "The JDK's own cleaner would close them after some GC, eventually. Never rely on that."]],
  LeakMutatedKey: [[0.5, "Leak six isn't quite a leak, but it looks like one: a key mutated while inside a `HashMap`."], [6, '`ImageKey` uses `width` in `hashCode()`. Put it in the map, and its hash picks bucket 11.'], [12.5, "Now set `width` to 200. The entry doesn't move. It sits in the bucket for the old hash."], [18.5, "`get(key)` computes the new hash, looks in bucket 7, and finds nothing. Even a fresh key with width 100 can't match."], [26, 'Yet `size()` is still 1. Put again, and the map holds two entries, one unreachable by any lookup.'], [33.5, 'The table still references it, so the GC keeps it. The fix: immutable keys, like a record.']],
  LeakCache: [[0.5, 'Leak seven: a cache with no eviction. Every distinct image URL adds an entry, forever.'], [6, 'It looks like a cache but behaves like a static collection. Real output: `OutOfMemoryError` at image 289.'], [13.5, 'A cache needs a bound and an eviction policy. The simplest: a `LinkedHashMap` in access order.'], [20, 'Each `get` moves an entry to the tail. After each `put`, `removeEldestEntry` can drop the head: the least recently used.'], [28, 'With a bound of 100, two thousand distinct images later the cache holds exactly 100.'], [35, 'In production, use Caffeine: size or weight bounds, expiry, statistics, and good concurrency.'], [40.5, 'Seven shapes, one cause: something reachable that you forgot about.']],
  SystemGc: [[0.5, 'Last: `System.gc()`. Here is what it actually does, from a real G1 log.'], [6, 'A busy program: eight young pauses. After warm-up, they take a third of a millisecond.'], [12.5, 'Then `System.gc()`: a **full**, stop-the-world collection of the whole heap. 19 ms here, far more on big heaps.'], [20, 'It also threw away what G1 had learned: the heap it had grown to 283 MB was shrunk to 144 MB.'], [27, "And it's only a hint. With `-XX:+DisableExplicitGC`, the same call does nothing at all."], [33.5, "It can't fix a leak: leaked objects are reachable by definition. The full GCs in leak one freed almost nothing."], [41, 'If `System.gc()` seems to help, you have a leak or a sizing problem. Fix that instead.'], [47, 'Legitimate uses: tests and benchmark setup, like the demos in this video. Never production code.']],
  Traps: [[0.5, 'Six traps.'], [3, 'Soft references make a poor cache: full or empty.'], [8.5, 'In a `WeakHashMap` only the keys are weak.'], [14, '"Next GC" means the next GC that covers the referent.'], [19.5, '`Cleaner` is a backstop, and its action must not capture `this`.'], [25, 'Pooled threads keep `ThreadLocal` values until you `remove()` them.'], [30.5, 'And `System.gc()` never helps. If it seems to, look for the leak.']],
  Recap: [[0.5, 'Recap.'], [3, 'Alive means reachable from a root, and the strongest path decides how.'], [8, 'Soft references go when memory is short; weak ones at the next GC that sees them.'], [13, 'Phantoms report collection through a queue. Keep the Reference itself reachable.'], [18, '`WeakHashMap`: weak keys, strong values, lazy cleanup.'], [23, 'try-with-resources first, `Cleaner` as a backstop, `finalize()` never.'], [28, 'And learn the seven leak shapes by sight. They are most of what you will meet.']],
};

const STRENGTHS_SRC = `import java.lang.ref.*;
import java.util.*;

public class Strengths {
    record Image(String name, byte[] px) {
        Image(String name) { this(name, new byte[1 << 20]); }   // 1 MB of pixels
        public String toString() { return name; }
    }
    static String show(Reference<?> r) { return r.refersTo(null) ? "cleared" : "alive"; }

    public static void main(String[] args) throws Exception {
        var queue = new ReferenceQueue<Image>();
        Image a = new Image("a.png");                                   // strong
        var b = new SoftReference<>(new Image("b.png"), queue);
        var c = new WeakReference<>(new Image("c.png"), queue);
        var d = new PhantomReference<>(new Image("d.png"), queue);
        Map<Reference<?>, String> names = Map.of(b, "soft b", c, "weak c", d, "phantom d");

        System.out.println("phantom.get() = " + d.get());
        System.gc();
        Thread.sleep(100);
        System.out.println("after GC  : a=" + a + "  b=" + show(b) + "  c=" + show(c) + "  d=" + show(d));
        for (Reference<?> r; (r = queue.poll()) != null; ) System.out.println("  queue.poll() -> " + names.get(r));

        List<byte[]> hog = new ArrayList<>();            // memory pressure
        int mb = 0;
        while (!b.refersTo(null)) { hog.add(new byte[1 << 20]); mb++; }
        System.out.println("pressure  : soft b cleared after allocating " + mb + " MB");
        hog = null;
        Thread.sleep(100);
        for (Reference<?> r; (r = queue.poll()) != null; ) System.out.println("  queue.poll() -> " + names.get(r));
        System.out.println("a is still " + a + " (strong: never collected while reachable)");
    }
}`;

const TEXTURE_SRC = `public class Texture implements AutoCloseable {
    private static final Cleaner CLEANER = Cleaner.create();
    private final Cleaner.Cleanable cleanable;

    public Texture(String name) {
        long handle = allocGpu(name);
        // the action must NOT reference this, or the Texture is never collected
        this.cleanable = CLEANER.register(this, new Free(handle));
    }

    // a record nested in a class is implicitly static: no hidden outer reference
    private record Free(long handle) implements Runnable {
        public void run() { freeGpu(handle); }
    }

    @Override public void close() { cleanable.clean(); }   // runs the action at most once
}`;

const notes = [
  { ch: 1, blocks: [
    { p: '**A Java object is alive exactly as long as it is reachable**: there is a chain of ordinary references to it from a **GC root**. Roots are the references the collector can find without looking in the heap: local variables and operands in every thread\'s stack frames, static fields of loaded classes, JNI handles, and a few JVM-internal ones (8.5 covers marking in detail). Anything not reached is garbage, including cycles: two objects pointing at each other keep nothing alive.' },
    { mini: { scene: 'Reachability' } },
    { p: 'A `java.lang.ref.Reference` (soft, weak, phantom) is an ordinary heap object that you hold strongly. What makes it special is one field, **`referent`**: the GC does not trace through it during marking. It records the Reference on a *discovered* list and decides at the end of marking, by reference type, whether to clear it.' },
    { tryit: { note: 'The fields the GC works with, straight from the JDK:', cmd: '$ javap -p java.lang.ref.Reference', out: 'public abstract class java.lang.ref.Reference<T> {\n  private T referent;\n  volatile java.lang.ref.ReferenceQueue<? super T> queue;\n  volatile java.lang.ref.Reference next;\n  private transient java.lang.ref.Reference<?> discovered;\n  ...\n  private static native java.lang.ref.Reference<?> getAndClearReferencePendingList();\n  public final boolean refersTo(T);\n  public static void reachabilityFence(java.lang.Object);' } },
    { table: { head: ['level', 'meaning'], rows: [['strongly reachable', 'a chain of ordinary references from a root'], ['softly reachable', 'not strongly; reachable through a `SoftReference`'], ['weakly reachable', 'not strongly or softly; reachable through a `WeakReference`'], ['phantom reachable', 'finalized (if needed), reachable only through a `PhantomReference`'], ['unreachable', 'reclaimable']] } },
    { callout: { tone: 'violet', title: 'deeper: reference processing in HotSpot', text: 'After marking, HotSpot processes discovered references in four phases. With `-Xlog:gc+phases+ref=debug` (JDK 17) they are logged as: **Reconsider SoftReferences** (apply the soft policy), **Notify Soft/WeakReferences** (clear the dead ones), **Notify and keep alive finalizable** (resurrect objects that still need `finalize()`), **Notify PhantomReferences**. Cleared References are linked through `discovered` into the VM\'s pending list, which the Java-side Reference Handler thread drains.' } },
  ] },
  { ch: 2, blocks: [
    { p: 'The running example: an image viewer holding `Image`s of 1 MB each. Four images, held four ways, then one `System.gc()` and one memory-pressure episode:' },
    { code: STRENGTHS_SRC, title: 'Strengths.java (JDK 16+ for refersTo)' },
    { mini: { scene: 'FourStrengths' } },
    { tryit: { note: 'Real output (JDK 17, G1). The full log has ~20 GC lines during the pressure phase; the relevant ones are kept and decorations trimmed.', cmd: '$ java -Xmx64m -Xlog:gc Strengths', out: 'phantom.get() = null\nGC(0) Pause Full (System.gc()) 9M->5M(24M) 1.757ms\nafter GC  : a=a.png  b=alive  c=cleared  d=cleared\n  queue.poll() -> weak c\n  queue.poll() -> phantom d\n...\nGC(13) Pause Full (G1 Compaction Pause) 59M->59M(64M) 1.194ms\nGC(17) Pause Full (G1 Compaction Pause) 61M->61M(64M) 1.222ms\nGC(18) Pause Full (G1 Compaction Pause) 61M->59M(64M) 0.937ms\npressure  : soft b cleared after allocating 29 MB\n  queue.poll() -> soft b\na is still a.png (strong: never collected while reachable)' } },
    { p: 'Notice GC(17) and GC(18): G1 first runs a full GC that **keeps** soft referents; only when that frees nothing does it run a last-ditch full GC that clears all soft references. That is the spec\'s guarantee in action: every soft reference is cleared before an `OutOfMemoryError`.' },
    { mini: { scene: 'StrengthTable' } },
    { table: { head: ['strength', 'referent cleared…', '`get()`', 'use for'], rows: [['**strong**', 'never, while strongly reachable', 'n/a', 'everything normal'], ['**soft**', 'when the GC decides memory is short; all before an OOM', 'object or null', 'memory-sensitive caches (badly: see next chapter)'], ['**weak**', 'at the next GC that finds it only weakly reachable', 'object or null', 'canonicalising maps, metadata, listener registries'], ['**phantom**', 'after collection: enqueued (and cleared automatically since Java 9)', '**always null**', 'post-mortem cleanup; the basis of `Cleaner`']] } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note says the collector clears them "strong > soft > weak > phantom… in that order when it needs memory". The ordering of **strength** is right, but clearing is not driven by need except for soft references. A weak reference is cleared by any GC that finds its referent only weakly reachable, even with gigabytes free.' } },
  ] },
  { ch: 3, blocks: [
    { h: 'The strongest path decides' },
    { mini: { scene: 'StrongestPath' } },
    { tryit: { note: 'One `Image` with a soft, a weak and a phantom reference, and no strong one:', cmd: '$ java -Xmx64m SameObject', out: 'after System.gc(): soft=alive weak=alive phantom=alive\n  queue.poll() -> null\nafter pressure:    soft=cleared weak=cleared phantom=cleared\n  queue.poll() -> soft\n  queue.poll() -> weak\n  queue.poll() -> phantom' } },
    { p: 'The weak reference survived the first GC because the image was **softly** reachable. The spec requires soft and weak references to an object to be cleared atomically, at the moment it stops being softly (or weakly) reachable; the phantom reference is enqueued once the object is truly gone. Don\'t read anything into the poll order.' },
    { h: 'How HotSpot decides memory is "short"' },
    { mini: { scene: 'SoftPolicy' } },
    { code: 'keep a soft referent if:\n    clock - timestamp  <=  freeMB * SoftRefLRUPolicyMSPerMB      (default 1000 ms per MB)\n\nclock      static, set at the end of every GC\ntimestamp  per reference, set to clock by the constructor and by each get()\nfreeMB     max heap minus used at the last GC (server VMs)', lang: 'plain', title: 'the LRU soft-reference policy (HotSpot)' },
    { tryit: { note: 'A 1 MB soft referent, idle for 1.5 s, then GCs. The clock only advances at the end of a GC, so the test runs one GC before sleeping and two after.', cmd: '$ for f in 1000 10 0; do echo "SoftRefLRUPolicyMSPerMB=$f"; java -Xmx64m -XX:SoftRefLRUPolicyMSPerMB=$f SoftClock; done', out: 'SoftRefLRUPolicyMSPerMB=1000\nsoft ref after 1.5 s idle + GC: alive\nSoftRefLRUPolicyMSPerMB=10\nsoft ref after 1.5 s idle + GC: cleared\nSoftRefLRUPolicyMSPerMB=0\nsoft ref after 1.5 s idle + GC: cleared' } },
    { tryit: { note: 'A cache of 200 soft 100 KB thumbnails while the app needs 4 MB more each round:', cmd: '$ java -Xmx48m Cache soft', out: 'soft: cached 200 thumbnails (~20 MB)\n  app holds 4 MB -> cache entries still alive: 200\n  app holds 8 MB -> cache entries still alive: 200\n  app holds 12 MB -> cache entries still alive: 200\n  app holds 16 MB -> cache entries still alive: 0\n  app holds 20 MB -> cache entries still alive: 0' } },
    { callout: { tone: 'pull', title: 'why soft caches disappoint', text: 'The policy is per-reference LRU on an opaque clock, and the clearing GC is usually the one that has run out of options, so it clears **everything** it may. You get a cache that is full or empty (200 → 0 above, run to run the cliff moved between 12 and 16 MB), plus extra GC work for the collector. Use a size-bounded cache: Caffeine, or a `LinkedHashMap` LRU (leak 7).' } },
    { h: '"The next GC" is not always next' },
    { mini: { scene: 'WeakOldGen' } },
    { tryit: { note: 'Abridged: 13 young GCs are logged between the first two lines and the result.', cmd: '$ java -Xmx64m -Xlog:gc OldWeak', out: 'GC(0) Pause Full (System.gc()) 1M->0M(10M) 0.773ms\nGC(1) Pause Young (Normal) (G1 Evacuation Pause) 2M->1M(10M) 0.107ms\n...\nGC(13) Pause Young (Normal) (G1 Evacuation Pause) 24M->1M(40M) 0.125ms\nafter young GCs: young referent cleared, old referent alive\nGC(14) Pause Full (System.gc()) 21M->1M(10M) 0.847ms\nafter full GC:   old referent cleared' } },
    { callout: { tone: 'violet', title: 'deeper', text: 'A collector only discovers references whose referents lie in the part of the heap it is collecting. A young GC treats old objects as live without looking at them, so a weak referent that has been promoted waits for a concurrent cycle + mixed GC (G1), a full GC, or, with ZGC/Shenandoah, the next concurrent cycle. That is why `WeakHashMap` entries for long-lived keys can linger for a long time after the key is dropped.' } },
  ] },
  { ch: 4, blocks: [
    { p: 'A `ReferenceQueue` is how you learn that something **was** collected, without polling every reference.' },
    { mini: { scene: 'RefQueue' } },
    { steps: ['**Active**: referent set. Each GC that covers the referent checks its reachability.', '**Pending**: the GC cleared the referent (soft/weak; phantom since Java 9) and linked the Reference into the VM\'s pending list through `discovered`.', '**Enqueued**: the **Reference Handler** thread (priority 10) moved it onto the queue you registered, linked through `next`. A Reference registered with no queue skips this.', '**Inactive**: your thread took it with `poll()` (non-blocking) or `remove()` (blocking, optional timeout).'] },
    { tryit: { note: 'The threads involved, in any JDK 17 process that created a Cleaner:', cmd: '$ jcmd <pid> Thread.print | grep \'^"\'', out: '"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.09ms elapsed=1.82s ... waiting on condition\n"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.10ms elapsed=1.82s ... in Object.wait()\n"Common-Cleaner" #13 daemon prio=8 os_prio=31 cpu=0.07ms elapsed=1.81s ... in Object.wait()\n"Cleaner-0" #14 daemon prio=8 os_prio=31 cpu=0.05ms elapsed=1.81s ... in Object.wait()' } },
    { code: 'static final class TextureRef extends PhantomReference<Texture> {\n    final String name; final long handle;                  // what cleanup needs, copied out\n    TextureRef(Texture t, ReferenceQueue<Texture> q, long handle) { super(t, q); name = t.name(); this.handle = handle; }\n}\nstatic final ReferenceQueue<Texture> QUEUE = new ReferenceQueue<>();\nstatic final Set<TextureRef> LIVE = new HashSet<>();      // keeps the Reference objects themselves alive\n\n// cleanup thread\nwhile (true) {\n    var r = (TextureRef) QUEUE.remove();                 // blocks until the GC enqueues one\n    freeGpu(r.handle);\n    LIVE.remove(r);\n}', title: 'Tracker.java (excerpt)' },
    { tryit: { cmd: '$ java Tracker', out: 'System.gc()\n  cleanup thread: freeing GPU handle of sea.png  (get() = null)\nsky.png still in use: sky.png; sun.png was never reported' } },
    { callout: { tone: 'bad', title: 'the Reference must stay reachable', text: '`sun.png` was loaded with a `TextureRef` that nothing kept. The GC collected the `TextureRef` along with the texture, so it was never enqueued. Always hold registered references somewhere strong (a set, like `LIVE`) until the queue hands them back. `Cleaner` does this for you.' } },
    { callout: { tone: 'violet', title: 'deeper', text: '`PhantomReference.get()` always returns null by design: you cannot resurrect the object, which is precisely the flaw that made finalizers dangerous. Copy what cleanup needs (the handle) into the Reference subclass. To test a reference without creating a strong reference, use `refersTo(null)` (Java 16+) rather than `get() == null`.' } },
  ] },
  { ch: 5, blocks: [
    { p: '**Keys are weakly referenced**, values strongly. An entry disappears some time after nothing else holds its key.' },
    { mini: { scene: 'WeakMapVanish' } },
    { code: 'static final class Page { final int number; Page(int n) { number = n; } }   // identity equals/hashCode\nrecord Thumbnail(byte[] px) {}\n\nMap<Page, Thumbnail> thumbs = new WeakHashMap<>();\nPage p1 = new Page(1), p2 = new Page(2);\nthumbs.put(p1, new Thumbnail(new byte[100_000]));\nthumbs.put(p2, new Thumbnail(new byte[100_000]));\np1 = null;                 // page 1 closed\nSystem.gc();', title: 'Thumbs.java (excerpt)' },
    { tryit: { cmd: '$ java Thumbs', out: 'size = 2\nafter gc, size = 1  keys = [Page2]\nvalue refers to key: after gc, size = 1  keys = [Page3]\nstring literal key: after gc, size = 1' } },
    { tryit: { note: 'Peeking at the private fields with reflection shows the two steps: the GC clears the key, the map removes the entry on its next operation.', cmd: '$ java --add-opens java.base/java.util=ALL-UNNAMED Expunge', out: 'after GC, before touching the map: internal size field = 2, table slots in use = 2\nm.size() = 1   <- expungeStaleEntries() ran inside size()\nafter size(): internal size field = 1, table slots in use = 1' } },
    { code: 'class java.util.WeakHashMap$Entry<K, V> extends java.lang.ref.WeakReference<java.lang.Object> implements java.util.Map$Entry<K, V> {\n  V value;\n  final int hash;\n  java.util.WeakHashMap$Entry<K, V> next;', lang: 'plain', title: 'javap -p java.util.WeakHashMap$Entry (JDK 17)' },
    { h: 'The traps' },
    { mini: { scene: 'WeakMapTraps' } },
    { list: ['**Value refers to key**: the map holds the value strongly, the value holds the key, so the key is strongly reachable and the entry never clears. Keep the key out of the value, or hold it as a `WeakReference` inside the value.', '**Interned keys**: string literals (and small boxed integers from the `Integer` cache) are held by the JVM and never become weakly reachable.', '**Entries vanish nondeterministically**, whenever a GC covering the key runs. Never use it where an entry must still be there.', '**Weak listener registries** (`Collections.newSetFromMap(new WeakHashMap<>())`): a listener held only by the registry disappears at the next GC. The owner must keep it in a field.'] },
    { tryit: { cmd: '$ java WeakRegistry', out: 'registered: 2\nafter gc:   1   (viewer A is still alive and open)\n  viewer A repaints for dark' } },
    { callout: { tone: 'violet', title: 'deeper', text: 'A non-capturing lambda (`t -> System.out.println(t)`) evaluates to a single cached instance held by its call site, so it never gets collected and will hide this bug in tests. The demo uses a capturing lambda, which is a new object each time. `ThreadLocalMap` uses the same weak-key/strong-value design as `WeakHashMap`, which is why it leaks values (leak 3).' } },
  ] },
  { ch: 6, blocks: [
    { mini: { scene: 'Finalize' } },
    { code: 'class Zombie {\n    static Zombie saved;                                   // a GC root\n    final String name;\n    Zombie(String name) { this.name = name; }\n    @Override protected void finalize() {\n        System.out.println("  finalize() running on thread: " + Thread.currentThread().getName());\n        saved = this;                                      // resurrection\n    }\n}', title: 'Zombie.java (excerpt)' },
    { tryit: { cmd: '$ javac -Xlint:deprecation Zombie.java && java Zombie', out: 'Zombie.java:8: warning: [deprecation] finalize() in Object has been deprecated\nGC #1\n  finalize() running on thread: Finalizer\n  saved = cat.png, weak ref cleared\nGC #2\n  saved = null   (finalize() never runs twice)' } },
    { p: 'The weak reference was cleared **before** the object was resurrected (phase 2 runs before phase 3), so after GC #1 the program has a live object whose weak reference says it is dead. Objects with a non-trivial `finalize()` are registered with a `java.lang.ref.Finalizer` (a `FinalReference`) at allocation, which itself costs time.' },
    { mini: { scene: 'FinalizeProblems' } },
    { table: { head: ['problem', 'why'], rows: [['may never run', 'no guarantee, not at exit either (`runFinalizersOnExit` is long gone)'], ['unpredictable timing', 'runs on the Finalizer thread, whenever it gets there, in no order'], ['slows collection', 'at least two GC cycles to reclaim; a slow finalizer backs up everyone'], ['resurrection', '`finalize()` can store `this` in a reachable place'], ['exceptions swallowed', 'a throw is ignored, leaving a half-cleaned object'], ['security hole', 'finalizer attack: subclass, let the constructor throw, grab `this` in `finalize()`']] } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note marks `finalize()` as "deprecated 9, REMOVED". It has **not** been removed: deprecated in Java 9, deprecated *for removal* in Java 18 (JEP 421), and still present in Java 25. JEP 421 also added `--finalization=disabled` (Java 18+; JDK 17 rejects it as an unrecognized option) so you can test whether your application or its libraries depend on finalization.' } },
    { callout: { tone: 'violet', title: 'deeper: defusing the finalizer attack', text: 'The attack needs the object to be finalizable, which only happens once `Object.<init>` completes. Classes that validate in a constructor can do it before calling `super()` (via a static helper in the `this(...)`/`super(...)` argument list, or since Java 25 with flexible constructor bodies) or simply be `final`.' } },
  ] },
  { ch: 7, blocks: [
    { code: TEXTURE_SRC, title: 'Texture.java' },
    { mini: { scene: 'CleanerVsTwr' } },
    { tryit: { cmd: '$ java Tex', out: '1) try-with-resources\n  alloc   sky.png\n  using   sky.png\n  free    sky.png  on thread main\n  block ended\n2) forgot close(): Cleaner is the backstop\n  alloc   sea.png\n  dropped sea.png\n  free    sea.png  on thread Cleaner-0\n3) cleanup action captures this\n  ...nothing. sun.png is reachable from the Cleaner forever\n4) clean() twice runs the action once\n  alloc   moon.png\n  free    moon.png  on thread main' } },
    { table: { head: ['', 'try-with-resources', '`Cleaner`'], rows: [['when it runs', '**deterministically**, at the end of the block', 'after some GC notices, or never'], ['which thread', 'yours', 'the Cleaner\'s (`Cleaner-0`, or `Common-Cleaner` inside the JDK)'], ['visible in the code', 'yes', 'no'], ['correct choice', '**almost always**', 'a backstop for native resources']] } },
    { mini: { scene: 'CleanerTrap' } },
    { code: 'void draw() {\n    try {\n        gpuDraw(handle);                    // last use of fields: `this` may now be unreachable\n    } finally {\n        Reference.reachabilityFence(this);  // keeps this reachable until here (Java 9+)\n    }\n}', title: 'the opposite trap: reachabilityFence' },
    { callout: { tone: 'violet', title: 'deeper', text: 'Reachability is about what the program **will** use, not what is in scope. Once a JIT-compiled method has read its last field, `this` can be considered dead, the Cleaner can run, and the native handle can be freed while `gpuDraw` is still using it. `reachabilityFence(this)` marks the point until which the object must stay reachable. try-with-resources avoids the problem because `close()` is a later use of the object.' } },
  ] },
  { ch: 8, blocks: [
    { p: '**A Java leak is unintentional reachability.** The GC is doing its job: everything leaked is reachable from a root. These seven shapes are most of what you will meet; each demo below ran with `-Xmx32m` so it fails in under a second.' },
    { h: '1 · Static collections' },
    { mini: { scene: 'LeakStatic' } },
    { tryit: { note: 'Leak vs fixed (abridged GC log). In the leak, every GC leaves more live data; in the fixed run each young GC drops back to 1M.', cmd: '$ java -Xmx32m -Xlog:gc Sessions\n$ java -Xmx32m -Xlog:gc Sessions fixed', out: 'GC(0) Pause Young (Normal) (G1 Evacuation Pause) 14M->14M(32M) 2.246ms\nGC(1) Pause Young (Normal) (G1 Evacuation Pause) 17M->17M(32M) 0.808ms\n...\nGC(19) Pause Young (Prepare Mixed) (G1 Evacuation Pause) 30M->30M(32M) 0.211ms\nGC(20) Pause Full (G1 Compaction Pause) 30M->30M(32M) 0.844ms\nGC(21) Pause Full (G1 Compaction Pause) 30M->29M(32M) 1.379ms\njava.lang.OutOfMemoryError: Java heap space at request 292, sessions=291\n--- fixed ---\nGC(0) Pause Young (Normal) (G1 Evacuation Pause) 14M->1M(32M) 0.605ms\nGC(1) Pause Young (Normal) (G1 Evacuation Pause) 19M->1M(32M) 0.370ms\n...\nrequests=1000  sessions=0' } },
    { p: 'Fix: remove entries when their owner is done, bound the collection, or don\'t make it static. Reading a leak in a GC log: look at the number **after** the arrow. If the floor keeps rising across GCs, something is accumulating.' },
    { h: '2 · Unremoved listeners and callbacks' },
    { mini: { scene: 'LeakListeners' } },
    { tryit: { cmd: '$ java -Xmx32m Listeners\n$ java -Xmx32m Listeners fixed', out: 'java.lang.OutOfMemoryError: Java heap space after 296 viewers; listeners still registered: 295\nopened 1000 viewers, listeners still registered: 0' } },
    { h: '3 · ThreadLocal in a pooled thread' },
    { mini: { scene: 'LeakThreadLocal' } },
    { code: 'private static final ThreadLocal<UserContext> CONTEXT = new ThreadLocal<>();\n\nvoid handleRequest(Request r) {\n    try {\n        CONTEXT.set(new UserContext(r.user()));\n        handle(r);\n    } finally {\n        CONTEXT.remove();                 // mandatory in pooled threads\n    }\n}', title: 'the fix' },
    { tryit: { cmd: '$ java Pool && java Pool fixed', out: '  pool-1-thread-1 request user=alice  sees context of: alice\n  pool-1-thread-1 request user=bob    sees context of: bob\n  pool-1-thread-1 request user=null   sees context of: bob\n  pool-1-thread-1 request user=alice  sees context of: alice\n  pool-1-thread-1 request user=bob    sees context of: bob\n  pool-1-thread-1 request user=null   sees context of: nobody' } },
    { tryit: { note: 'Eight pool threads, each leaving a 4 MB buffer in a ThreadLocal, then a full GC once all requests are done:', cmd: '$ java -Xlog:gc PoolMem && java -Xlog:gc PoolMem fixed', out: 'all requests finished; pool threads idle\nGC(0) Pause Full (System.gc()) 36M->33M(120M) 9.169ms\nall requests finished; pool threads idle\nGC(0) Pause Full (System.gc()) 36M->1M(10M) 2.131ms' } },
    { callout: { tone: 'violet', title: 'deeper: why the weak key doesn\'t save you', text: '`javap -p \'java.lang.ThreadLocal$ThreadLocalMap$Entry\'` shows `class ThreadLocal$ThreadLocalMap$Entry extends WeakReference<ThreadLocal<?>> { Object value; }`. The **key** is weak, but a `static final` ThreadLocal is never collected anyway, and the **value** is strong. Even when a key is collected, its stale value stays until a later `set`/`get`/`remove` on that thread happens to expunge it. Only `remove()` is reliable. A thread you create and discard takes its map with it, which is why the leak needs a pool. On Java 25, `ScopedValue` (final in JDK 25) is a bounded, immutable alternative for passing context down a call.' } },
    { p: 'It is also a classic **classloader leak** (8.2): a value whose class came from a webapp, left on a container-owned pool thread, keeps that webapp\'s class loader and all its classes alive after redeploy.' },
    { h: '4 · Inner class references' },
    { mini: { scene: 'LeakInner' } },
    { tryit: { cmd: "$ javap -p 'ImageViewer$Refresh' 'ImageViewer$StaticRefresh'", out: 'class ImageViewer$Refresh implements java.lang.Runnable {\n  final ImageViewer this$0;\n  ImageViewer$Refresh(ImageViewer);\n  public void run();\n}\nclass ImageViewer$StaticRefresh implements java.lang.Runnable {\n  final java.lang.String url;\n  ImageViewer$StaticRefresh(java.lang.String);\n  public void run();\n}' } },
    { tryit: { cmd: '$ java -Xmx32m ImageViewer && java -Xmx32m ImageViewer fixed', out: 'java.lang.OutOfMemoryError: Java heap space after 292 viewers (291 tiny tasks queued)\n1000 viewers closed, 1000 tasks queued, heap fine' } },
    { h: '5 · Unclosed resources' },
    { mini: { scene: 'LeakResources' } },
    { tryit: { note: 'HotSpot on macOS raises the soft file limit at startup (`MaxFDLimit`); turning that off makes `ulimit` bite.', cmd: '$ (ulimit -n 256; java -XX:-MaxFDLimit Unclosed; java -XX:-MaxFDLimit Unclosed fixed)', out: 'after 253 reads: java.io.FileNotFoundException: cat.png (Too many open files)\nread 5000 headers, fine' } },
    { h: '6 · Mutated map keys' },
    { mini: { scene: 'LeakMutatedKey' } },
    { tryit: { note: 'Bucket numbers computed with the HashMap spread `(h ^ h >>> 16) & 15`: width 100 → bucket 11, width 200 → bucket 7.', cmd: '$ java MutKey', out: 'get(key)         = null\nget(cat.png,100) = null\ncontainsKey(key) = false\nsize()           = 1\nafter put again, size() = 2\nremove(key)      = 200px thumbnail, size() = 1' } },
    { h: '7 · Growing caches with no eviction' },
    { mini: { scene: 'LeakCache' } },
    { code: 'static final class Lru<K, V> extends LinkedHashMap<K, V> {\n    final int max;\n    Lru(int max) { super(16, 0.75f, true); this.max = max; }      // true = access order\n    @Override protected boolean removeEldestEntry(Map.Entry<K, V> e) { return size() > max; }\n}', title: 'a bounded LRU (not thread-safe; wrap or use Caffeine)' },
    { tryit: { cmd: '$ java -Xmx32m Cache unbounded; java -Xmx32m Cache lru', out: 'unbounded: java.lang.OutOfMemoryError: Java heap space at image 289, cache size = 288\nlru: 2000 distinct images requested, cache size = 100' } },
  ] },
  { ch: 9, blocks: [
    { mini: { scene: 'SystemGc' } },
    { tryit: { note: 'About 2 million live objects, then lots of short-lived garbage, then one `System.gc()` (abridged):', cmd: '$ java -Xmx512m -Xlog:gc ExplicitGc', out: 'GC(0) Pause Young (Normal) (G1 Evacuation Pause) 23M->23M(130M) 23.523ms\n...\nGC(4) Pause Young (Normal) (G1 Evacuation Pause) 68M->41M(283M) 2.708ms\nGC(5) Pause Young (Normal) (G1 Evacuation Pause) 54M->41M(283M) 0.605ms\nGC(6) Pause Young (Normal) (G1 Evacuation Pause) 57M->41M(283M) 0.345ms\nGC(7) Pause Young (Normal) (G1 Evacuation Pause) 57M->41M(283M) 0.334ms\ncalling System.gc()\nGC(8) Pause Full (System.gc()) 203M->39M(144M) 19.162ms\nlive arrays: 2000' } },
    { tryit: { cmd: '$ java -Xmx512m -Xlog:gc -XX:+DisableExplicitGC ExplicitGc | tail -3', out: 'GC(7) Pause Young (Normal) (G1 Evacuation Pause) 61M->40M(283M) 0.395ms\ncalling System.gc()\nlive arrays: 2000' } },
    { table: { head: ['', ''], rows: [['**it is a hint**', 'the JVM may ignore it; `-XX:+DisableExplicitGC` makes that official'], ['**usually a full GC**', 'G1 logs `Pause Full (System.gc())`, stop-the-world over the whole heap (unless `-XX:+ExplicitGCInvokesConcurrent`)'], ['**undoes adaptive sizing**', 'above, G1 had grown the heap to 283M; the full GC shrank it to 144M'], ['**fixes nothing**', 'leaked objects are reachable, so no GC can collect them']] } },
    { callout: { tone: 'pull', text: '**If `System.gc()` appears to help, you have a leak** (things reachable that shouldn\'t be) **or a sizing problem** (8.3). The only legitimate uses are outside production: benchmark setup between measured runs, and forcing reference clearing in tests, as every demo on this page does.' } },
  ] },
];

const traps = [
  '`SoftReference` caches are full or empty: the HotSpot LRU-clock policy clears everything eligible in one GC. Use Caffeine or a bounded `LinkedHashMap`.',
  '`WeakHashMap` **keys** are weak; values are strong. A value that refers to its key keeps the entry forever. Interned strings never clear either.',
  'Weak references are cleared at the next GC **that covers the referent** (an old object waits for a mixed/full GC), and only if no soft path remains.',
  'A `Cleaner` is a backstop, not a replacement for try-with-resources. If its action references the object (a lambda using `this`), the object is never collected and the action never runs.',
  'A `PhantomReference` (or any Reference) that you don\'t keep strongly reachable is collected with its referent and never enqueued.',
  '`ThreadLocal` without `remove()` in a pooled thread leaks memory and can leak one request\'s data into the next.',
  '`System.gc()` before a memory-heavy operation: a full GC, discarded tuning, no benefit.',
  '`finalize()` has not been removed (still in Java 25), but it is deprecated for removal: don\'t write new ones.',
];

const recap = [
  '**Reachability**: alive = reachable from a GC root; the strongest path decides the level (strong › soft › weak › phantom › unreachable).',
  '**Soft**: cleared when the GC decides memory is short (LRU clock: idle time vs free MB × 1000 ms); all cleared before an OOM. Poor cache.',
  '**Weak**: cleared by the next GC that finds the referent only weakly reachable. `WeakHashMap`, canonical maps, registries.',
  '**Phantom**: `get()` always null; enqueued after collection. Basis of `Cleaner`. Keep Reference objects reachable.',
  '**ReferenceQueue**: active → pending (GC) → enqueued (Reference Handler thread) → your `poll()`/`remove()`.',
  '**`WeakHashMap`**: entries are `WeakReference`s to keys with strong values; stale entries are expunged on the next map operation.',
  '**`finalize()`**: deprecated for removal (JEP 421); may never run, can resurrect, needs two GCs, a security hole.',
  '**Cleanup**: try-with-resources first; `Cleaner` as a backstop with an action that never references the object.',
  '**Leak shapes**: static collections · listeners · `ThreadLocal` in pools · inner classes · unclosed resources · mutated keys · unbounded caches.',
  '**`System.gc()`**: don\'t. If it helps, you have a leak or a sizing problem.',
];

const quiz = [
  { q: 'An image is reachable through a `SoftReference` and a `WeakReference`, and nothing else. A GC runs with plenty of free memory. What happens to the weak reference?', options: ['It is cleared: weak references are always cleared at the next GC', 'It is kept: the image is softly reachable, and weak references are only cleared once an object is weakly reachable', 'It is cleared, and the soft reference is cleared with it', 'It is enqueued but not cleared'], answer: 1, why: 'Reachability is the strongest path. A live soft path makes the object softly reachable, so the weak reference stays. When memory pressure finally clears the soft reference, the weak one is cleared atomically in the same GC (real output: soft, weak and phantom all went together).' },
  { q: 'Why does `PhantomReference.get()` always return null?', options: ['Because phantom referents are cleared before the reference is created', 'So that cleanup code can never resurrect the object, the flaw that made finalizers dangerous', 'Because phantom references only work with a ReferenceQueue that holds the object', 'It is a bug kept for compatibility'], answer: 1, why: 'Phantom references exist only to report that an object is gone. If `get()` returned it, cleanup code could store it somewhere and bring it back, exactly what `finalize()` allowed. Copy what cleanup needs (a handle) into the Reference subclass instead.' },
  { q: 'You register `new PhantomReference<>(texture, queue)` and keep no reference to the PhantomReference itself. The texture is dropped and a GC runs. What does your cleanup thread see?', options: ['The reference arrives on the queue as usual', 'Nothing: the PhantomReference was unreachable too, so it was collected and never enqueued', 'The reference arrives, but get() returns the texture', 'An exception from the Reference Handler thread'], answer: 1, why: 'A Reference object is an ordinary object. If nothing holds it, it is garbage like anything else and the GC never enqueues it (the `sun.png` case in the demo). Keep registered references in a set until processed; `Cleaner` does that internally.' },
  { q: 'A `WeakHashMap<Page, Thumbnail>` entry never disappears, even after the page is closed and many GCs run. What is the most likely cause?', options: ['WeakHashMap only clears entries on a full GC', 'The `Thumbnail` value holds a reference to its `Page` key, so the map keeps the key strongly reachable', 'The map needs `System.gc()` to expunge entries', 'Pages must implement `equals` for weak keys to work'], answer: 1, why: 'Values are strongly held by the map. A value that points at its key makes the key strongly reachable through the map itself, so it can never become weakly reachable. Remove the back-pointer or hold it weakly.' },
  { q: 'Right after a GC clears a `WeakHashMap` key, before you touch the map again, what does the map look like inside?', options: ['The entry is already gone from the table', 'The entry is still in the table (holding its value) and sits on the map\'s private queue; the next `size()`/`get()`/`put()` expunges it', 'The entry\'s value has been cleared too', 'The whole table is rebuilt'], answer: 1, why: 'Each entry is a `WeakReference` registered with the map\'s queue. The GC only clears the key and enqueues the entry. `expungeStaleEntries()` runs inside later map operations and unlinks it (real reflection output: 2 slots, then 1 after `size()`).' },
  { q: 'Why does a `ThreadLocal` value leak in a thread pool but not in a thread you create for one task and then discard?', options: ['Pools use a different ThreadLocal implementation', 'The value lives in the Thread object\'s own map; a pooled thread is never discarded, so its map (and the value) lives on', 'ThreadLocal values are static', 'Pools disable garbage collection of thread-local data'], answer: 1, why: 'Each `Thread` has a `ThreadLocalMap` whose entries hold their values strongly. A discarded thread becomes unreachable and takes its map with it. A pooled thread is reused forever, so values stay until `remove()`, and the next request on that thread can even read them.' },
  { q: 'A `Cleaner` action is written as `() -> freeGpu(this.handle)`. What happens when the texture is no longer used?', options: ['The action runs after the next GC', 'The action runs immediately', 'The texture is never collected and the action never runs, because the Cleaner reaches the texture through the lambda', 'The JVM throws IllegalArgumentException at register time'], answer: 2, why: 'The Cleaner holds the action strongly, and the lambda captures `this`. That is a strong path from a root to the texture, so it never becomes phantom reachable. Use a static nested class or record holding just the handle.' },
  { q: 'An object overrides `finalize()` to do `saved = this`. After its last reference is dropped, which sequence happens in the first GC?', options: ['It is collected, then finalize() runs on the copy', 'Weak references to it are cleared, then it is kept alive and queued for the Finalizer thread, which runs finalize() and resurrects it', 'finalize() runs on the GC thread before any references are cleared', 'Nothing: finalizable objects are skipped until a full GC'], answer: 1, why: 'Reference processing clears soft/weak references first (phase 2), then marks finalizable objects alive again (phase 3) for the Finalizer thread. Real output: the weak reference was cleared, yet `saved` held the same object. finalize() never runs a second time.' },
  { q: 'A weak referent was promoted to the old generation, then its last strong reference was dropped. Thirteen young GCs later, `refersTo(null)` is still false. Why?', options: ['Weak references are only cleared under memory pressure', 'A young GC only processes references whose referents are in the regions it collects; the old referent waits for a mixed or full GC', 'The JIT is keeping the object alive', 'The reference was not registered with a queue'], answer: 1, why: '"Cleared at the next GC" really means the next GC that examines the referent. G1 young GCs never trace old regions, so an old referent can outlive many young GCs (real output: cleared only by the full GC).' },
  { q: 'Someone adds `System.gc()` after each batch job and memory graphs look better. What have they most likely discovered?', options: ['That G1 needs manual help', 'A leak or a sizing problem: either something reachable is accumulating, or the heap is mis-sized, and the forced full GC is masking it', 'That full GCs are cheaper than young GCs', 'Nothing: System.gc() is the recommended way to free batch memory'], answer: 1, why: 'A forced full GC can only collect unreachable objects, which a normal GC would also collect eventually. If it "helps", look at heap-after-GC trends for a leak, or at heap sizing (8.3). Meanwhile it adds stop-the-world full pauses and discards G1\'s adaptive sizing (283M → 144M in the demo).' },
];

window.AN.registerTopic({
  id: '8.7', part: '08', title: 'References and reachability', kicker: 'Part 08 · The JVM',
  lede: 'An object lives exactly as long as something can reach it. Learn the four reference strengths by watching a real GC clear them, the only correct ways to clean up after an object, and the seven shapes a Java memory leak takes.',
  chapters, scenes, captions, notes, traps, recap, quiz,
});
