// Topic 8.8 — JIT compilation. Source notes: Part-08-The-JVM/8.8-jit-compilation.md
// Every PrintCompilation / PrintInlining / LogCompilation line, flag default, timing and JMH result is
// real output from JDK 17.0.17 (Homebrew OpenJDK, Apple M1) for the small programs in this topic.
import { SIntro, SCounters, STiers, SPrintComp, SWarmCurve } from './8.8/scenes1.jsx';
import { SOsr, SInlineTree, SInlineLimits, SEscape, SEscapeStates } from './8.8/scenes2.jsx';
import { SMorphism, SInlineCache, SDeopt, SGuards, SOtherOpts } from './8.8/scenes3.jsx';
import { SNaiveBench, SJmh, SGraal, STraps, SRecap } from './8.8/scenes4.jsx';

const chapters = ['Intro', 'Tiers', 'OSR', 'Inlining', 'Escape analysis', 'Call sites', 'Deoptimisation', 'More optimisations', 'Benchmarking', 'Graal', 'Traps', 'Recap'];

const scenes = [
  { name: 'Intro', dur: 24, ch: 0, title: '', C: SIntro },
  { name: 'Counters', dur: 58, ch: 1, title: 'Two counters decide when to compile', C: SCounters },
  { name: 'Tiers', dur: 60, ch: 1, title: 'Five tiers, one usual path', C: STiers },
  { name: 'PrintComp', dur: 62, ch: 1, title: 'Watch it happen: `-XX:+PrintCompilation`', C: SPrintComp },
  { name: 'WarmCurve', dur: 48, ch: 1, title: 'A real warm-up curve', C: SWarmCurve },
  { name: 'Osr', dur: 56, ch: 2, title: 'On-stack replacement: new code, mid-loop', C: SOsr },
  { name: 'InlineTree', dur: 56, ch: 3, title: 'Inlining: the call disappears', C: SInlineTree },
  { name: 'InlineLimits', dur: 54, ch: 3, title: "Who gets inlined, and who doesn't", C: SInlineLimits },
  { name: 'Escape', dur: 62, ch: 4, title: 'Escape analysis: the object that never existed', C: SEscape },
  { name: 'EscapeStates', dur: 50, ch: 4, title: 'What makes an object escape', C: SEscapeStates },
  { name: 'Morphism', dur: 70, ch: 5, title: 'Monomorphic, bimorphic, megamorphic', C: SMorphism },
  { name: 'InlineCache', dur: 52, ch: 5, title: 'Inline caches: dispatch without the lookup', C: SInlineCache },
  { name: 'Deopt', dur: 66, ch: 6, title: 'Deoptimisation: losing a bet', C: SDeopt },
  { name: 'Guards', dur: 50, ch: 6, title: 'Every speculation has a guard', C: SGuards },
  { name: 'OtherOpts', dur: 56, ch: 7, title: 'The rest of the toolbox', C: SOtherOpts },
  { name: 'NaiveBench', dur: 62, ch: 8, title: 'Why `nanoTime` benchmarks lie', C: SNaiveBench },
  { name: 'Jmh', dur: 66, ch: 8, title: 'JMH: a harness that knows the JIT', C: SJmh },
  { name: 'Graal', dur: 40, ch: 9, title: 'Graal: a JIT written in Java', C: SGraal },
  { name: 'Traps', dur: 38, ch: 10, title: 'Traps', C: STraps },
  { name: 'Recap', dur: 36, ch: 11, title: 'Recap', C: SRecap },
];

const captions = {
  Intro: [[0.8, 'Here is a tiny loop: add up the areas of 100 circles.'], [5.5, 'The first calls run in the interpreter: about 3,450 ns each on this machine.'], [11, 'Moments later the same bytecode takes about 80 ns. Nothing in the code changed.'], [17, 'The JIT did that. This topic opens it up, using this one loop all the way through.']],
  Counters: [[0.5, 'Every method starts in the interpreter, and HotSpot keeps two counters for it.'], [5, 'Each call bumps the invocation counter, `i`.'], [10.5, 'Each jump back to the top of a loop bumps the back-edge counter, `b`. One call of `total` adds 100.'], [17, 'Checking on every tick would be slow, so the interpreter asks the policy every 128 calls or 1,024 back-edges.'], [24, 'The rule for tier 3: more than 200 calls, or more than 100 calls with `i + b` over 2,000.'], [31, 'Real log: `total` was queued at 103 calls and 10,240 back-edges. Just past the minimum of 100.'], [38, 'A background compiler thread does the work. Meanwhile, calls keep running in the interpreter.'], [45, '`Circle.area` has no loop, so only calls count: it was queued at 256, the first check past 200.'], [51.5, 'From tier 3 to C2, the same rules with bigger numbers: 5,000 calls, 15,000 combined, or 40,000 back-edges for OSR.']],
  Tiers: [[0.5, 'HotSpot has two JIT compilers, C1 and C2, arranged as five tiers.'], [5, 'Tier 0 is the interpreter. Tier 4 is C2. Tiers 1 to 3 are all C1, with different amounts of profiling.'], [12, 'The usual path is 0, then 3, then 4. Tier 3 is C1 code that also records a profile.'], [19, 'The profile lives in a MethodData object: counts, branch directions, and the receiver classes seen at each call.'], [27, 'Our call site saw `Circle` 163,956 times out of 163,956. C2 will bet on that.'], [34, 'Profiling has a cost. Tier 3 ran our loop at about 310 ns; plain C1 without profiling manages 122.'], [41, 'That is why tier 3 is a short stop: just long enough to gather a profile for C2.'], [47, 'Trivial methods like getters go to tier 1 and stay there: C2 could not do better.'], [53, 'Tier 2 is a fallback: when C2’s queue is long, C1 profiles lightly while the method waits.']],
  PrintComp: [[0.5, 'Run the loop with `-XX:+PrintCompilation`: one line per compilation. Real JDK 17 output.'], [6, 'First the JDK’s own hot methods: `String.hashCode`, `Object.<init>`. Your code isn’t the only code.'], [12, 'Column one is milliseconds since start. Column two is a compile id, in queue order.'], [18, 'The digit before the method is the tier. `Circle::area` reaches tier 3, then tier 4 in the same millisecond.'], [25, 'Then the tier 3 version is `made not entrant`: no new call may enter it. Callers switch to tier 4.'], [32, '`%` marks an OSR compile, entered mid-loop at bytecode 11: the top of our for-loop.'], [39, 'The normal tier 4 `total` follows, and its tier 3 version is retired too.'], [46, 'The size in brackets is bytecode bytes, not machine code. `area` is 14 bytes: inlining cares about this number.'], [53, 'Flags you may see: `%` OSR, `s` synchronized, `!` exception handlers, `n` native wrapper.']],
  WarmCurve: [[0.5, 'Real timing for our loop: 500 calls per batch, one dot per batch. JDK 17 on an M1.'], [6, 'Batch 1 averages 1,257 ns: mostly interpreter, then C1 arrives.'], [12, 'Then a plateau around 305 to 350 ns: tier 3 code, busy collecting a profile.'], [18, 'C2 compiles in the background. When its code is installed, batch 25 drops to 80 ns.'], [25, 'Now compare other modes. `-Xint`, interpreter only: about 3,450 ns, forever.'], [31, 'C1 only: 122 ns, quick to reach, never better. C2 only: 73 ns, but four slow batches first.'], [38, 'Tiered gets both: C1’s quick start, then C2’s peak. This is why services warm up.'], [43.4, 'And why a benchmark that stops at batch 10 measures the wrong compiler.']],
  Osr: [[0.5, 'Some methods are called once but loop for ages. Counting calls would never compile them.'], [6, '`sumAreas` is called once. Its invocation counter stays at 1; its back-edge counter races ahead.'], [13, 'Past 60,000 back-edges, the JVM compiles a version that can be entered at the loop header: bytecode 4.'], [20, 'Then it swaps mid-loop: the interpreter frame’s locals, `n`, `sum` and `i`, are copied into the compiled frame.'], [27, 'The loop carries on in machine code, from the same iteration. That is on-stack replacement.'], [33, 'Real runs: 10,000 or even 60,000 iterations, no OSR at all. 70,000 gets a tier 3 OSR compile.'], [40, 'A million iterations reaches C2’s OSR too. Then the loop finishes, and that version is made not entrant.'], [47, 'Why? C2 had never seen the loop exit, so it compiled that exit as a trap. More on traps soon.']],
  InlineTree: [[0.5, 'Inlining replaces a call with a copy of the callee’s body.'], [5, 'Before: `total` calls `area` 100 times per run. Each call is a jump, a new frame, a return.'], [11, 'After: the body of `area` sits inside the loop. The call is gone.'], [17, 'It is guarded: the profile said every `s` was a `Circle`, so C2 checks the class and traps otherwise.'], [24, '`-XX:+PrintInlining` confirms it: `Circle::area`, 14 bytes, inline (hot), from that profile.'], [31, 'The saved call is the small win. The big one: now the optimiser can see everything at once.'], [38, '`s.r` is loaded once instead of twice. `Math.PI` is just a constant. The loop is one body.'], [45, 'Same for getters: `p.getX() + p.getY()` becomes `p.x + p.y`. Escape analysis needs this too.'], [51, 'Every other optimisation works inside one compiled body. Inlining decides how big that body is.']],
  InlineLimits: [[0.5, 'C2 doesn’t inline everything. It decides by bytecode size and by how hot the call is.'], [6, 'Up to 35 bytes, a callee is always a candidate: `MaxInlineSize`. A getter is 5 bytes; `area` is 14.'], [13, 'Hot call sites may inline up to 325 bytes: `FreqInlineSize`.'], [19, 'Real output from one hot method. `tiny`, 8 bytes: inline. `medium`, 100 bytes but hot: inline.'], [27, '`huge`, 484 bytes: hot method too big. It stays a real call, and C2 can’t see inside it.'], [34, '`rare`, also 100 bytes, but rarely called: too big. Hotness changes the limit.'], [40, 'C1 is stricter: `callee is too large` for anything over 35 bytes. There are depth limits too.'], [46, 'So small methods are not slow. They are the ones that get inlined. Large ones block the optimiser.']],
  Escape: [[0.5, 'Can an object be created and never exist? `distance` makes two `Point`s per call.'], [6, 'Without help, each call allocates 64 bytes on the heap. 100 million calls: 6.4 GB of garbage.'], [13, 'C2 first inlines the constructor and the accessors. Now it can follow every use of `p1` and `p2`.'], [20, 'Is either stored in a field, returned, or passed to code it can’t see? No. They never escape.'], [27.5, 'So scalar replacement takes each field out of its object: `p1.x` becomes plain `x1`, in a register.'], [33, 'The allocations are deleted. No object, no header, no GC work.'], [40, 'Measured: 97 ms and 216 bytes allocated in total for 100 million calls. None of it from the loop.'], [47, 'With `-XX:-DoEscapeAnalysis`: 448 ms, 6,400,000,216 bytes, and 34 young collections instead of none.'], [55, 'Exactly two 32-byte `Point`s per call. Escape analysis made them disappear.']],
  EscapeStates: [[0.5, 'C2 sorts every allocation into one of three escape states.'], [5, 'NoEscape: used only inside this compiled body. These can be scalar-replaced.'], [11, 'ArgEscape: passed to a call that wasn’t inlined. It must exist, but it can’t outlive the call.'], [18, 'GlobalEscape: stored in a field, returned, or thrown. It is a real heap object.'], [24, 'Add one line, `last = p1`, and `p1` escapes. The run allocates 3.2 GB: `p1` is back, `p2` is still gone.'], [32, 'Locks get the same treatment. A lock on an object no other thread can ever see is removed.'], [38, 'Real numbers: 97 ms with lock elision, 1,136 ms with `-XX:-EliminateLocks`.'], [44, 'Escape analysis is fragile: one call too big to inline, and the object escapes. Enjoy it; don’t rely on it.']],
  Morphism: [[0.5, 'The profile at the call site `s.area()` records which receiver classes it has actually seen.'], [6, 'It has room for two classes, plus a counter for everything else. Phase 1: only `Circle`.'], [12, 'One class seen: monomorphic. C2 inlines `Circle.area` behind a single class check.'], [19, 'Real output: inline (hot), TypeProfile 760,993 out of 760,993 = Circle. About 1 ns per call.'], [26, 'Phase 2: we start mixing in `Square`. The second row fills. Bimorphic.'], [32, 'C2 inlines both bodies, with an if and an else. Still about 1 ns per call.'], [39, 'Phase 3: `Triangle` arrives. No row left: the site is megamorphic.'], [45, 'C2 gives up inlining: `Shape::area`, virtual call. A real dispatch for every element.'], [52, '3.65 ns per call: nearly four times slower, and nothing can be optimised across the call.'], [59, 'An interface with one implementation costs nothing. It’s the third type at a hot site that costs.']],
  InlineCache: [[0.5, 'When a call isn’t inlined, it still doesn’t have to do the full vtable lookup every time.'], [5, 'Compiled call sites carry an inline cache. It starts clean: the first call goes into the JVM to resolve it.'], [11, 'The resolver patches the site to monomorphic: “if the receiver is a `Circle`, jump straight to `Circle.area`.”'], [18, 'A compare and a direct jump. No klass-to-vtable walk while the class keeps matching.'], [24, 'When a `Square` misses the check, the site goes megamorphic: it now calls a vtable or itable stub.'], [32, 'That stub is the 8.1 lookup: dependent loads and an indirect jump the CPU has to predict.'], [38, 'One more C2 rule: if one class is at least 90% of a megamorphic site, C2 inlines that one anyway.'], [45, 'Real: in one run phase 3 still saw 94% `Circle`, left over from phase 1, so C2 inlined it. Old counts linger.']],
  Deopt: [[0.5, 'C2’s code for `total` rests on a bet: every shape is a `Circle`. The class check guards it.'], [6, 'Phase 2 begins and the very first element is a `Square`. The check fails.'], [11, 'The failed branch is an uncommon trap: a call into the JVM saying “my assumption broke, here”.'], [17, 'The JVM deoptimises. It reads the compiled frame’s registers and rebuilds an interpreter frame, slot by slot.'], [25, '`sum` lands in slots 1 and 2, `i` in slot 5, `s` in slot 6: exactly where the interpreter expects them.'], [32, 'Execution resumes in the interpreter at bytecode 27, the `invokeinterface`. Nothing is lost.'], [38, 'The compiled code is made not entrant, so no new call enters it. The profile now includes `Square`.'], [45, 'The real log: reason `class_check`, at bci 27, in compile 39. Both tier 4 versions were retired.'], [52, 'Moments later C2 recompiles `total` as id 127: bimorphic this time. Speed is back.'], [58, 'The bet, the guard, the undo. That loop is what lets the JIT be bolder than a static compiler.']],
  Guards: [[0.5, 'Every speculative optimisation comes with a guard, and every guard has a way back.'], [5, 'The profile says only `Circle`? A class check. Failure reason: `class_check`.'], [11, 'A branch never taken? It isn’t compiled at all, just a trap: `unstable_if`. Our OSR loop exit was one.'], [18, 'Never null? C2 drops the check and lets the hardware fault catch it: `null_check`.'], [24, 'Some guards aren’t in the code at all. Class hierarchy analysis records a dependency instead.'], [30, '“`Circle.area` is the only `Shape.area`.” When `Square` loaded, the real log said `dependency_failed`.'], [38, 'Dependencies are checked when a class loads, and every compiled method relying on one is invalidated.'], [44, 'So loading a class can slow down code that was already fast: a plugin, a lazy implementation, a mock.']],
  OtherOpts: [[0.5, 'Inside one inlined body, C2 has a whole toolbox. Six worth knowing by name.'], [5, 'Loop unrolling: do four iterations per pass, so the loop test and jump run a quarter as often.'], [12, 'Range-check elimination: prove `i` stays inside the array once, before the loop, instead of on every access.'], [20, 'Lock coarsening: neighbouring lock and unlock pairs on the same object merge into one region.'], [27, 'Constant folding: arithmetic on constants is done once, at compile time.'], [33, 'Loop-invariant hoisting: work that gives the same answer every iteration moves out of the loop.'], [40, 'And dead code elimination: compute a value nobody uses, and the computation is deleted.'], [47, 'That last one is great for real code, and a disaster for a naive benchmark. Watch.']],
  NaiveBench: [[0.5, 'The classic home-made benchmark: read the clock, run a loop, read the clock again.'], [6, 'Two loops of 10 million calls to `area`. One ignores the result, one adds it up. Real output.'], [13, 'Round 1: 3.3 ms and 12.6 ms. Rounds 3 to 5: the first loop takes 0.000 ms.'], [20, 'Ten million calls in no time? No calls at all. C2 saw the result was unused and deleted the loop.'], [28, 'The second loop is honest: about 10 ms, 1 ns per iteration, once C2 is in.'], [34, 'Rounds 1 and 2 measured the interpreter, C1 and OSR code. With `-Xint` it is 220 ms.'], [41, 'Everything that can go wrong: no warm-up, dead code, constant folding, OSR, a GC in the middle.'], [49, 'Each one silently changes what you measured. You get a number. It just isn’t the answer.'], [55, 'This is why the JDK team wrote a tool for it.']],
  Jmh: [[0.5, 'JMH, the Java Microbenchmark Harness, is built by the people who build the JIT.'], [6, 'It forks a fresh JVM for each benchmark, so one benchmark’s profile can’t pollute the next.'], [12, 'In each fork it runs warm-up iterations and throws them away, then measures.'], [19, 'Return a value and JMH consumes it, so it can’t be dead. `Blackhole.consume` does the same for several values.'], [26, 'Inputs come from `@State` fields, not constants, so they can’t be folded away.'], [32, 'Real JMH 1.37 on JDK 17: three forks, five warm-ups, five measurements each.'], [38, '`ignored`: 0.642 ns for 1,000 calls. JMH can’t save you if you discard the result yourself.'], [45, '`returned`: 939 ns. That is 1,000 dependent additions, one after another, about 3 cycles each.'], [53, '`blackhole`: 242 ns. Each result is consumed separately, so the CPU can overlap the work.'], [59, 'Three honest numbers for three different questions. JMH makes it sound; you choose what to measure.']],
  Graal: [[0.5, 'C2 is a large C++ compiler. Graal is a JIT compiler written in Java.'], [5, 'HotSpot talks to it through JVMCI, a compiler interface. Graal takes C2’s place at tier 4.'], [11, 'It is strong where code is abstract: deeper inlining and partial escape analysis for streams and lambdas.'], [18, 'The usual flags to switch it on look like this. On a stock OpenJDK 17, here is what really happens.'], [24, '“No JVMCI compiler found.” JDK 17 removed the experimental Graal JIT (JEP 410). Get it from a GraalVM JDK.'], [32, 'Not to be confused with native image (8.10): the same project, compiling ahead of time, no JIT at all.']],
  Traps: [[0.5, 'Five traps worth avoiding.'], [3.5, 'A `nanoTime` loop measures the interpreter, C1, or a deleted loop. Use JMH.'], [10, 'Interfaces and getters are not slow: one type at a site is inlined behind a check.'], [16.5, 'Small methods are the ones that get inlined. Huge ones are the problem.'], [23, 'Performance is not fixed once warm: new classes can deoptimise hot code.'], [29.5, 'And escape analysis only helps when C2 can see an object’s whole life.']],
  Recap: [[0.5, 'Recap.'], [3, 'Tiers: interpreter, C1 with a profile, then C2. Calls and back-edges decide.'], [8.5, 'OSR swaps a long-running loop into compiled code mid-flight.'], [13.5, 'Inlining is the enabler: tiny methods are free.'], [18.5, 'Escape analysis can make allocations disappear.'], [23.5, 'One or two types at a call site get inlined; three or more get a real dispatch.'], [28.5, 'The JIT speculates, guards and undoes. And benchmark with JMH, never `nanoTime`.']],
};

const SHAPES = `interface Shape { double area(); }

final class Circle implements Shape {
    final double r;
    Circle(double r) { this.r = r; }
    public double area() { return Math.PI * r * r; }
}

public class Shapes {
    static double total(Shape[] shapes) {
        double sum = 0;
        for (Shape s : shapes) sum += s.area();
        return sum;
    }
    public static void main(String[] args) {
        Shape[] shapes = new Shape[100];
        for (int i = 0; i < shapes.length; i++) shapes[i] = new Circle(i);
        double x = 0;
        for (int call = 0; call < 20_000; call++) x += total(shapes);
        System.out.println(x);
    }
}`;

const notes = [
  { ch: 1, blocks: [
    { p: '**Every method starts in the interpreter.** HotSpot watches how often it runs and, when it is hot enough, compiles it in the background: first with **C1** (fast to compile, adds profiling), then with **C2** (slow to compile, aggressively optimised, using that profile). Our running example for the whole topic:' },
    { code: SHAPES, title: 'Shapes.java' },
    { h: 'Two counters' },
    { mini: { scene: 'Counters' } },
    { p: 'Each method has an **invocation counter** `i` (bumped on every call) and a **back-edge counter** `b` (bumped every time a loop jumps back to its header). To keep counting cheap, the interpreter only consults the compile policy every 2^7 = 128 calls (`Tier0InvokeNotifyFreqLog=7`) or every 2^10 = 1,024 back-edges (`Tier0BackedgeNotifyFreqLog=10`).' },
    { table: { head: ['transition', 'fires when (JDK 17 defaults)', 'flags'], rows: [['0 → 3 (C1 + profile)', '`i > 200`, or `i > 100 && i + b > 2,000`', '`Tier3InvocationThreshold`, `Tier3MinInvocationThreshold`, `Tier3CompileThreshold`'], ['0 → 3, OSR', '`b > 60,000`', '`Tier3BackEdgeThreshold`'], ['3 → 4 (C2)', '`i > 5,000`, or `i > 600 && i + b > 15,000`', '`Tier4InvocationThreshold`, `Tier4MinInvocationThreshold`, `Tier4CompileThreshold`'], ['3 → 4, OSR', '`b > 40,000`', '`Tier4BackEdgeThreshold`'], ['(tiered off)', '`CompileThreshold=10000`', 'only with `-XX:-TieredCompilation`']] } },
    { callout: { tone: 'violet', title: 'deeper: the thresholds are scaled', text: 'The policy multiplies these thresholds by a factor that grows with the length of the compile queues (`Tier3LoadFeedback`, `Tier4LoadFeedback`), so a busy JVM compiles less eagerly. Treat the numbers as "approximately, and adaptive". In our run `total` was queued at exactly `count=103 backedge_count=10240`: the `i > 100 && i + b > 2,000` rule, checked at the 10th back-edge notification.' } },
    { h: 'Five tiers' },
    { mini: { scene: 'Tiers' } },
    { table: { head: ['tier', 'compiler', 'what it is for'], rows: [['0', 'interpreter', 'everything starts here; also gathers basic counts'], ['1', 'C1, no profiling', 'trivial methods (getters, tiny leaves): C2 could not do better, so stop here'], ['2', 'C1, counters only', 'used when C2\'s queue is long: lighter than tier 3 while the method waits'], ['3', 'C1, full profiling', 'the usual stop: records branch counts and receiver types in a `MethodData` object'], ['4', 'C2', 'fully optimised, using the tier 3 profile']] } },
    { p: 'Profiling is not free. On this machine our loop ran at ≈ 310 ns per `total()` in tier 3, but 122 ns with C1 alone (`-XX:TieredStopAtLevel=1`) and ≈ 80 ns in C2. Tier 3 is meant to be a short stop.' },
    { h: 'Reading -XX:+PrintCompilation' },
    { mini: { scene: 'PrintComp' } },
    { tryit: { note: 'Real JDK 17 output for Shapes.java (abridged: the JDK\'s own methods removed).', cmd: '$ javac Shapes.java\n$ java -XX:+PrintCompilation Shapes | grep -E "Shapes|Circle"', out: '42   10       3       Circle::area (14 bytes)\n42   11       4       Circle::area (14 bytes)\n42   12       3       Shapes::total (42 bytes)\n42   10       3       Circle::area (14 bytes)   made not entrant\n43   13 %     4       Shapes::total @ 11 (42 bytes)\n47   14       4       Shapes::total (42 bytes)\n52   12       3       Shapes::total (42 bytes)   made not entrant' } },
    { list: ['Columns: **ms since start**, **compile id**, **flags**, **tier**, method, **bytecode size**, and optionally `made not entrant`.', 'Flags: `%` OSR (with `@ bci`), `s` synchronized, `!` has exception handlers, `b` blocking compile, `n` native wrapper.', '`made not entrant`: no new call may enter that version (frames already in it may finish). Seen when a lower tier is replaced, or after a deoptimisation.'] },
    { h: 'The warm-up curve' },
    { mini: { scene: 'WarmCurve' } },
    { table: { head: ['mode', 'flag', 'ns per total() (steady)'], rows: [['interpreter only', '`-Xint`', '≈ 3,450'], ['tiered (default)', '', '≈ 80 (after ≈ 3 ms of tier 3 at ≈ 305–350)'], ['C1 only', '`-XX:TieredStopAtLevel=1`', '122'], ['C2 only', '`-XX:-TieredCompilation`', '73, after four batches at ≈ 1,900–2,600']] } },
    { callout: { tone: 'pull', title: 'consequence', text: 'A Java service is slow for its first requests and then several times faster. That is the JIT reaching C2, not caches warming. A benchmark without warm-up measures the wrong compiler.' } },
  ] },
  { ch: 2, blocks: [
    { p: 'A method that is **called once** but loops millions of times would never reach an invocation threshold. **On-stack replacement** (OSR) handles it: when the back-edge counter passes the threshold, the JVM compiles a special version of the method whose entry point is the **loop header**, then transfers the running interpreter frame into it.' },
    { mini: { scene: 'Osr' } },
    { steps: ['The back-edge counter passes ≈ 60,000 (`Tier3BackEdgeThreshold`).', 'A compile is queued with an OSR entry bci: the loop header (bci 4 in `sumAreas`).', 'At the next back-edge, the interpreter copies the frame\'s locals (`n`, `sum`, `i`) into an OSR buffer.', 'It jumps into the compiled code, which loads those values and continues the same iteration.'] },
    { tryit: { note: 'Real runs of Osr.java with different loop lengths. Only the 70,000+ runs print anything.', cmd: '$ java -XX:+PrintCompilation Osr 60000 | grep Osr::\n$ java -XX:+PrintCompilation Osr 70000 | grep Osr::\n$ java -XX:+PrintCompilation Osr 1000000 | grep Osr::', out: '22    6 %     3       Osr::sumAreas @ 4 (29 bytes)\n---- (1,000,000)\n21    6 %     3       Osr::sumAreas @ 4 (29 bytes)\n21    7       3       Osr::sumAreas (29 bytes)\n21    8 %     4       Osr::sumAreas @ 4 (29 bytes)\n22    6 %     3       Osr::sumAreas @ 4 (29 bytes)   made not entrant\n23    8 %     4       Osr::sumAreas @ 4 (29 bytes)   made not entrant' } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note says a loop "running 10,000 iterations" qualifies via OSR. With JDK 17 defaults it does not: 10,000 and even 60,000 iterations produced **no** OSR compile; tier 3 OSR needs more than 60,000 back-edges (`Tier3BackEdgeThreshold`), and C2 OSR another 40,000 counted in tier 3.' } },
    { callout: { tone: 'violet', title: 'deeper: why the C2 OSR version died', text: 'The `-XX:+LogCompilation` log shows `<uncommon_trap reason=\'unstable_if\' action=\'reinterpret\' compile_kind=\'osr\'>` at bci 6, the `if_icmpge` loop test. The profile had never seen the loop exit, so C2 compiled the exit path as a trap. When the loop finally ended, the trap fired and that code was made not entrant. OSR code is also why a benchmark loop written inside `main` behaves differently from a method called normally.' } },
  ] },
  { ch: 3, blocks: [
    { p: '**Inlining replaces a call with the callee\'s body.** Saving the call (frame setup, argument moves, return) is the small win. The big win is that the optimiser now sees caller and callee as **one body**, so every other optimisation can work across what used to be a call boundary.' },
    { mini: { scene: 'InlineTree' } },
    { code: '// roughly what C2 builds for total() after inlining Circle.area (a sketch, not real output)\nfor (Shape s : shapes) {\n    if (s.klass != Circle) uncommon_trap();   // guard from the type profile\n    double r = ((Circle) s).r;                // one load instead of two\n    sum += 3.141592653589793 * r * r;\n}', lang: 'java', title: 'after inlining' },
    { tryit: { cmd: '$ java -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining -XX:+PrintCompilation Shapes', out: '61   13 %     4       Shapes::total @ 11 (42 bytes)\n                              @ 27   Circle::area (14 bytes)   inline (hot)\n                               \\-> TypeProfile (163956/163956 counts) = Circle' } },
    { h: 'The limits' },
    { mini: { scene: 'InlineLimits' } },
    { table: { head: ['flag (JDK 17 default)', 'meaning'], rows: [['`MaxInlineSize=35`', 'callees up to 35 **bytecode bytes** are inlined even if not hot'], ['`FreqInlineSize=325`', 'hot callees up to 325 bytes may be inlined (platform-dependent; 325 on x86-64 and AArch64)'], ['`MaxInlineLevel=15`', 'maximum **nesting depth** of inlined calls in one compile'], ['`MaxRecursiveInlineLevel=1`', 'how many times a recursive call may be inlined into itself'], ['`InlineSmallCode=2500`', 'don\'t inline a callee whose existing compiled code is already bigger than this (machine-code bytes)'], ['`C1MaxInlineSize=35`', 'C1\'s limit, regardless of hotness']] } },
    { tryit: { note: 'Sizes.java: one hot method calling four helpers. Real C2 decisions (abridged).', cmd: '$ java -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining Sizes', out: '                              @ 1   Sizes::tiny (8 bytes)   inline (hot)\n                              @ 5   Sizes::medium (100 bytes)   inline (hot)\n                              @ 10   Sizes::huge (484 bytes)   hot method too big\n                              @ 24   Sizes::rare (100 bytes)   too big' } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note labels `MaxInlineLevel=15` as "recursion depth". It is the maximum **nesting depth** of inlining (A inlines B inlines C…). Recursive inlining is limited separately by `MaxRecursiveInlineLevel=1`.' } },
    { callout: { tone: 'pull', text: 'A getter is **5 bytes** of bytecode (`aload_0`, `getfield`, `dreturn`: three instructions). PrintInlining even labels them specially: `Point::x (5 bytes) accessor`. "Getters are slow" has been false for decades. The corollary matters more: **a huge method may not be inlined**, and then nothing around that call can be optimised through it.' } },
  ] },
  { ch: 4, blocks: [
    { p: 'After inlining, C2 runs **escape analysis**: for each allocation, can it prove the object never leaves the compiled body? If so, **scalar replacement** turns the object\'s fields into plain local values (registers), and the allocation is deleted. No object, no header, no GC work.' },
    { mini: { scene: 'Escape' } },
    { code: 'record Point(double x, double y) {}\n\nstatic double distance(double x1, double y1, double x2, double y2) {\n    var p1 = new Point(x1, y1);\n    var p2 = new Point(x2, y2);\n    double dx = p2.x() - p1.x(), dy = p2.y() - p1.y();\n    return Math.sqrt(dx * dx + dy * dy);\n}', title: 'Escape.java' },
    { tryit: { note: 'Allocated bytes are measured with `ThreadMXBean.getThreadAllocatedBytes` around 100 million calls.', cmd: '$ java Escape\n$ java -XX:-DoEscapeAnalysis Escape', out: '100M calls: 97 ms, allocated 216 bytes   (sink=505000000)\n100M calls: 448 ms, allocated 6,400,000,216 bytes   (sink=505000000)' } },
    { p: '6,400,000,000 bytes = 100 million calls × 2 `Point`s × 32 bytes (12-byte header, padding, two 8-byte doubles). With `-Xlog:gc` the second run shows 34 young collections; the first shows none.' },
    { h: 'Escape states' },
    { mini: { scene: 'EscapeStates' } },
    { table: { head: ['state', 'meaning', 'what C2 can do'], rows: [['NoEscape', 'used only inside this compiled body', 'scalar replacement; remove its locks'], ['ArgEscape', 'passed to a callee that was not inlined, but does not outlive it', 'must allocate; can still remove its locks'], ['GlobalEscape', 'stored in a field or array, returned, thrown', 'a normal heap object']] } },
    { tryit: { note: 'Escape2 adds `last = p1;` (a static field). Locks.java synchronizes on a fresh local `Object`.', cmd: '$ java Escape2\n$ java Locks\n$ java -XX:-EliminateLocks Locks', out: '100M calls: 466 ms, allocated 3,200,000,216 bytes   (sink=505000000)\n100M calls: 97 ms  (1.0e+24)\n100M calls: 1136 ms  (1.0e+24)' } },
    { callout: { tone: 'bad', title: 'corrections to the source note', text: '`-XX:+PrintEscapeAnalysis` is a **notproduct** flag: a normal JDK 17 refuses it ("available only in debug version of VM"). And HotSpot does **not** stack-allocate objects; what it does is scalar replacement (Graal adds partial escape analysis). Use `-XX:-DoEscapeAnalysis` and an allocation measurement to see the effect.' } },
    { callout: { tone: 'violet', title: 'deeper: why it is fragile', text: 'Escape analysis is per compiled body, after inlining. A callee too big to inline makes its arguments ArgEscape. An object merged from two branches (`p = cond ? new Point(…) : other`) usually cannot be scalar-replaced. Large arrays (over `EliminateAllocationArraySizeLimit=64` elements) are never replaced. Don\'t rely on it for correctness of a performance budget, but do stop hand-pooling small short-lived objects (8.5).' } },
  ] },
  { ch: 5, blocks: [
    { p: 'A virtual or interface call (8.1) needs to find the right implementation at runtime. Tier 3 code records, per call site, **which receiver classes actually arrived**: two rows (`TypeProfileWidth=2`) with counts, plus a counter for everything else. C2 then decides:' },
    { table: { head: ['call site', 'classes seen', 'what C2 does', 'measured (ns per area())'], rows: [['monomorphic', '1', 'inline it behind one class check; trap otherwise', '0.97'], ['bimorphic', '2', 'inline both behind if / else; trap otherwise', '0.94'], ['megamorphic', '3+', 'virtual call through an inline cache / vtable or itable stub', '3.65']] } },
    { mini: { scene: 'Morphism' } },
    { tryit: { note: 'Phases.java runs the same loop with only Circle, then Circle + Square, then all three. Real C2 decisions at bci 27 (abridged).', cmd: '$ java -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining -XX:+PrintCompilation Phases', out: '---- only Circle\n      @ 27   Circle::area (14 bytes)   inline (hot)\n       \\-> TypeProfile (760993/760993 counts) = Circle\n---- Circle + Square\n      @ 27   Circle::area (14 bytes)   inline (hot)\n      @ 27   Square::area (10 bytes)   inline (hot)\n---- Circle + Square + Triangle\n      @ 27   Shape::area (0 bytes)   virtual call' } },
    { h: 'Inline caches' },
    { mini: { scene: 'InlineCache' } },
    { p: 'When a call is not inlined (always in C1 code, and at megamorphic sites in C2), HotSpot still avoids a full lookup on every call with an **inline cache** in the compiled call instruction. It starts **clean** (the first call enters the runtime to resolve the target), becomes **monomorphic** (compare the receiver\'s klass with the cached one, jump straight to the target), and on a miss becomes **megamorphic**, calling a vtable or itable stub: the dispatch from 8.1.' },
    { callout: { tone: 'violet', title: 'deeper: the 90% rule and stale profiles', text: 'If one class makes up at least `TypeProfileMajorReceiverPercent=90`% of a site, C2 inlines it with a guard and uses a virtual call for the rest. Profiles are cumulative: in one of our runs, phase 3 still showed `TypeProfile (1215087/1292834 counts) = Circle` (94%) because of phase 1\'s counts. Another run of the same program printed `virtual call`. This is exactly why JMH forks a fresh JVM per benchmark.' } },
    { callout: { tone: 'pull', text: '**An interface with one loaded implementation is as fast as a direct call**, and so is one with two. "Don\'t add interfaces, they\'re slow" is wrong. What costs is three or more receiver types at one hot call site, and a benchmark that only ever uses one implementation measures a call site production may never have.' } },
  ] },
  { ch: 6, blocks: [
    { p: 'C2 optimises **speculatively**, for what the profile says has happened, and backs each bet with a guard. When a guard fails, the JVM **deoptimises**: it stops at the failing point, rebuilds the equivalent interpreter frame(s) from the compiled frame, continues in the interpreter, marks the compiled code *not entrant*, and lets the method re-profile and recompile.' },
    { mini: { scene: 'Deopt' } },
    { tryit: { note: 'Phase 2 of Phases.java: the first Square reaches the C2-compiled total (abridged).', cmd: '$ java -XX:+PrintCompilation -XX:+UnlockDiagnosticVMOptions -XX:+LogCompilation Phases', out: '163   39       4       Phases::total (42 bytes)   made not entrant\n163   38 %     4       Phases::total @ 11 (42 bytes)   made not entrant\n163  127       4       Phases::total (42 bytes)\n\n# hotspot_pid<N>.log\n<uncommon_trap reason=\'class_check\' action=\'maybe_recompile\' compile_id=\'39\' compiler=\'c2\' level=\'4\'>\n<jvms bci=\'27\' method=\'Phases total ([LShape;)D\' .../>' } },
    { h: 'Guards' },
    { mini: { scene: 'Guards' } },
    { table: { head: ['assumption', 'guard', 'trap reason in the log'], rows: [['this call site only sees `Circle`', 'class check', '`class_check` (`bimorphic_or_optimized_type_check` for two)'], ['this branch is never taken', 'the branch is compiled as a trap', '`unstable_if`'], ['this value is never null', 'implicit: a hardware fault (SIGSEGV) is caught', '`null_check`'], ['this index stays in bounds', 'check hoisted out of the loop', '`range_check`'], ['`Circle.area` is the only `Shape.area`', 'none in code: a **dependency** checked at class load', '`dependency_failed type=\'unique_concrete_method_4\'`']] } },
    { callout: { tone: 'pull', text: '**Loading a class can slow down code that was already fast.** A plugin, a lazily created implementation or a mock in a test can invalidate class hierarchy assumptions or add a receiver type. A C++ compiler must assume any subclass might exist; the JVM optimises for what is loaded now and undoes it when that changes.' } },
    { callout: { tone: 'violet', title: 'deeper: what deoptimisation reconstructs', text: 'C2 keeps a map (debug info) at every safepoint and trap: for each interpreter local and stack slot, where its value lives in the compiled frame (a register, a stack slot, a constant, or a scalar-replaced object to re-materialise). Deoptimisation walks that map to rebuild one interpreter frame per inlined method, so even objects that escape analysis deleted get allocated for real at that moment.' } },
  ] },
  { ch: 7, blocks: [
    { mini: { scene: 'OtherOpts' } },
    { table: { head: ['optimisation', 'what it does'], rows: [['loop unrolling', 'several iterations per pass, fewer loop tests and jumps (`LoopUnrollLimit`)'], ['range-check elimination', 'prove the index stays in bounds and check once before the loop (loop predication)'], ['lock elision', 'remove locks on non-escaping objects'], ['lock coarsening', 'merge neighbouring lock/unlock pairs on the same object'], ['constant folding', 'evaluate constant expressions at compile time'], ['loop-invariant hoisting', 'move work that does not change per iteration out of the loop'], ['null-check elimination', 'drop checks it can prove redundant, use implicit checks for the rest'], ['dead code elimination', 'delete computations whose result is unused: ⚠️ what destroys naive benchmarks']] } },
    { callout: { tone: 'violet', title: 'deeper: dead code is not always removable', text: 'DCE only deletes code with no side effects. In our JMH experiments a loop calling `s.area()` through an interface was **not** removed even when its result was unused: the inlined type guard can trap, and a trap is a side effect. A pure arithmetic loop with a constant trip count was removed completely.' } },
  ] },
  { ch: 8, blocks: [
    { mini: { scene: 'NaiveBench' } },
    { tryit: { note: 'Naive.java: 10 million calls to `area(i)` per loop, timed with `System.nanoTime()`.', cmd: '$ java Naive', out: 'round 1: ignored   3.328 ms   used  12.639 ms   (sum=1.047e+21)\nround 2: ignored  12.309 ms   used  11.185 ms   (sum=1.047e+21)\nround 3: ignored   0.000 ms   used  12.276 ms   (sum=1.047e+21)\nround 4: ignored   0.000 ms   used  10.594 ms   (sum=1.047e+21)\nround 5: ignored   0.000 ms   used  10.727 ms   (sum=1.047e+21)' } },
    { table: { head: ['problem', 'effect'], rows: [['no warm-up', 'you measured the interpreter and C1, not C2'], ['dead code elimination', 'an unused result lets the JIT delete the work: you timed an empty loop'], ['constant folding', 'constant inputs are computed once, at compile time'], ['on-stack replacement', 'loops inside `main` run OSR code, optimised differently from normal calls'], ['GC interference', 'one collection in the middle skews everything'], ['profile pollution', 'earlier code changes call-site profiles for later code (see Call sites)']] } },
    { h: 'JMH' },
    { mini: { scene: 'Jmh' } },
    { code: '@BenchmarkMode(Mode.AverageTime)\n@OutputTimeUnit(TimeUnit.NANOSECONDS)\n@Warmup(iterations = 5, time = 1)\n@Measurement(iterations = 5, time = 1)\n@Fork(3)\n@State(Scope.Benchmark)\npublic class AreaBench {\n    static double area(double r) { return Math.PI * r * r; }\n\n    @Benchmark\n    public void ignored() {\n        for (int i = 0; i < 1000; i++) area(i);              // results unused\n    }\n\n    @Benchmark\n    public double returned() {\n        double sum = 0;\n        for (int i = 0; i < 1000; i++) sum += area(i);\n        return sum;                                          // JMH consumes it\n    }\n\n    @Benchmark\n    public void blackhole(Blackhole bh) {\n        for (int i = 0; i < 1000; i++) bh.consume(area(i));  // every result consumed\n    }\n}', title: 'AreaBench.java' },
    { tryit: { note: 'JMH 1.37 jars from Maven Central, compiled with its annotation processor (abridged).', cmd: '$ javac -cp "$CP" -processorpath "$CP" -d out AreaBench.java\n$ java -cp "$CP:out" org.openjdk.jmh.Main bench.AreaBench', out: '# JMH version: 1.37\n# VM version: JDK 17.0.17, OpenJDK 64-Bit Server VM, 17.0.17+0\n# Blackhole mode: compiler (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)\n...\nBenchmark            Mode  Cnt    Score    Error  Units\nAreaBench.blackhole  avgt   15  241.969 ±  2.087  ns/op\nAreaBench.ignored    avgt   15    0.642 ±  0.068  ns/op\nAreaBench.returned   avgt   15  938.996 ± 56.728  ns/op' } },
    { list: ['**Forks** a fresh JVM per benchmark (here 3), so profiles and compiled code don\'t leak between benchmarks.', '**Warm-up** iterations run and are discarded before measurement.', 'Consumes **return values**, and `Blackhole.consume` for several values, so results are never dead.', 'Reads inputs from **`@State`** fields so they can\'t be constant-folded.', 'Reports **error bars** across forks and iterations.'] },
    { callout: { tone: 'pull', title: 'read results critically', text: '`ignored` is 0.642 ns for 1,000 calls: deleted, because the benchmark threw its results away. `returned` (939 ns) is one chain of 1,000 dependent floating-point additions, about 3 cycles each, while `blackhole` (242 ns) consumes independent results the CPU can overlap. Both are honest; they answer different questions.' } },
  ] },
  { ch: 9, blocks: [
    { mini: { scene: 'Graal' } },
    { p: '**Graal** is an optimising JIT written in Java that plugs into HotSpot through **JVMCI** (the JVM Compiler Interface) and replaces C2 at tier 4. It is often better on abstraction-heavy code (aggressive inlining, partial escape analysis for streams and lambdas) and sometimes worse on warm-up or some numeric loops.' },
    { tryit: { note: 'On stock OpenJDK 17 the flags are accepted, but there is no compiler behind them.', cmd: '$ java -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler Escape', out: 'Cannot use JVMCI compiler: No JVMCI compiler found' } },
    { callout: { tone: 'bad', title: 'correction to the source note', text: 'The note presents `-XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler` as the way to use Graal. JDK 17 removed the experimental Graal JIT from OpenJDK builds (JEP 410). JVMCI is still there, so the flags are accepted, but you need a **GraalVM** JDK (where Graal is already the default top-tier JIT) or Graal supplied separately.' } },
    { callout: { tone: 'flow', text: 'Distinct from **GraalVM native image** (8.10), which compiles ahead of time and has no JIT at runtime. Same project, opposite ends.' } },
  ] },
];

const traps = [
  'Benchmarking with `System.nanoTime()` measures the interpreter, C1, or a loop the JIT deleted. Use **JMH**, and return or `Blackhole.consume` every result.',
  '"Interfaces are slow": one or two receiver types at a call site are inlined behind a class check, as fast as a direct call.',
  '"Getters cost a method call": a getter is 5 bytes of bytecode and always inlined.',
  '"Small methods are slower": the opposite. Small methods get inlined; a huge method stays a call and blocks optimisation around it.',
  'Java is not "slow because it is interpreted": only until C2 compiles the hot code, typically within milliseconds to seconds.',
  'Performance is not fixed once warm: a newly loaded class can **deoptimise** hot code, and a third receiver type makes a site megamorphic.',
  'A 10,000-iteration loop is not enough for OSR with default settings: tier 3 OSR needs more than 60,000 back-edges.',
];

const recap = [
  '**Tiered**: interpreter (0) → C1 with profile (3) → C2 (4). Thresholds ≈ 200 calls / ≈ 5,000 calls, plus back-edge rules.',
  '**Counters**: invocations `i` and back-edges `b`; checked every 128 calls / 1,024 back-edges.',
  '**OSR**: long loops are compiled with a loop-header entry and swapped in mid-loop (> 60,000 back-edges).',
  '**Inlining**: the enabler for everything else. ≤ 35 bytes always a candidate, ≤ 325 if hot. Tiny methods are free.',
  '**Escape analysis**: non-escaping objects are scalar-replaced (no allocation); locks on them are removed.',
  '**Call sites**: monomorphic and bimorphic → inlined; megamorphic (3+) → a real dispatch via inline cache / vtable stub.',
  '**Deoptimisation**: speculate, guard, undo. Traps (`class_check`, `unstable_if`…) and class-load dependencies.',
  '**JMH**: forks, warm-up, consumed results, `@State` inputs, error bars. The only sound way to microbenchmark Java.',
  '**Graal**: a JIT written in Java via JVMCI; on JDK 17+ get it from GraalVM.',
];

const quiz = [
  { q: 'A method is called exactly once, but it contains a loop that runs 5 million times. How can it ever run as compiled code?', options: ['It can\'t: compilation is triggered only by invocation counts', 'On-stack replacement: the back-edge counter triggers a compile with a loop-header entry, and the running frame is moved into it', 'The interpreter recompiles each iteration', 'javac compiled the loop to machine code ahead of time'], answer: 1, why: 'The back-edge counter crosses ≈ 60,000 (tier 3) and the JVM compiles an OSR version entered at the loop header (`@ bci` in PrintCompilation, marked `%`). The interpreter frame\'s locals are copied into it mid-loop.' },
  { q: 'Your benchmark loop calls `hash(input)` 10 million times and ignores the result. After warm-up it reports 0.000 ms. What did you measure?', options: ['hash() is extremely fast thanks to the CPU cache', 'Nothing: C2 saw the result was unused and deleted the calls (dead code elimination)', 'Only the interpreter', 'The cost of System.nanoTime()'], answer: 1, why: 'An unused, side-effect-free result is dead code. Our Naive.java showed exactly this: 0.000 ms for 10 million calls. Return the result (JMH consumes it) or use `Blackhole.consume`.' },
  { q: 'Why is an interface call with exactly one loaded implementation as fast as a direct call, and what happens when a second implementation starts arriving at that call site?', options: ['Interfaces are compiled to static calls by javac; nothing changes', 'C2 inlines the single implementation behind a class check; when a second type fails the check, the code deoptimises and is recompiled as bimorphic (both inlined)', 'The JVM caches the vtable slot; the second type slows every call permanently', 'It is only fast in the interpreter'], answer: 1, why: 'The type profile drives speculative inlining. A failed class check is an uncommon trap (`class_check`); the JVM deoptimises, re-profiles, and C2 recompiles with both types inlined. A third type makes the site megamorphic.' },
  { q: 'What does `made not entrant` mean in `-XX:+PrintCompilation` output?', options: ['The method threw an exception', 'That compiled version may not be entered by new calls; existing frames may finish, and calls go to a newer version or the interpreter', 'The method is too big to compile', 'The method was inlined everywhere so its code was deleted'], answer: 1, why: 'It appears when a lower tier is superseded (e.g. tier 3 after tier 4 is installed) or after a deoptimisation. The code is retired for new entries, not instantly freed.' },
  { q: 'Why does inlining matter far more than the call overhead it saves?', options: ['Calls are extremely expensive on modern CPUs', 'Inlining puts caller and callee into one compiled body, so escape analysis, constant folding, CSE and loop optimisations can see across the old call boundary', 'Inlined methods use less memory', 'It lets the garbage collector skip the frame'], answer: 1, why: 'Almost every optimisation works within one compiled body. Escape analysis of `new Point(...)` needs the constructor and accessors inlined; `s.r * s.r` can share one load only once `area` is inside the loop.' },
  { q: 'A hot method calls a 484-byte helper. PrintInlining says `hot method too big`. What is the consequence?', options: ['The helper is never compiled', 'The call stays a real call: C2 cannot optimise the caller\'s code through it, and objects passed to it escape', 'The JVM splits the helper automatically', 'Nothing: size limits only apply to C1'], answer: 1, why: 'Above `FreqInlineSize` (325 bytes) the callee is compiled separately and called. The caller loses context: values passed in are ArgEscape, and nothing is optimised across the call. Splitting large methods can genuinely speed code up.' },
  { q: '`distance()` creates two `Point` records per call. With escape analysis on it allocates 216 bytes over 100 million calls; with `-XX:-DoEscapeAnalysis` it allocates 6.4 GB. What did C2 do?', options: ['Allocated the Points on the stack', 'Pooled and reused two Point objects', 'Scalar replacement: after inlining, it proved the Points never escape and replaced their fields with local values, deleting the allocations', 'Moved the Points into metaspace'], answer: 2, why: 'HotSpot does not stack-allocate; it scalar-replaces NoEscape objects. Store one Point in a static field and it escapes: our run then allocated 3.2 GB (only that Point).' },
  { q: 'A call site in a hot loop has seen `Circle`, `Square` and `Triangle` in roughly equal numbers. What does C2 typically generate there?', options: ['Three inlined bodies in an if/else chain', 'A virtual call through an inline cache / vtable or itable stub: no inlining', 'An uncommon trap on every call', 'A call to the interpreter'], answer: 1, why: 'With `TypeProfileWidth=2`, three types make the site megamorphic. Unless one type is ≥ 90% (`TypeProfileMajorReceiverPercent`), C2 emits a real dispatch: `Shape::area (0 bytes) virtual call`, measured at 3.65 ns vs ~1 ns per call.' },
  { q: 'Production code was fast for hours. Then a plugin loads a new subclass, and the hot path gets slower for a while. Why?', options: ['Class loading pauses all threads permanently', 'Compiled code depended on class-hierarchy assumptions (e.g. a unique implementation); loading the subclass invalidated them and deoptimised the dependent methods', 'The plugin used more heap', 'New classes are always interpreted'], answer: 1, why: 'C2 records dependencies such as "Circle.area is the only Shape.area". When a class loads that breaks one (`dependency_failed` in the log), every method relying on it is deoptimised and must re-profile and recompile.' },
  { q: 'In JMH, `returned()` (sum 1,000 areas, return the sum) took 939 ns, while `blackhole()` (consume each area) took 242 ns. Which explanation is right?', options: ['Blackhole is broken and skips work', '`returned` is one chain of 1,000 dependent additions, each waiting for the previous one; the blackhole version consumes independent results the CPU can overlap', 'JMH measured returned in the interpreter', 'The difference is GC'], answer: 1, why: 'Both measurements are sound; they ask different questions. A loop-carried floating-point sum is latency-bound (≈ 3 cycles per add on this CPU ≈ 0.94 µs for 1,000). JMH ensures the work happens; you still have to know what work you wrote.' },
];

window.AN.registerTopic({
  id: '8.8', part: '08', title: 'JIT compilation', kicker: 'Part 08 · The JVM',
  lede: 'The most under-appreciated part of the platform, and the reason naive benchmarks lie. Watch one loop climb from the interpreter to C2, get inlined, lose its allocations, lose a bet, and get recompiled.',
  chapters, scenes, captions, notes, traps, recap, quiz,
});
