// Topic 8.9 — Observing a running JVM. Source notes: Part-08-The-JVM/8.9-observing-a-running-jvm.md
// Every terminal line is real JDK 17.0.17 output (macOS/AArch64, 8 GB) from the Shop demo: see 8.9/data.jsx.
import { SIntro, SAttach, SAttachMech, SDumpAnatomy, SStates, SDeadlock, SDeadlockDetect, SThreeDumps } from './8.9/scenes1.jsx';
import { SJstat, SHistogram, SRetained, SDominators, SHeapDump } from './8.9/scenes2.jsx';
import { SJfrRing, SJfrCommands, SInstrument, SSafepointBias, SFlameBuild, SFlameRead } from './8.9/scenes3.jsx';
import { SFlags, SJmx, SNmt, SPlaybook, STraps, SRecap } from './8.9/scenes4.jsx';

const chapters = ['Intro', 'Attaching', 'Thread dumps', 'GC statistics', 'Heap analysis', 'Flight Recorder', 'Profilers', 'Flags & JMX', 'Native memory', 'Playbook', 'Traps', 'Recap'];

const scenes = [
  { name: 'Intro', dur: 24, ch: 0, title: '', C: SIntro },
  { name: 'Attach', dur: 52, ch: 1, title: 'Find the JVM, then ask what it can do', C: SAttach },
  { name: 'AttachMech', dur: 46, ch: 1, title: 'How jcmd gets inside a JVM it didn’t start', C: SAttachMech },
  { name: 'DumpAnatomy', dur: 58, ch: 2, title: 'Reading a thread dump, line by line', C: SDumpAnatomy },
  { name: 'States', dur: 46, ch: 2, title: 'Thread states, and the lines that come with them', C: SStates },
  { name: 'Deadlock', dur: 58, ch: 2, title: 'Spotting a deadlock by eye', C: SDeadlock },
  { name: 'DeadlockDetect', dur: 42, ch: 2, title: 'What the built-in detector can see', C: SDeadlockDetect },
  { name: 'ThreeDumps', dur: 46, ch: 2, title: 'One dump is a photo. Three are a film.', C: SThreeDumps },
  { name: 'Jstat', dur: 56, ch: 3, title: 'jstat: the GC’s heartbeat', C: SJstat },
  { name: 'Histogram', dur: 48, ch: 4, title: 'GC.class_histogram: run it twice', C: SHistogram },
  { name: 'Retained', dur: 56, ch: 4, title: 'Shallow size vs retained size', C: SRetained },
  { name: 'Dominators', dur: 56, ch: 4, title: 'The dominator tree and the path to GC roots', C: SDominators },
  { name: 'HeapDump', dur: 46, ch: 4, title: 'Taking a heap dump, and getting one for free', C: SHeapDump },
  { name: 'JfrRing', dur: 56, ch: 5, title: 'JFR: a flight recorder inside the JVM', C: SJfrRing },
  { name: 'JfrCommands', dur: 54, ch: 5, title: 'Recording, then reading', C: SJfrCommands },
  { name: 'Instrument', dur: 48, ch: 6, title: 'Two ways to profile', C: SInstrument },
  { name: 'SafepointBias', dur: 60, ch: 6, title: 'Where the samples land', C: SSafepointBias },
  { name: 'FlameBuild', dur: 54, ch: 6, title: 'Building a flame graph from samples', C: SFlameBuild },
  { name: 'FlameRead', dur: 48, ch: 6, title: 'Reading Shop’s flame graph', C: SFlameRead },
  { name: 'Flags', dur: 48, ch: 7, title: 'What did the JVM actually choose?', C: SFlags },
  { name: 'Jmx', dur: 44, ch: 7, title: 'JMX: the JVM as an API', C: SJmx },
  { name: 'Nmt', dur: 54, ch: 8, title: 'Memory the heap doesn’t explain', C: SNmt },
  { name: 'Playbook', dur: 58, ch: 9, title: 'The triage playbook', C: SPlaybook },
  { name: 'Traps', dur: 38, ch: 10, title: 'Traps', C: STraps },
  { name: 'Recap', dur: 36, ch: 11, title: 'Recap', C: SRecap },
];

const captions = {
  Intro: [[0.8, "Production is slow. You can't restart it, and you can't add logging. Now what?"], [6.5, 'Meet `Shop`, a tiny service with three bugs: it freezes, it leaks, and it burns CPU.'], [13, 'Each one can be diagnosed from outside, on the live process, with tools that ship in the JDK.'], [18.5, "We'll investigate all three, and see what each tool is really showing you."]],
  Attach: [[0.5, 'Step one: find the process. `jps` lists every JVM running as your user.'], [6.5, '`-l` shows the main class, `-v` the JVM flags, `-m` the program arguments. Our `Shop` is pid 6498.'], [13.5, 'Step two: ask that JVM what it can do. `jcmd 6498 help`.'], [19, 'The answer is a menu of diagnostic commands built into the JVM. JDK 17 lists 47 of them.'], [26, 'They group by prefix: threads, GC and heap, VM internals, the flight recorder, the JIT, JMX.'], [33, 'The older single-purpose tools still work, but `jcmd` does what they do.'], [40.5, 'Only `jstat` has no `jcmd` twin. It stays useful for live GC numbers.'], [46, 'So the habit is: `jps`, then `jcmd <pid> help`, then pick the command.']],
  AttachMech: [[0.5, 'How can a separate program reach inside a running JVM? Through the **attach mechanism**.'], [5.5, 'First, `jcmd` creates an empty trigger file, `.attach_pid6498`, in the temp directory.'], [11, 'Then it sends the JVM a `SIGQUIT` signal: the same signal as `kill -3`.'], [16, "The JVM's Signal Dispatcher sees the trigger file, and starts an **Attach Listener** thread."], [22.5, 'The listener opens a Unix socket. `jcmd` connects and sends its command as plain text.'], [28.5, 'The command runs inside the JVM. Thread and heap commands need a safepoint: a brief pause of every thread.'], [35.5, 'The evidence is in our dump: the Attach Listener is 0.18 s old. `main` is 7 s old.'], [41, 'No trigger file? Then `kill -3` simply prints a thread dump to the JVM\'s own stdout.']],
  DumpAnatomy: [[0.5, 'Here is one real thread from `jcmd 6498 Thread.print`. JDK 17 output, nothing edited.'], [6, 'The first line is the header. The name comes first: `checkout`. Naming your threads pays off right here.'], [12.5, "`cpu=` is CPU time used; `elapsed=` is the thread's age. 0.55 ms in 7 seconds: it's idle."], [20, "`nid` is the operating system's thread id, in hex. It links a hot thread in `top -H` to its stack."], [27, 'Then the state: `BLOCKED (on object monitor)`. Now read the stack from the top.'], [33, 'The top frame is where the thread is right now: `Shop.checkout`, line 11.'], [38.5, '`waiting to lock <…c878>`: it wants a monitor that someone else holds.'], [44.5, '`locked <…c868>`: it already holds this one, taken earlier in the same method, at line 9.'], [51, 'Holding one lock while waiting for another. Keep that picture in mind.']],
  States: [[0.5, 'Every thread is in one of a few states, and each state comes with its own telltale line.'], [5.5, '`BLOCKED`: waiting to enter a `synchronized` block. The line says `waiting to lock`.'], [12, "`WAITING`: parked with no timeout, in `wait()`, `join()` or `park()`. You'll see `waiting on`."], [19.5, 'A `ReentrantLock` waiter is `WAITING (parking)`, not `BLOCKED`. Same problem, different words.'], [26, '`TIMED_WAITING`: the same, with a timeout. `Thread.sleep` shows up as `(sleeping)`.'], [32, "`RUNNABLE` is the tricky one. It means running, or inside native code the JVM can't see into."], [38.5, "This `RUNNABLE` thread has used 0.12 ms of CPU in 7 s. It's waiting in native code. Read `cpu=`, not the state."]],
  Deadlock: [[0.5, 'Now the deadlock. `checkout` locks the inventory, then the ledger. `refund` locks them in the opposite order.'], [8, '`checkout` takes INVENTORY. At the same moment, `refund` takes LEDGER.'], [14, 'Both pause briefly. Then `checkout` asks for LEDGER, held by `refund`. It blocks.'], [20, '`refund` asks for INVENTORY, held by `checkout`. It blocks too.'], [26, 'Draw it as a graph: an arrow from each thread to the lock it wants, and from each lock to its owner.'], [33, 'The arrows form a cycle. Every thread in it waits for the next one. None can ever move.'], [39.5, "In the dump, match the addresses: each thread's `waiting to lock` is the other's `locked`."], [46, 'You rarely need to do it by hand. The JVM runs this cycle check itself, and prints the result at the end.'], [53, 'So when a JVM is frozen: thread dump, then scroll straight to the bottom.']],
  DeadlockDetect: [[0.5, 'How does the JVM find the cycle? It walks from each blocked thread to the lock it wants, then to that lock\'s owner.'], [7.5, "If the walk returns to a thread it already visited, that's a deadlock. It needs every lock to know its owner."], [14.5, '`synchronized` monitors know their owner. So does `ReentrantLock`: here is a real deadlock between two of them.'], [22, 'The dump says `waiting for ownable synchronizer`, and still reports `Found one Java-level deadlock`.'], [28.5, 'A `Semaphore` or a `CountDownLatch` has no owner, so cycles through them are invisible. So are database locks.'], [35.5, 'For those, read the dump yourself: many threads parked on the same object is your clue.']],
  ThreeDumps: [[0.5, 'One thread dump is a single photo. A thread caught in a method might just be passing through.'], [6, 'So take three, about ten seconds apart. Here are three real dumps of `Shop`, running all three bugs at once.'], [13, "`checkout`: the same line, all three times, and its CPU time barely moves. It's stuck."], [20.5, "`http-worker-1`: a different frame each time, and 19 seconds of CPU in 20. It's busy, and it's hot."], [28.5, '`login-handler` sleeps each time, but its CPU creeps up. It wakes, works briefly, sleeps: healthy.'], [35.5, 'Same frame plus flat CPU means stuck. A moving frame means busy. Busy and hot means profile it.'], [41, "For a slow service with low CPU, that's the first move: three dumps, and look for what doesn't move."]],
  Jstat: [[0.5, '`jstat -gcutil <pid> 1000` prints one line of GC statistics every second. This is the leaking `Shop`.'], [7, '`S0`, `S1`, `E` and `O`: how full the two survivor spaces, eden and the old generation are, in percent.'], [13.5, "Eden fills with new objects; a young GC empties it. That's the sawtooth. `YGC` counts them."], [20, '`O` is the old generation: objects that survived. Sessions nobody frees get promoted here.'], [27, 'The red marks are full GCs, and we caused them: `GC.class_histogram` collects before it counts.'], [33.5, 'But in percent, old gen keeps dropping back to about 60 %. It looks almost stable.'], [40, 'Ask `jstat -gc` for sizes instead: old-gen usage climbs from 0 to 391 MB. The capacity grew, so the percentage hid it.'], [48, 'Left alone, it ends like this: old gen 99.9 %, 17 full GCs, then `OutOfMemoryError`.']],
  Histogram: [[0.5, 'The fastest leak check: `jcmd <pid> GC.class_histogram`. Instance counts and bytes, per class.'], [6.5, 'One snapshot tells you little: byte arrays and strings top every histogram. So take a second one.'], [12.5, 'Twenty seconds later, `Shop$Session` has gone from 216,000 to 600,000. Whatever keeps growing is the leak.'], [20, 'Notice what grows with it, in lockstep: one HashMap node, one Long and one String per session.'], [27.5, "And two byte arrays: each session's cart, plus the bytes inside its user-name String."], [34, "Divide bytes by instances: 32 bytes per Session. That's **shallow** size: the object alone."], [40.5, 'One cost to know: without `-all`, the histogram runs a full GC first. On a big heap that pause is real.']],
  Retained: [[0.5, 'Here is what one login leaves behind. Each box shows its shallow size.'], [7, 'A static field, `SESSIONS`, points to a HashMap. The map holds a table of nodes; each node, a key and a Session.'], [14.5, 'Retained size asks a different question: if this object disappeared, how much memory would be freed?'], [21, 'Remove a Session and its name String, the String\'s bytes and the cart all go with it. Retained: 304 bytes.'], [28.5, 'Remove the map node and its Long key goes too: 360 bytes per login.'], [35, 'Now the HashMap itself. Shallow size: 48 bytes. Retained: every node and every session, about 220 MB.'], [43, "Sorted by shallow size, the map is invisible. Sorted by retained size, it's row one."]],
  Dominators: [[0.5, 'Real heaps share objects, so "what would be freed" needs care. Take this small graph.'], [6, 'Ask: if `A` disappeared, what would become unreachable?'], [11, '`E` dies with it. But `C` survives, because `B` still reaches it. So `A` retains only itself and `E`.'], [18.5, 'We say `A` **dominates** `E`: every path from a GC root to `E` goes through `A`. Nothing but the roots dominates `C`.'], [26.5, 'Hang each object under its closest dominator, and you get the **dominator tree**.'], [32.5, "An object's retained size is just the total of its subtree. Heap analysers compute this for millions of objects."], [40.5, 'Then, for a suspect Session, ask for its **path to GC roots**.'], [46.5, 'Node, table, HashMap, the static field `SESSIONS`, class `Shop`. The path names the bug: a static map nobody clears.']],
  HeapDump: [[0.5, 'For the full picture, take a heap dump: every live object and every reference, written to a file.'], [6.5, '`GC.heap_dump` writes only live objects by default, so it runs a full GC first. `-all` keeps the garbage too.'], [13.5, 'The application is paused while the file is written: here, 275 MB in 1.1 seconds. Plan for the disk space.'], [21, 'Better still, let the JVM dump itself at the worst moment: `-XX:+HeapDumpOnOutOfMemoryError`.'], [27.5, 'It costs nothing until the OOM. Then you get the one file that explains it: 1.27 GB, written in 3 seconds.'], [34.5, 'Open it in Eclipse MAT, VisualVM or IntelliJ. Sort by retained size. Follow the path to GC roots.'], [40.5, 'Static collections, `ThreadLocal`s and forgotten listeners: the usual names at the end of that path.']],
  JfrRing: [[0.5, 'JDK Flight Recorder is built into the JVM. It records **events**: small timestamped facts about what happened.'], [7, 'A stack sample every 10 or 20 ms. Each GC pause. Allocations, lock waits, sleeps, I/O, exceptions, JIT work.'], [14.5, "Each thread writes events into its own buffer. No lock, no I/O: that's how the overhead stays near 1 %."], [21.5, 'Full buffers move to global buffers, and a background thread writes them to disk in chunks.'], [28.5, "Disk use is capped by `maxsize` or `maxage`. When it's full, the oldest chunk is dropped: a rolling window."], [36, "Like an aircraft's recorder, it's always running. After an incident, you dump the last stretch to a file."], [43, '`default` settings cost under 1 %: safe to leave on in production. `profile` records more, at around 2 %.'], [49.5, 'Open source since JDK 11 and free ever since. It may be the most useful tool on this page.']],
  JfrCommands: [[0.5, 'Attach to the running `Shop` and start a recording. No restart.'], [6, '`JFR.start` with `settings=profile`. With no limit given, it caps the recording at 250 MB.'], [12, "Let it run while the problem happens. `JFR.dump` copies what's recorded so far into a file."], [18.5, "`jfr summary` lists what's inside: 21 seconds, and a count per event type."], [25, '1,580 execution samples: stacks of the busy thread, about one every 13 ms.'], [31.5, '`jfr print` shows each event in full. JDK Mission Control or IntelliJ draws them as charts and flame graphs.'], [39, 'You can also record from launch: `-XX:StartFlightRecording`, with a duration and a file name.'], [46, 'Newer JDKs add `jfr view` and `jfr scrub` (21), and in 25 a CPU-time sampler for Linux, plus method tracing.']],
  Instrument: [[0.5, 'There are two ways to profile a program, and they fail in different ways.'], [5, 'An **instrumenting** profiler injects timing code at the start and end of every method.'], [11.5, 'For a tiny getter, the probes cost far more than the work. Worse, the JIT can no longer inline it.'], [19, 'So methods that were free now look expensive, and people "optimise" getters. Overall: 2 to 10× slower.'], [27, "A **sampling** profiler leaves the code alone. Every few milliseconds, it captures each running thread's stack."], [34, "Count where the samples land. It's statistical, not exact, but cheap enough for production."], [41.5, 'Exact counts for a narrow local question; sampling for everything else. But where do samples really land?']],
  SafepointBias: [[0.5, 'A sampler stops a thread and asks: where are you? The answer depends on where it can stop.'], [7, 'Here is one pass through `serve`, drawn as time. Each tick marks a moment the profiler wants a sample.'], [13, 'Many classic profilers wait for a **safepoint** before reading a stack: polls at calls and loop back-edges.'], [19.5, "So each sample slides to the next poll. `query`'s hot loop has no poll inside, so its time is blamed on `toJson`."], [26.5, "That's **safepoint bias**. JFR and async-profiler don't wait for safepoints, but a subtler version remains."], [33.5, 'Compiled code only records where it is at calls and polls. A sample in between gets the nearest record.'], [41, 'Real JFR data from `Shop`, JDK 17: `query` gets zero samples, and `toJson` gets 474.'], [48, 'Add `-XX:+DebugNonSafepoints` and the JIT records more: now `query` gets 347, and `toJson` just 38.'], [54.5, "Same program, opposite conclusions. Use that flag whenever you profile; async-profiler's docs say so too."]],
  FlameBuild: [[0.5, "A sampling profiler's raw output is a pile of stacks. Here are eight, drawn bottom to top. An illustration."], [7, 'In time order it looks like noise: the same stacks scattered everywhere.'], [12.5, 'Step one: sort the samples alphabetically, frame by frame, so identical stacks sit side by side.'], [19.5, "Step two: merge neighbouring boxes with the same name. Each box's width is now its sample count."], [27, '`serve` is in all 8 samples. `render` in 5, `handle` in 3. `format` alone in 4: half the time.'], [34.5, "That's a flame graph. The x-axis is not time: left to right is just alphabetical order."], [41.5, 'Width is the share of samples. Height is only stack depth.'], [47.5, 'The part of a box with nothing on top is time spent in that method itself: its **self time**.']],
  FlameRead: [[0.5, "Now real data: `Shop`'s busy worker, 1,333 JFR samples, drawn as a flame graph. `Shop` frames only."], [7.5, 'Start at the bottom: almost every sample passes through `serve`, so it spans the width.'], [13.5, '`render` holds 72 % of the samples, `handle` 28 %.'], [19.5, 'Look for wide boxes near the top. `format` alone holds 68 %: two thirds of a core spent in `String.format`.'], [27, "`query` is the other plateau: 26 %, all self time. `parse` and `toJson` are slivers: don't bother with them."], [34, "Tall, thin towers are just deep call chains. They don't matter unless they're wide."], [40.5, 'So the fix starts in `format`: build that string without `String.format` in the hot path.']],
  Flags: [[0.5, '"What heap size is it actually using?" `-XX:+PrintFlagsFinal` prints every flag and its final value.'], [6.5, 'Each line: a type, the flag, its value, its kind, and at the end, where that value came from.'], [12.5, '`{ergonomic}` means the JVM chose it by looking at the machine. `MaxHeapSize` is 2 GB here.'], [19, 'Why 2 GB? `MaxRAMPercentage` defaults to 25 %, and this machine has 8 GB. In a container, the limit counts.'], [26.5, 'Set `-Xmx512m` and the origin changes to `{command line}`.'], [32, "For a JVM that's already running, `jcmd <pid> VM.flags` shows the flags in effect."], [38.5, 'A few flags are `manageable`: `VM.set_flag` changes them live. `HeapDumpOnOutOfMemoryError` is one. Heap size is not.']],
  Jmx: [[0.5, "Everything you've seen is also available from inside the JVM, through **JMX** and its MBeans."], [6.5, '`ManagementFactory` hands out the platform MXBeans: memory, threads, garbage collectors, runtime.'], [13, 'This program asks for its heap usage, then runs the same deadlock check the thread dump uses.'], [20, 'Real output: `checkout` waits for a lock held by `refund`, and the reverse. Detected in code.'], [27.5, "JConsole, VisualVM and Mission Control connect over a JMX port. Secure it: it's remote control."], [34.5, 'Most teams export these numbers continuously instead, with Micrometer and Prometheus.'], [39.5, 'Forgot to open the port? `jcmd <pid> ManagementAgent.start` turns it on in a running JVM.']],
  Nmt: [[0.5, 'The heap is capped at 1 GB, yet the process holds more. Where does the rest go? **Native Memory Tracking**.'], [7, 'Start the JVM with `-XX:NativeMemoryTracking=summary`, then ask: `jcmd <pid> VM.native_memory summary`.'], [13.5, 'Two numbers per area. **Reserved** is address space set aside. **Committed** is memory actually backed.'], [20.5, 'The heap: 1 GB reserved, 527 MB committed so far. Class space reserves another gigabyte, and commits 128 KB of it.'], [28.5, 'Threads: 33 of them, about 2 MB of stack each on this Mac. On Linux the default is 1 MB. A thousand threads add up.'], [36, "The GC's own bookkeeping: 70 MB here. The code cache holds compiled methods; metaspace, class metadata."], [43, 'Take a `baseline`, wait, then `summary.diff`: whichever area grows is your native leak.'], [49, "Memory malloc'ed by native libraries isn't tracked. If NMT's total is far below RSS, look there."]],
  Playbook: [[0.5, 'Put it together as a playbook: from the symptom you see, to the first command you run.'], [6, 'Slow and CPU high: profile. JFR or async-profiler, then a flame graph. That found `format` in `Shop`.'], [13, 'Slow but CPU low: threads are waiting on something. Three thread dumps, ten seconds apart.'], [19.5, 'Frozen: one thread dump, scroll to the bottom. That found `checkout` and `refund`.'], [25.5, 'Memory growing: two class histograms, then a heap dump sorted by retained size. That found `SESSIONS`.'], [32, 'Already dead with an OOM: open the file from `HeapDumpOnOutOfMemoryError`.'], [37.5, 'Long pauses: GC logs. A pause much longer than the GC work means threads were slow to reach the safepoint.'], [45, 'Process far bigger than its heap: Native Memory Tracking. And to check settings: `VM.flags`.'], [51.5, 'Every one starts the same way: `jps`, `jcmd <pid> help`, pick the command. No restart, no code change.']],
  Traps: [[0.5, 'Five traps worth avoiding.'], [3.5, "One thread dump can't tell stuck from passing through. Take three."], [10, "`RUNNABLE` doesn't mean burning CPU. Native code and blocking I/O look the same. Check `cpu=`."], [16.5, 'Shallow size hides leaks. Sort heap dumps by retained size.'], [23, 'Profilers distort. Instrumenting breaks inlining; samplers misattribute without `DebugNonSafepoints`.'], [29.5, 'And add `HeapDumpOnOutOfMemoryError` before the OOM, not after. It costs nothing until it fires.']],
  Recap: [[0.5, 'Recap.'], [3, '`jps`, then `jcmd <pid> help`: the menu of everything this JVM can tell you.'], [9, 'Thread dumps: states and lock lines, three dumps, and the deadlock check at the bottom.'], [15, '`jstat` for the GC heartbeat, histograms twice, heap dumps sorted by retained size.'], [21, 'JFR always on; flame graphs read by width; `DebugNonSafepoints` for honest samples.'], [27, 'And `PrintFlagsFinal`, JMX and NMT for settings, live metrics and native memory.']],
};

const SHOP = `public class Shop {
    static final Object INVENTORY = new Object();
    static final Object LEDGER = new Object();

    static void checkout() {                       // lines 8–13
        synchronized (INVENTORY) {
            pause(100);
            synchronized (LEDGER) { System.out.println("checked out"); }
        }
    }
    static void refund() {                         // opposite lock order
        synchronized (LEDGER) {
            pause(100);
            synchronized (INVENTORY) { System.out.println("refunded"); }
        }
    }

    static class Session {
        final long id; final String user; final byte[] cart = new byte[200];
        Session(long id) { this.id = id; this.user = "user-" + id; }
    }
    static final Map<Long, Session> SESSIONS = new HashMap<>();
    static void login(long id) { SESSIONS.put(id, new Session(id)); }   // never removed

    static void serve(int i)   { handle(i); render(i); }               // http-worker-1 loops on this
    static void handle(int i)  { sink += parse(i); sink += query(i); }
    static int query(int i)    { int h = 0; for (int k = 0; k < 400; k++) h = h * 31 + (i ^ k); return h; }
    static void render(int i)  { sink += toJson(i).length(); sink += format(i).length(); }
    static String format(int i){ return String.format("order %08d total %.2f", i, i * 1.25); }
    // … parse, toJson, pause, main(mode): "deadlock" | "leak" | "cpu" | "all"
}`;

const notes = [
  { ch: 1, blocks: [
    { p: 'Everything in this topic works on a **live process**, with no restart, no code change and no agent. The running example is `Shop`, one small program with three bugs you can switch on: a lock-order **deadlock** (`checkout` vs `refund`), a **leak** (a static map of sessions that is never cleared) and a **CPU hog** (`http-worker-1` looping on `serve`).' },
    { code: SHOP, title: 'Shop.java (abridged)' },
    { mini: { scene: 'Attach' } },
    { tryit: { note: 'Start it, find it, ask it. (JDK 17 output; pids will differ.)', cmd: '$ java Shop deadlock &\n$ jps -l\n$ jcmd 6498 help', out: '6498 Shop\n6512 jdk.jcmd/sun.tools.jps.Jps\n6498:\nThe following commands are available:\nCompiler.CodeHeap_Analytics\n…\nGC.class_histogram\nGC.heap_dump\nGC.heap_info\n…\nThread.print\nVM.flags\nVM.native_memory\n…\nhelp' } },
    { table: { head: ['older tool', 'does', 'jcmd equivalent'], rows: [['`jstack <pid>`', 'thread dump', '`jcmd <pid> Thread.print`'], ['`jmap -histo <pid>`', 'class histogram', '`jcmd <pid> GC.class_histogram`'], ['`jmap -dump:live,file=h.hprof <pid>`', 'heap dump', '`jcmd <pid> GC.heap_dump h.hprof`'], ['`jinfo <pid>`', 'flags and properties', '`jcmd <pid> VM.flags` / `VM.system_properties`'], ['`jstat -gcutil <pid> 1s`', 'GC stats every second', 'none: still useful']] } },
    { p: '`jcmd <pid> help <command>` documents each command and its options, e.g. `Thread.print -l` (also list `java.util.concurrent` locks held) or `GC.heap_dump -all`.' },
    { h: 'The attach mechanism' },
    { mini: { scene: 'AttachMech' } },
    { steps: ['`jcmd` creates an empty trigger file `.attach_pid<pid>` (in the target\'s working directory or the temp directory).', 'It sends the target `SIGQUIT`.', 'The JVM\'s **Signal Dispatcher** thread sees the trigger file and starts the **Attach Listener** thread, which creates a Unix domain socket `.java_pid<pid>` in the temp directory.', '`jcmd` connects and sends the command name and arguments as text. The listener runs it (thread dumps, heap dumps and histograms as safepoint operations on the VM Thread) and streams the output back.'] },
    { callout: { tone: 'violet', title: 'deeper', text: 'Without a trigger file, `SIGQUIT` (`kill -3 <pid>`) makes HotSpot print a thread dump to its **own stdout**: handy when no JDK tools are installed in a container. Attaching requires the same OS user (and, in containers, the same PID namespace and `/tmp`). `-XX:+DisableAttachMechanism` turns attach off entirely. In our dump the Attach Listener was 0.18 s old while every other thread was 7 s old: it was created by the attach.' } },
  ] },
  { ch: 2, blocks: [
    { mini: { scene: 'DumpAnatomy' } },
    { code: '"checkout" #14 prio=5 os_prio=31 cpu=0.55ms elapsed=7.07s tid=0x0000000c3cd6cc00 nid=0x8003 waiting for monitor entry  [0x000000016e092000]\n   java.lang.Thread.State: BLOCKED (on object monitor)\n    at Shop.checkout(Shop.java:11)\n    - waiting to lock <0x0000000787f1c878> (a java.lang.Object)\n    - locked <0x0000000787f1c868> (a java.lang.Object)\n    at Shop$$Lambda$1/0x0000000801000a08.run(Unknown Source)\n    at java.lang.Thread.run(java.base@17.0.17/Thread.java:840)', lang: 'plain', title: 'jcmd 6498 Thread.print (one thread, JDK 17)' },
    { table: { head: ['field', 'means'], rows: [['`"checkout"`', 'thread name: name your threads and pools'], ['`#14`', 'Java thread id'], ['`cpu=0.55ms elapsed=7.07s`', 'CPU time used, and the thread\'s age (JDK 11+)'], ['`tid=0x…`', 'address of the JVM\'s internal thread object'], ['`nid=0x8003`', 'OS thread id in hex (32771): matches `top -H -p <pid>` on Linux'], ['`waiting for monitor entry`', 'what the VM thinks it is doing'], ['`- locked <0x…>`', 'this frame **holds** that monitor'], ['`- waiting to lock <0x…>`', 'this thread **wants** that monitor']] } },
    { callout: { tone: 'pull', title: 'correction to the note', text: 'The note shows `… nid=0x1e03 BLOCKED` on the header line. In real HotSpot output the header ends with the VM\'s description (`waiting for monitor entry`) and a stack address; the state appears on the next line, `java.lang.Thread.State: BLOCKED (on object monitor)`.' } },
    { h: 'Thread states' },
    { mini: { scene: 'States' } },
    { table: { head: ['state', 'means', 'line you will see'], rows: [['`RUNNABLE`', 'running, **or** in native code / blocking I/O', 'none: check `cpu=`'], ['`BLOCKED`', 'waiting to enter a `synchronized` block', '`- waiting to lock <…>`'], ['`WAITING`', '`wait()`, `join()`, `park()` with no timeout', '`- waiting on <…>` · `- parking to wait for <…>`'], ['`TIMED_WAITING`', 'the same with a timeout, or `sleep()`', '`(sleeping)` · `(on object monitor)` · `(parking)`']] } },
    { p: 'A `ReentrantLock` waiter is `WAITING (parking)` with `parking to wait for <…> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)`, never `BLOCKED`. In the real dump, the `Reference Handler` thread is `RUNNABLE` with `cpu=0.12ms` after 7 s: it is waiting inside a native method. That is exactly how a thread blocked on a socket read looks.' },
    { h: 'Deadlocks' },
    { mini: { scene: 'Deadlock' } },
    { tryit: { cmd: '$ java Shop deadlock &\n$ jcmd $(jps | awk \'$2=="Shop"{print $1}\') Thread.print | tail -12', out: 'Found one Java-level deadlock:\n=============================\n"checkout":\n  waiting to lock monitor 0x0000000c3d4340e0 (object 0x0000000787f1c878, a java.lang.Object),\n  which is held by "refund"\n\n"refund":\n  waiting to lock monitor 0x0000000c3d4341c0 (object 0x0000000787f1c868, a java.lang.Object),\n  which is held by "checkout"\n…\nFound 1 deadlock.' } },
    { mini: { scene: 'DeadlockDetect' } },
    { callout: { tone: 'bad', title: 'correction to the note', text: 'The note says the built-in detector does **not** detect `ReentrantLock` deadlocks. On JDK 17 it does: `ReentrantLock` and the write lock of `ReentrantReadWriteLock` extend `AbstractOwnableSynchronizer`, which records the owner thread, so the dump prints `waiting for ownable synchronizer 0x…, (a java.util.concurrent.locks.ReentrantLock$NonfairSync), which is held by "t2"` under **Found one Java-level deadlock**. What it cannot see: `Semaphore`, `CountDownLatch`, read locks, database locks, and threads waiting on each other through queues or futures.' } },
    { p: 'In code, `ThreadMXBean.findDeadlockedThreads()` covers monitors **and** ownable synchronizers; the older `findMonitorDeadlockedThreads()` covers monitors only.' },
    { h: 'Three dumps' },
    { mini: { scene: 'ThreeDumps' } },
    { table: { head: ['thread', 'dump 1 (0 s)', 'dump 2 (10 s)', 'dump 3 (20 s)', 'verdict'], rows: [['checkout', '`Shop.checkout:11` · cpu 0.25 ms', 'same · 0.39 ms', 'same · 0.53 ms', '**stuck**'], ['http-worker-1', '`Shop.toJson:34` · 2,254 ms', '`Shop.format:35` · 11,969 ms', '`Shop.toJson:34` · 21,638 ms', '**busy, hot**'], ['login-handler', '`Thread.sleep` · 26 ms', '`Thread.sleep` · 46 ms', '`Thread.sleep` · 65 ms', 'healthy']] } },
  ] },
  { ch: 3, blocks: [
    { mini: { scene: 'Jstat' } },
    { tryit: { note: 'The leaking Shop, first rows and a row after the first full GC (JDK 17 has the extra `CGC`/`CGCT` columns for concurrent cycles, which the note omits).', cmd: '$ jstat -gcutil 11027 1000', out: '  S0     S1     E      O      M     CCS    YGC     YGCT     FGC    FGCT     CGC    CGCT       GCT   \n  0.00   0.00  32.00   0.00      -      -      0     0.000     0     0.000     0     0.000     0.000\n  0.00 100.00  40.00  18.33  56.77   6.66      1     0.005     0     0.000     0     0.000     0.005\n…\n  0.00   0.00  41.67  63.70  56.87   6.66      4     0.031     1     0.052     2     0.001     0.084' } },
    { table: { head: ['column', 'means'], rows: [['`S0` `S1` `E` `O`', 'survivor 0/1, eden, old: % of **current capacity**'], ['`M` `CCS`', 'metaspace, compressed class space'], ['`YGC` `YGCT`', 'young collections and their total seconds'], ['`FGC` `FGCT`', 'full (stop-the-world, whole-heap) collections'], ['`CGC` `CGCT`', 'concurrent cycles (G1 remark/cleanup pauses)'], ['`GCT`', 'total GC time']] } },
    { callout: { tone: 'pull', title: 'percent can lie', text: 'In this real run, `O` hovered between 60 % and 73 % for a full minute while `jstat -gc` showed old-gen **used** (`OU`) climbing from 0 to 391 MB, because G1 kept growing old-gen **capacity** (`OC`) from 103 MB to 595 MB. The note\'s rule "if `O` climbs and never drops, you have a leak" is right in spirit, but read it in bytes (`-gc`), or watch the floor after full GCs once the heap has reached its maximum.' } },
    { p: 'The two full GCs in the chart (`FGC` 0→1→2) were caused by our two `GC.class_histogram` calls: the histogram collects first so it can count only live objects.' },
  ] },
  { ch: 4, blocks: [
    { mini: { scene: 'Histogram' } },
    { tryit: { cmd: '$ jcmd 11027 GC.class_histogram | head -8     # at 10 s, then again at 30 s', out: ' num     #instances         #bytes  class name (module)\n-------------------------------------------------------\n   1:        439039       53889240  [B (java.base@17.0.17)\n   2:        217003        6944096  java.util.HashMap$Node (java.base@17.0.17)\n   3:        216000        6912000  Shop$Session\n   4:        222954        5350896  java.lang.String (java.base@17.0.17)\n   5:        216128        5187072  java.lang.Long (java.base@17.0.17)\n…20 s later…\n   1:       1207039      149121240  [B (java.base@17.0.17)\n   3:        600000       19200000  Shop$Session' } },
    { p: '**What grows is the leak**, and what grows with it in lockstep tells you the shape: +384,000 Sessions, +384,000 `HashMap$Node`, +384,000 `Long` keys, +384,000 `String`s and +768,000 `byte[]` (cart + the string\'s bytes). The `#bytes` column is **shallow** size: 19,200,000 / 600,000 = 32 bytes per Session.' },
    { callout: { tone: 'bad', title: 'cost', text: 'Without `-all`, `GC.class_histogram` triggers a **full GC** first (it is a safepoint operation that inspects only live objects). On a large heap that is a real stop-the-world pause. `-all` skips the GC but counts garbage too.' } },
    { h: 'Shallow vs retained' },
    { mini: { scene: 'Retained' } },
    { table: { head: ['object', 'shallow', 'retained'], rows: [['`byte[200]` cart', '216 B (16 header + 200)', '216 B'], ['`String` user + its `byte[]`', '24 B + ≈32 B', '≈56 B'], ['`Session`', '32 B', '304 B'], ['`HashMap$Node` + `Long` key', '32 B + 24 B', '360 B'], ['`HashMap` (600,000 entries)', '**48 B**', '**≈ 220 MB**']] } },
    { p: 'Cross-check: the histogram\'s five rows sum to 216.5 MB, and the table array for 600,000 entries is 2^20 slots × 4 bytes ≈ 4 MB.' },
    { h: 'Dominators and paths to GC roots' },
    { mini: { scene: 'Dominators' } },
    { list: ['**X dominates Y** if every path from a GC root to Y goes through X. The closest such X is Y\'s *immediate dominator*.', 'Hanging every object under its immediate dominator gives the **dominator tree**.', '**Retained size(X)** = the sum of shallow sizes in X\'s dominator subtree: exactly what would be freed if X became unreachable.', 'Shared objects (like `C`, reachable from both `A` and `B`) are retained by neither; they hang higher up the tree.'] },
    { callout: { tone: 'violet', title: 'deeper', text: 'Eclipse MAT computes dominators with the Lengauer–Tarjan algorithm, close to linear in the number of references, which is why it can handle dumps with hundreds of millions of objects. "Path to GC roots" should **exclude weak and soft references**: they don\'t keep anything alive.' } },
    { h: 'Taking the dump' },
    { mini: { scene: 'HeapDump' } },
    { tryit: { cmd: '$ jcmd 8730 GC.heap_dump /tmp/heap.hprof\n$ java -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=. Shop leak', out: 'Dumping heap to /tmp/heap.hprof ...\nHeap dump file created [275597746 bytes in 1.101 secs]\n…\njava.lang.OutOfMemoryError: Java heap space\nDumping heap to ./java_pid6670.hprof ...\nHeap dump file created [1269807379 bytes in 3.013 secs]' } },
    { steps: ['Open the `.hprof` in Eclipse MAT, VisualVM or IntelliJ.', 'Open the **dominator tree**, sort by **retained** size: the leak is usually row 1 or 2.', '**Path to GC roots** (excluding weak/soft refs) for one suspect object.', 'The path names the bug: a static collection, a `ThreadLocal` on a pooled thread, a listener never removed, a cache without eviction.'] },
    { callout: { tone: 'pull', text: '`HeapDumpOnOutOfMemoryError` is **manageable**: if you forgot it, `jcmd <pid> VM.set_flag HeapDumpOnOutOfMemoryError true` turns it on in a running JVM (shown for real in the Flags chapter). Make sure `HeapDumpPath` has room for a file about the size of the heap.' } },
  ] },
  { ch: 5, blocks: [
    { mini: { scene: 'JfrRing' } },
    { p: '**JDK Flight Recorder** is an event recorder compiled into HotSpot and the JDK libraries. Each event is a small binary record (timestamp, thread, stack trace id, fields) written into a **thread-local buffer** without locking. Full buffers are promoted to **global buffers**; a recorder thread writes them into **chunks** in a disk repository. With `maxsize`/`maxage` the repository behaves as a ring: the oldest chunks are deleted as new ones arrive, so a long-running recording always holds the most recent history.' },
    { table: { head: ['settings', 'stack samples (Java)', 'lock waits recorded', 'allocation samples', 'overhead'], rows: [['`default`', 'every 20 ms', '> 20 ms', '150/s', '< 1 %'], ['`profile`', 'every 10 ms', '> 10 ms', '300/s', '≈ 2 %']] } },
    { p: 'Values from JDK 17\'s `lib/jfr/default.jfc` and `profile.jfc`. What it records: CPU samples by method, allocation by call site, GC phases and pauses, safepoints, lock contention, thread parks and sleeps, file and socket I/O, exceptions, class loading, JIT compilation, CPU load, and the JVM\'s flags and environment.' },
    { h: 'Recording and reading' },
    { mini: { scene: 'JfrCommands' } },
    { tryit: { cmd: '$ jcmd 7196 JFR.start name=rec settings=profile\n$ jcmd 7196 JFR.dump name=rec filename=/tmp/rec.jfr\n$ jcmd 7196 JFR.stop name=rec\n$ jfr summary /tmp/rec.jfr\n$ jfr print --events GCPhasePause /tmp/rec.jfr', out: 'Started recording 1. No limit specified, using maxsize=250MB as default.\nDumped recording "rec", 3.4 MB written to: …\nStopped recording "rec".\n Duration: 21 s\n jdk.ExecutionSample                           1580         17361\n …\njdk.GCPhasePause {\n  startTime = 12:12:03.909\n  duration = 1.09 ms\n  gcId = 45\n  name = "GC Pause"\n  eventThread = "VM Thread" (osThreadId = 17411)\n}' } },
    { callout: { tone: 'pull', title: 'in production', text: 'Start every service with something like `-XX:StartFlightRecording:settings=default,maxage=1h,disk=true` (add `dumponexit=true,filename=…` to keep it at shutdown). At 3 a.m. you `JFR.dump` the last hour instead of trying to reproduce the problem.' } },
    { table: { head: ['version', 'addition'], rows: [['JDK 11', 'JFR open-sourced (JEP 328), free to use; also backported to 8u262'], ['JDK 14', 'event streaming API (JEP 349): consume events in-process, live'], ['JDK 21', '`jfr view` (e.g. `jfr view hot-methods rec.jfr`) and `jfr scrub` to remove events/threads before sharing'], ['JDK 25', 'CPU-time profiling (JEP 509, experimental, **Linux only**), cooperative sampling (JEP 518), method timing & tracing (JEP 520)']] } },
    { callout: { tone: 'violet', title: 'unverified', text: 'The note lists "automatic redaction of secrets in recordings" as a **Java 27** feature. I could not confirm a JEP for that, so treat it as unverified. What exists today: `jfr scrub` (JDK 21 has it) strips chosen events, categories or threads from a recording before you share it. On JDK 26 on macOS, enabling `jdk.CPUTimeSample` prints "CPU time method sampling not supported in JFR on your platform": the JDK 25 CPU-time sampler is Linux-only.' } },
  ] },
  { ch: 6, blocks: [
    { mini: { scene: 'Instrument' } },
    { table: { head: ['', 'sampling', 'instrumenting'], rows: [['how', 'periodically capture stacks', 'inject timing code into methods'], ['overhead', 'low (≈ 1 %)', 'high (2–10×)'], ['accuracy', 'statistical', 'exact counts'], ['distorts the program', 'minimally', 'yes: defeats inlining (8.8)'], ['use', 'production, first look', 'narrow, local questions']] } },
    { h: 'Safepoint bias, and a real experiment' },
    { mini: { scene: 'SafepointBias' } },
    { p: 'Profilers built on `Thread.getAllStackTraces()` / JVMTI `GetAllStackTraces` must bring threads to a **safepoint** to read their stacks, so every sample lands at a poll (method calls, loop back-edges; C2 removes polls from counted `int` loops). Time spent in poll-free code is credited to whatever poll comes next: **safepoint bias**.' },
    { p: 'JFR and async-profiler interrupt threads asynchronously, so they avoid that. But compiled code only carries **debug info** (method, bytecode index, inlined frames) at calls and safepoints. A sample whose PC falls between records is credited to a nearby record. In `Shop`, `query` was inlined and its loop has no poll, so its samples went to `toJson`:' },
    { table: { head: ['Shop frame', 'JDK 17 default', 'with -XX:+DebugNonSafepoints'], rows: [['`format`', '930', '912'], ['`query`', '**0**', '**347**'], ['`toJson`', '**474**', '**38**'], ['`parse`', '24', '29'], ['total samples', '1,437', '1,333']] } },
    { tryit: { note: 'Reproduce it (JDK 26 shows the same effect: 0 vs 230 samples for `query`).', cmd: '$ java -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints \\\n    -XX:StartFlightRecording=duration=20s,filename=rec2.jfr,settings=profile Shop cpu\n$ jfr print --json --stack-depth 64 --events jdk.ExecutionSample rec2.jfr > samples.json', out: '[0.230s][info][jfr,startup] Started recording 1. The result will be written to:\n[0.230s][info][jfr,startup] …/rec2.jfr' } },
    { callout: { tone: 'pull', title: 'correction to the note', text: 'The note says "most JVM sampling profilers only sample at safepoints" and that async-profiler avoids the problem by using signals. More precisely: JFR also samples without waiting for safepoints; both JFR and async-profiler still need `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` for accurate attribution inside inlined, poll-free code (async-profiler\'s documentation recommends it). Also note `jfr print` shows only 5 frames per stack unless you pass `--stack-depth`.' } },
    { h: 'Flame graphs' },
    { mini: { scene: 'FlameBuild' } },
    { steps: ['Collect stack samples (each is a list of frames, root first).', 'Sort them lexicographically so identical prefixes are adjacent.', 'Merge adjacent equal frames at each depth into one box.', 'Box width = number of samples containing that frame; the exposed top = self time.'] },
    { mini: { scene: 'FlameRead' } },
    { list: ['**Width = share of samples** (time on CPU for a CPU profile). Height is just stack depth.', '**x-order is alphabetical**, not chronological.', 'Look for **wide plateaus near the top**: wide boxes with little above them are where time is actually spent.', 'In `Shop` (real JFR stacks, aggregated by hand): `format` 68 %, `query` 26 %, `toJson` 3 %, `parse` 2 %.'] },
    { code: '$ ./profiler.sh -d 30 -f flame.html <pid>          # async-profiler (not installed here)\n$ asprof -d 30 -e cpu -f flame.html <pid>          # newer releases ship the asprof launcher', lang: 'shell', title: 'async-profiler' },
  ] },
  { ch: 7, blocks: [
    { mini: { scene: 'Flags' } },
    { tryit: { cmd: '$ java -XX:+PrintFlagsFinal -version | grep -E "MaxHeapSize|MaxRAMPercentage|UseG1GC|ThreadStackSize"', out: '   size_t MaxHeapSize                              = 2147483648                                {product} {ergonomic}\n   double MaxRAMPercentage                         = 25.000000                                 {product} {default}\n     intx ThreadStackSize                          = 2048                                   {pd product} {default}\n     bool UseG1GC                                  = true                                      {product} {ergonomic}' } },
    { table: { head: ['origin', 'means'], rows: [['`{default}`', 'built-in default'], ['`{ergonomic}`', '**the JVM chose it** from CPU count and memory'], ['`{command line}`', 'you set it'], ['others', 'e.g. `{environment}` (from `JAVA_TOOL_OPTIONS`), `{management}` (set live)']] } },
    { p: '`MaxHeapSize` = 25 % (`MaxRAMPercentage`) of 8 GB = 2 GB on this machine. In a container the JVM uses the **container memory limit** instead of the host\'s RAM (8.3), so the default is rarely what anyone expects. For a running JVM use `jcmd <pid> VM.flags` (non-default flags) or `VM.flags -all`.' },
    { tryit: { note: 'Manageable flags can be changed live; others cannot.', cmd: '$ jcmd 14768 VM.set_flag HeapDumpOnOutOfMemoryError true\n$ jcmd 14768 VM.set_flag MaxHeapSize 100000000', out: '14768:\nCommand executed successfully\n14768:\nonly \'writeable\' flags can be set' } },
    { h: 'JMX and MBeans' },
    { mini: { scene: 'Jmx' } },
    { code: 'var mem = ManagementFactory.getMemoryMXBean();\nmem.getHeapMemoryUsage();                                     // init, used, committed, max\nManagementFactory.getThreadMXBean().findDeadlockedThreads();  // monitors + ownable synchronizers\nManagementFactory.getGarbageCollectorMXBeans();\nManagementFactory.getRuntimeMXBean().getInputArguments();     // the JVM\'s own args', title: 'platform MXBeans' },
    { tryit: { cmd: '$ java -Xmx256m Watch', out: 'init = 134217728(131072K) used = 1998848(1952K) committed = 136314880(133120K) max = 268435456(262144K)\ncheckout waits for java.lang.Object@2f92e0f4 held by refund\nrefund waits for java.lang.Object@2a84aee7 held by checkout\nG1 Young Generation count=0\nG1 Old Generation count=0\n[-Xmx256m]' } },
    { callout: { tone: 'bad', title: 'secure it', text: '`-Dcom.sun.management.jmxremote.port=9010` (or `jcmd <pid> ManagementAgent.start jmxremote.port=9010 …` at runtime) opens remote control of the JVM: invoke operations, trigger dumps. Never expose it without authentication and TLS. In practice most teams export MXBean values with Micrometer to Prometheus instead of connecting interactively.' } },
  ] },
  { ch: 8, blocks: [
    { mini: { scene: 'Nmt' } },
    { tryit: { cmd: '$ java -Xmx1g -XX:NativeMemoryTracking=summary Shop leak &\n$ jcmd 6670 VM.native_memory summary', out: 'Total: reserved=2587481KB, committed=701529KB\n-                 Java Heap (reserved=1048576KB, committed=539648KB)\n-                     Class (reserved=1048669KB, committed=221KB)\n-                    Thread (reserved=68059KB, committed=68059KB)\n                            (thread #33)\n-                      Code (reserved=247742KB, committed=7630KB)\n-                        GC (reserved=90354KB, committed=71522KB)\n…' } },
    { list: ['**Thread stacks**: here 33 threads × ≈ 2 MB (macOS/AArch64 default `ThreadStackSize=2048K`; Linux x64 is 1 MB). 1,000 platform threads reserve 1–2 GB of stack, one reason virtual threads exist.', '**Class / metaspace**: grows with loaded classes; steady growth means a class-loader leak (8.2).', '**GC**: remembered sets and marking bitmaps; G1 typically needs a few to ~10 % of the heap.', '**Code**: the JIT\'s code cache (8.8).', '**Other / Internal**: includes direct `ByteBuffer`s (Netty, NIO).'] },
    { callout: { tone: 'pull', title: 'correction to the note', text: 'The note says "1 MB per thread". That is the Linux x64 default; on macOS/AArch64 (this machine) `ThreadStackSize` is 2048 KB. Also, a stack is **reserved** up front but pages are only touched as the stack grows, so resident memory per thread is usually far below the reservation.' } },
    { callout: { tone: 'violet', title: 'deeper', text: '`-XX:NativeMemoryTracking=summary` must be set at startup (the `detail` level also records call sites, at higher cost). Use `jcmd <pid> VM.native_memory baseline`, then later `VM.native_memory summary.diff` to see which category grew. NMT tracks only allocations made by the JVM itself: native libraries calling `malloc` directly are invisible to it.' } },
  ] },
  { ch: 9, blocks: [
    { mini: { scene: 'Playbook' } },
    { table: { head: ['symptom', 'first move'], rows: [['slow, high CPU', 'JFR or async-profiler → flame graph (with `DebugNonSafepoints`)'], ['slow, low CPU', 'three thread dumps 10 s apart → what is blocked or waiting'], ['frozen', 'thread dump → scroll to `Found one Java-level deadlock`'], ['memory grows steadily', '`GC.class_histogram` twice → what grows → heap dump'], ['OOM', 'the `HeapDumpOnOutOfMemoryError` file → sort by retained size'], ['long pauses', '`-Xlog:gc*,safepoint`: if a pause ≫ GC work, threads were slow to reach the safepoint (8.5)'], ['RSS ≫ heap', 'Native Memory Tracking, `baseline` + `summary.diff`'], ['"what settings is it using?"', '`jcmd <pid> VM.flags`, `-XX:+PrintFlagsFinal`']] } },
    { callout: { tone: 'pull', text: '**The habit worth building:** `jps` → `jcmd <pid> help` → pick the command. Most of an incident can be diagnosed from those, a thread dump and a JFR recording, with no agent, no restart and no code change.' } },
  ] },
];

const traps = [
  'One thread dump: take **three**, ~10 s apart. One is a snapshot; three show what is stuck.',
  '`RUNNABLE` does not mean using CPU: native code and blocking I/O also show as `RUNNABLE`. Check `cpu=`.',
  'Sorting a heap dump by shallow size: sort by **retained** size.',
  'Reading `jstat -gcutil` percentages as sizes: they are % of a capacity that can grow. Use `-gc` for bytes.',
  'Running an instrumenting profiler in production: 2–10× overhead, and it defeats inlining.',
  'Profiling without `-XX:+DebugNonSafepoints`: samples in inlined, poll-free code get blamed on neighbours.',
  'Adding `-XX:+HeapDumpOnOutOfMemoryError` after the OOM: too late. Add it now (or `VM.set_flag` it live).',
  '"JFR is a paid feature": free and open source since JDK 11.',
  '"The deadlock detector misses `ReentrantLock`": it finds them; it misses semaphores, latches and external locks.',
];

const recap = [
  '**`jps` / `jcmd <pid> help`**: start here; `jcmd` subsumes `jstack`, `jmap`, `jinfo`. It attaches via a trigger file, `SIGQUIT` and a Unix socket.',
  '**`Thread.print`**: states, `locked` / `waiting to lock`, `cpu=`; three dumps; `Found one Java-level deadlock` at the bottom.',
  '**`jstat -gcutil <pid> 1s`**: live GC heartbeat; `-gc` for sizes.',
  '**`GC.class_histogram`** twice: what grows is the leak (it forces a full GC).',
  '**Heap dump + MAT**: dominator tree, **retained** size, path to GC roots.',
  '**JFR**: always-on event ring, < 1 % with `default`; `JFR.start/dump/stop`, `jfr summary/print`.',
  '**Profiling**: sampling over instrumenting; flame graphs read by width; `DebugNonSafepoints` for honest attribution.',
  '**`-XX:+PrintFlagsFinal`** / `VM.flags`: what the JVM actually chose; **NMT** for memory outside the heap.',
];

const quiz = [
  { q: 'Why take three thread dumps about ten seconds apart rather than one?', options: ['The first dump is often incomplete', 'A thread caught in a method once might just be passing through; one stuck in the same frame with flat cpu= across all three is really stuck', 'The JVM only detects deadlocks on the third dump', 'Each dump only shows a third of the threads'], answer: 1, why: 'A dump is a snapshot. Comparing three separates threads that are stuck (same frame, CPU not moving) from threads that are busy (frames change, CPU climbs).' },
  { q: 'A thread shows `RUNNABLE` with `cpu=0.12ms elapsed=7.08s`, top frame a native method. What is it most likely doing?', options: ['Spinning at 100 % CPU', 'Waiting inside native code (e.g. a blocking read): the JVM reports it as RUNNABLE', 'It is about to be garbage collected', 'It is BLOCKED but the dump is wrong'], answer: 1, why: 'The JVM cannot see what native code is doing, so blocking I/O and native waits show as RUNNABLE. Almost no CPU in 7 s proves it is not running.' },
  { q: 'Thread A: `waiting to lock <0x…878>`, `locked <0x…868>`. Thread B: `waiting to lock <0x…868>`, `locked <0x…878>`. What is this?', options: ['Lock contention that will resolve', 'A deadlock: a cycle in the wait-for graph', 'Two threads sharing one lock correctly', 'A livelock'], answer: 1, why: 'Each thread wants what the other holds. The wait-for graph has a cycle, so neither can ever proceed; the JVM prints "Found one Java-level deadlock".' },
  { q: 'Two threads deadlock on two `ReentrantLock`s. What does `jcmd Thread.print` (JDK 17) show?', options: ['Nothing: only synchronized monitors are checked', '"Found one Java-level deadlock" with "waiting for ownable synchronizer … held by …"', 'Both threads as BLOCKED with no deadlock section', 'An exception in the target JVM'], answer: 1, why: 'ReentrantLock extends AbstractOwnableSynchronizer, which records its owner, so the detector can follow the cycle. Semaphores and latches have no owner and are not detected.' },
  { q: 'A `HashMap` shows 48 bytes shallow and 220 MB retained. Which number matters for a leak, and why?', options: ['Shallow: it is the real object size', 'Retained: it is what would be freed if the map became unreachable, including all entries only it keeps alive', 'Neither: only instance counts matter', 'Shallow, because retained double-counts shared objects'], answer: 1, why: 'Retained size sums the dominator subtree: everything exclusively kept alive by the object. Sorting by it puts the leaking map at the top.' },
  { q: 'Objects A and B both reference C. What is C\'s contribution to A\'s retained size?', options: ['All of C, because A references it', 'Half of C', 'Nothing: C stays reachable through B, so A does not dominate it', 'Nothing, because C is garbage'], answer: 2, why: 'A dominates only objects every path to which goes through A. C is reachable via B, so removing A frees nothing of C.' },
  { q: '`jstat -gcutil` shows old gen bouncing between 60 % and 73 % for a minute. Can you conclude there is no leak?', options: ['Yes, it is stable', 'No: the percentages are of current capacity, which G1 can grow; check OU in `jstat -gc`', 'Yes, if FGC is non-zero', 'No, because -gcutil only shows young gen'], answer: 1, why: 'In the real Shop run, OU climbed 0 → 391 MB while O% stayed around 60–73 %, because old-gen capacity grew from 103 MB to 595 MB.' },
  { q: 'A JFR profile of Shop shows `query` with 0 samples and `toJson` with 474. With `-XX:+DebugNonSafepoints`, `query` gets 347. Why?', options: ['JFR randomly drops samples', 'Compiled code records its location only at calls and safepoints; samples inside the inlined, poll-free loop were credited to the next record, in toJson', 'query only runs when the flag is set', 'The flag makes query slower'], answer: 1, why: 'Debug info exists only at certain PCs. DebugNonSafepoints makes the JIT record more, so samples are attributed to the code actually running.' },
  { q: 'In a flame graph, what does the horizontal position of a box tell you?', options: ['When the method ran', 'Nothing meaningful: boxes are sorted alphabetically; only width matters', 'Which thread ran it', 'How deep the stack was'], answer: 1, why: 'Samples are sorted and merged, so the x-order is alphabetical. Width is the share of samples; height is stack depth.' },
  { q: 'RSS is 6 GB, the heap is 1 GB and metaspace is 200 MB. What should you check next?', options: ['Increase -Xmx', 'Native Memory Tracking (thread stacks, GC structures, code cache, direct buffers), then native libraries NMT cannot see', 'Take a heap dump', 'Run jstat -gcutil'], answer: 1, why: 'The heap and metaspace explain 1.2 GB. NMT breaks down the JVM\'s own native memory; if its total is still far below RSS, suspect malloc from native libraries.' },
];

window.AN.registerTopic({
  id: '8.9', part: '08', title: 'Observing a running JVM', kicker: 'Part 08 · The JVM',
  lede: 'jcmd, thread dumps, heap dumps, JFR and profilers, used on one misbehaving service that deadlocks, leaks and burns CPU. Everything works on a live process: no restart, no code change.',
  chapters, scenes, captions, notes, traps, recap, quiz,
});
